// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from 'dotenv';
import { defineConfig } from 'prisma/config';

config({ path: 'apps/backend/.env' });
config({ path: '.env.backend' });

function buildPostgresUrl() {
  const {
    POSTGRES_HOST,
    POSTGRES_PORT,
    POSTGRES_USER,
    POSTGRES_PASSWORD,
    POSTGRES_DB,
    POSTGRES_SCHEMA = 'public',
  } = process.env;

  if (!POSTGRES_HOST || !POSTGRES_PORT || !POSTGRES_USER || !POSTGRES_PASSWORD || !POSTGRES_DB) {
    throw new Error(
      'PostgreSQL env is incomplete. Required: POSTGRES_HOST, POSTGRES_PORT, POSTGRES_USER, POSTGRES_PASSWORD, POSTGRES_DB.',
    );
  }

  const encodedUser = encodeURIComponent(POSTGRES_USER);
  const encodedPassword = encodeURIComponent(POSTGRES_PASSWORD);
  const encodedSchema = encodeURIComponent(POSTGRES_SCHEMA);

  return `postgresql://${encodedUser}:${encodedPassword}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?schema=${encodedSchema}`;
}

// DB connection is environment-driven — no branching needed in config.
// local : POSTGRES_HOST="localhost"
// docker: POSTGRES_HOST="postgres"
const DATABASE_URL = buildPostgresUrl();

export default defineConfig({
  schema: 'prisma/schema',
  migrations: {
    path: 'prisma/migrations',
    seed: 'npx ts-node prisma/seeds/index.ts',
  },
  datasource: {
    url: DATABASE_URL,
  },
});
