
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `FeaturedCategory` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model FeaturedCategory
 * 
 */
export type FeaturedCategoryModel = runtime.Types.Result.DefaultSelection<Prisma.$FeaturedCategoryPayload>

export type AggregateFeaturedCategory = {
  _count: FeaturedCategoryCountAggregateOutputType | null
  _avg: FeaturedCategoryAvgAggregateOutputType | null
  _sum: FeaturedCategorySumAggregateOutputType | null
  _min: FeaturedCategoryMinAggregateOutputType | null
  _max: FeaturedCategoryMaxAggregateOutputType | null
}

export type FeaturedCategoryAvgAggregateOutputType = {
  order: number | null
}

export type FeaturedCategorySumAggregateOutputType = {
  order: number | null
}

export type FeaturedCategoryMinAggregateOutputType = {
  id: string | null
  category_id: string | null
  order: number | null
  is_active: boolean | null
  created_at: Date | null
  updated_at: Date | null
}

export type FeaturedCategoryMaxAggregateOutputType = {
  id: string | null
  category_id: string | null
  order: number | null
  is_active: boolean | null
  created_at: Date | null
  updated_at: Date | null
}

export type FeaturedCategoryCountAggregateOutputType = {
  id: number
  category_id: number
  order: number
  is_active: number
  created_at: number
  updated_at: number
  _all: number
}


export type FeaturedCategoryAvgAggregateInputType = {
  order?: true
}

export type FeaturedCategorySumAggregateInputType = {
  order?: true
}

export type FeaturedCategoryMinAggregateInputType = {
  id?: true
  category_id?: true
  order?: true
  is_active?: true
  created_at?: true
  updated_at?: true
}

export type FeaturedCategoryMaxAggregateInputType = {
  id?: true
  category_id?: true
  order?: true
  is_active?: true
  created_at?: true
  updated_at?: true
}

export type FeaturedCategoryCountAggregateInputType = {
  id?: true
  category_id?: true
  order?: true
  is_active?: true
  created_at?: true
  updated_at?: true
  _all?: true
}

export type FeaturedCategoryAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which FeaturedCategory to aggregate.
   */
  where?: Prisma.FeaturedCategoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FeaturedCategories to fetch.
   */
  orderBy?: Prisma.FeaturedCategoryOrderByWithRelationInput | Prisma.FeaturedCategoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.FeaturedCategoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FeaturedCategories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FeaturedCategories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned FeaturedCategories
  **/
  _count?: true | FeaturedCategoryCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: FeaturedCategoryAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: FeaturedCategorySumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: FeaturedCategoryMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: FeaturedCategoryMaxAggregateInputType
}

export type GetFeaturedCategoryAggregateType<T extends FeaturedCategoryAggregateArgs> = {
      [P in keyof T & keyof AggregateFeaturedCategory]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateFeaturedCategory[P]>
    : Prisma.GetScalarType<T[P], AggregateFeaturedCategory[P]>
}




export type FeaturedCategoryGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.FeaturedCategoryWhereInput
  orderBy?: Prisma.FeaturedCategoryOrderByWithAggregationInput | Prisma.FeaturedCategoryOrderByWithAggregationInput[]
  by: Prisma.FeaturedCategoryScalarFieldEnum[] | Prisma.FeaturedCategoryScalarFieldEnum
  having?: Prisma.FeaturedCategoryScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: FeaturedCategoryCountAggregateInputType | true
  _avg?: FeaturedCategoryAvgAggregateInputType
  _sum?: FeaturedCategorySumAggregateInputType
  _min?: FeaturedCategoryMinAggregateInputType
  _max?: FeaturedCategoryMaxAggregateInputType
}

export type FeaturedCategoryGroupByOutputType = {
  id: string
  category_id: string
  order: number
  is_active: boolean
  created_at: Date
  updated_at: Date
  _count: FeaturedCategoryCountAggregateOutputType | null
  _avg: FeaturedCategoryAvgAggregateOutputType | null
  _sum: FeaturedCategorySumAggregateOutputType | null
  _min: FeaturedCategoryMinAggregateOutputType | null
  _max: FeaturedCategoryMaxAggregateOutputType | null
}

export type GetFeaturedCategoryGroupByPayload<T extends FeaturedCategoryGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<FeaturedCategoryGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof FeaturedCategoryGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], FeaturedCategoryGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], FeaturedCategoryGroupByOutputType[P]>
      }
    >
  >



export type FeaturedCategoryWhereInput = {
  AND?: Prisma.FeaturedCategoryWhereInput | Prisma.FeaturedCategoryWhereInput[]
  OR?: Prisma.FeaturedCategoryWhereInput[]
  NOT?: Prisma.FeaturedCategoryWhereInput | Prisma.FeaturedCategoryWhereInput[]
  id?: Prisma.StringFilter<"FeaturedCategory"> | string
  category_id?: Prisma.StringFilter<"FeaturedCategory"> | string
  order?: Prisma.IntFilter<"FeaturedCategory"> | number
  is_active?: Prisma.BoolFilter<"FeaturedCategory"> | boolean
  created_at?: Prisma.DateTimeFilter<"FeaturedCategory"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"FeaturedCategory"> | Date | string
  category?: Prisma.XOR<Prisma.ProductCategoryScalarRelationFilter, Prisma.ProductCategoryWhereInput>
}

export type FeaturedCategoryOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  category_id?: Prisma.SortOrder
  order?: Prisma.SortOrder
  is_active?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  category?: Prisma.ProductCategoryOrderByWithRelationInput
}

export type FeaturedCategoryWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  category_id?: string
  AND?: Prisma.FeaturedCategoryWhereInput | Prisma.FeaturedCategoryWhereInput[]
  OR?: Prisma.FeaturedCategoryWhereInput[]
  NOT?: Prisma.FeaturedCategoryWhereInput | Prisma.FeaturedCategoryWhereInput[]
  order?: Prisma.IntFilter<"FeaturedCategory"> | number
  is_active?: Prisma.BoolFilter<"FeaturedCategory"> | boolean
  created_at?: Prisma.DateTimeFilter<"FeaturedCategory"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"FeaturedCategory"> | Date | string
  category?: Prisma.XOR<Prisma.ProductCategoryScalarRelationFilter, Prisma.ProductCategoryWhereInput>
}, "id" | "category_id">

export type FeaturedCategoryOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  category_id?: Prisma.SortOrder
  order?: Prisma.SortOrder
  is_active?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  _count?: Prisma.FeaturedCategoryCountOrderByAggregateInput
  _avg?: Prisma.FeaturedCategoryAvgOrderByAggregateInput
  _max?: Prisma.FeaturedCategoryMaxOrderByAggregateInput
  _min?: Prisma.FeaturedCategoryMinOrderByAggregateInput
  _sum?: Prisma.FeaturedCategorySumOrderByAggregateInput
}

export type FeaturedCategoryScalarWhereWithAggregatesInput = {
  AND?: Prisma.FeaturedCategoryScalarWhereWithAggregatesInput | Prisma.FeaturedCategoryScalarWhereWithAggregatesInput[]
  OR?: Prisma.FeaturedCategoryScalarWhereWithAggregatesInput[]
  NOT?: Prisma.FeaturedCategoryScalarWhereWithAggregatesInput | Prisma.FeaturedCategoryScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"FeaturedCategory"> | string
  category_id?: Prisma.StringWithAggregatesFilter<"FeaturedCategory"> | string
  order?: Prisma.IntWithAggregatesFilter<"FeaturedCategory"> | number
  is_active?: Prisma.BoolWithAggregatesFilter<"FeaturedCategory"> | boolean
  created_at?: Prisma.DateTimeWithAggregatesFilter<"FeaturedCategory"> | Date | string
  updated_at?: Prisma.DateTimeWithAggregatesFilter<"FeaturedCategory"> | Date | string
}

export type FeaturedCategoryCreateInput = {
  id?: string
  order?: number
  is_active?: boolean
  created_at?: Date | string
  updated_at?: Date | string
  category: Prisma.ProductCategoryCreateNestedOneWithoutFeatured_categoryInput
}

export type FeaturedCategoryUncheckedCreateInput = {
  id?: string
  category_id: string
  order?: number
  is_active?: boolean
  created_at?: Date | string
  updated_at?: Date | string
}

export type FeaturedCategoryUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  is_active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  category?: Prisma.ProductCategoryUpdateOneRequiredWithoutFeatured_categoryNestedInput
}

export type FeaturedCategoryUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  category_id?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  is_active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FeaturedCategoryCreateManyInput = {
  id?: string
  category_id: string
  order?: number
  is_active?: boolean
  created_at?: Date | string
  updated_at?: Date | string
}

export type FeaturedCategoryUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  is_active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FeaturedCategoryUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  category_id?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  is_active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FeaturedCategoryNullableScalarRelationFilter = {
  is?: Prisma.FeaturedCategoryWhereInput | null
  isNot?: Prisma.FeaturedCategoryWhereInput | null
}

export type FeaturedCategoryCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  category_id?: Prisma.SortOrder
  order?: Prisma.SortOrder
  is_active?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type FeaturedCategoryAvgOrderByAggregateInput = {
  order?: Prisma.SortOrder
}

export type FeaturedCategoryMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  category_id?: Prisma.SortOrder
  order?: Prisma.SortOrder
  is_active?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type FeaturedCategoryMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  category_id?: Prisma.SortOrder
  order?: Prisma.SortOrder
  is_active?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type FeaturedCategorySumOrderByAggregateInput = {
  order?: Prisma.SortOrder
}

export type FeaturedCategoryCreateNestedOneWithoutCategoryInput = {
  create?: Prisma.XOR<Prisma.FeaturedCategoryCreateWithoutCategoryInput, Prisma.FeaturedCategoryUncheckedCreateWithoutCategoryInput>
  connectOrCreate?: Prisma.FeaturedCategoryCreateOrConnectWithoutCategoryInput
  connect?: Prisma.FeaturedCategoryWhereUniqueInput
}

export type FeaturedCategoryUncheckedCreateNestedOneWithoutCategoryInput = {
  create?: Prisma.XOR<Prisma.FeaturedCategoryCreateWithoutCategoryInput, Prisma.FeaturedCategoryUncheckedCreateWithoutCategoryInput>
  connectOrCreate?: Prisma.FeaturedCategoryCreateOrConnectWithoutCategoryInput
  connect?: Prisma.FeaturedCategoryWhereUniqueInput
}

export type FeaturedCategoryUpdateOneWithoutCategoryNestedInput = {
  create?: Prisma.XOR<Prisma.FeaturedCategoryCreateWithoutCategoryInput, Prisma.FeaturedCategoryUncheckedCreateWithoutCategoryInput>
  connectOrCreate?: Prisma.FeaturedCategoryCreateOrConnectWithoutCategoryInput
  upsert?: Prisma.FeaturedCategoryUpsertWithoutCategoryInput
  disconnect?: Prisma.FeaturedCategoryWhereInput | boolean
  delete?: Prisma.FeaturedCategoryWhereInput | boolean
  connect?: Prisma.FeaturedCategoryWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.FeaturedCategoryUpdateToOneWithWhereWithoutCategoryInput, Prisma.FeaturedCategoryUpdateWithoutCategoryInput>, Prisma.FeaturedCategoryUncheckedUpdateWithoutCategoryInput>
}

export type FeaturedCategoryUncheckedUpdateOneWithoutCategoryNestedInput = {
  create?: Prisma.XOR<Prisma.FeaturedCategoryCreateWithoutCategoryInput, Prisma.FeaturedCategoryUncheckedCreateWithoutCategoryInput>
  connectOrCreate?: Prisma.FeaturedCategoryCreateOrConnectWithoutCategoryInput
  upsert?: Prisma.FeaturedCategoryUpsertWithoutCategoryInput
  disconnect?: Prisma.FeaturedCategoryWhereInput | boolean
  delete?: Prisma.FeaturedCategoryWhereInput | boolean
  connect?: Prisma.FeaturedCategoryWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.FeaturedCategoryUpdateToOneWithWhereWithoutCategoryInput, Prisma.FeaturedCategoryUpdateWithoutCategoryInput>, Prisma.FeaturedCategoryUncheckedUpdateWithoutCategoryInput>
}

export type FeaturedCategoryCreateWithoutCategoryInput = {
  id?: string
  order?: number
  is_active?: boolean
  created_at?: Date | string
  updated_at?: Date | string
}

export type FeaturedCategoryUncheckedCreateWithoutCategoryInput = {
  id?: string
  order?: number
  is_active?: boolean
  created_at?: Date | string
  updated_at?: Date | string
}

export type FeaturedCategoryCreateOrConnectWithoutCategoryInput = {
  where: Prisma.FeaturedCategoryWhereUniqueInput
  create: Prisma.XOR<Prisma.FeaturedCategoryCreateWithoutCategoryInput, Prisma.FeaturedCategoryUncheckedCreateWithoutCategoryInput>
}

export type FeaturedCategoryUpsertWithoutCategoryInput = {
  update: Prisma.XOR<Prisma.FeaturedCategoryUpdateWithoutCategoryInput, Prisma.FeaturedCategoryUncheckedUpdateWithoutCategoryInput>
  create: Prisma.XOR<Prisma.FeaturedCategoryCreateWithoutCategoryInput, Prisma.FeaturedCategoryUncheckedCreateWithoutCategoryInput>
  where?: Prisma.FeaturedCategoryWhereInput
}

export type FeaturedCategoryUpdateToOneWithWhereWithoutCategoryInput = {
  where?: Prisma.FeaturedCategoryWhereInput
  data: Prisma.XOR<Prisma.FeaturedCategoryUpdateWithoutCategoryInput, Prisma.FeaturedCategoryUncheckedUpdateWithoutCategoryInput>
}

export type FeaturedCategoryUpdateWithoutCategoryInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  is_active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FeaturedCategoryUncheckedUpdateWithoutCategoryInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  is_active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type FeaturedCategorySelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  category_id?: boolean
  order?: boolean
  is_active?: boolean
  created_at?: boolean
  updated_at?: boolean
  category?: boolean | Prisma.ProductCategoryDefaultArgs<ExtArgs>
}, ExtArgs["result"]["featuredCategory"]>

export type FeaturedCategorySelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  category_id?: boolean
  order?: boolean
  is_active?: boolean
  created_at?: boolean
  updated_at?: boolean
  category?: boolean | Prisma.ProductCategoryDefaultArgs<ExtArgs>
}, ExtArgs["result"]["featuredCategory"]>

export type FeaturedCategorySelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  category_id?: boolean
  order?: boolean
  is_active?: boolean
  created_at?: boolean
  updated_at?: boolean
  category?: boolean | Prisma.ProductCategoryDefaultArgs<ExtArgs>
}, ExtArgs["result"]["featuredCategory"]>

export type FeaturedCategorySelectScalar = {
  id?: boolean
  category_id?: boolean
  order?: boolean
  is_active?: boolean
  created_at?: boolean
  updated_at?: boolean
}

export type FeaturedCategoryOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "category_id" | "order" | "is_active" | "created_at" | "updated_at", ExtArgs["result"]["featuredCategory"]>
export type FeaturedCategoryInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  category?: boolean | Prisma.ProductCategoryDefaultArgs<ExtArgs>
}
export type FeaturedCategoryIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  category?: boolean | Prisma.ProductCategoryDefaultArgs<ExtArgs>
}
export type FeaturedCategoryIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  category?: boolean | Prisma.ProductCategoryDefaultArgs<ExtArgs>
}

export type $FeaturedCategoryPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "FeaturedCategory"
  objects: {
    category: Prisma.$ProductCategoryPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    category_id: string
    order: number
    is_active: boolean
    created_at: Date
    updated_at: Date
  }, ExtArgs["result"]["featuredCategory"]>
  composites: {}
}

export type FeaturedCategoryGetPayload<S extends boolean | null | undefined | FeaturedCategoryDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$FeaturedCategoryPayload, S>

export type FeaturedCategoryCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<FeaturedCategoryFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: FeaturedCategoryCountAggregateInputType | true
  }

export interface FeaturedCategoryDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['FeaturedCategory'], meta: { name: 'FeaturedCategory' } }
  /**
   * Find zero or one FeaturedCategory that matches the filter.
   * @param {FeaturedCategoryFindUniqueArgs} args - Arguments to find a FeaturedCategory
   * @example
   * // Get one FeaturedCategory
   * const featuredCategory = await prisma.featuredCategory.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends FeaturedCategoryFindUniqueArgs>(args: Prisma.SelectSubset<T, FeaturedCategoryFindUniqueArgs<ExtArgs>>): Prisma.Prisma__FeaturedCategoryClient<runtime.Types.Result.GetResult<Prisma.$FeaturedCategoryPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one FeaturedCategory that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {FeaturedCategoryFindUniqueOrThrowArgs} args - Arguments to find a FeaturedCategory
   * @example
   * // Get one FeaturedCategory
   * const featuredCategory = await prisma.featuredCategory.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends FeaturedCategoryFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, FeaturedCategoryFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__FeaturedCategoryClient<runtime.Types.Result.GetResult<Prisma.$FeaturedCategoryPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first FeaturedCategory that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FeaturedCategoryFindFirstArgs} args - Arguments to find a FeaturedCategory
   * @example
   * // Get one FeaturedCategory
   * const featuredCategory = await prisma.featuredCategory.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends FeaturedCategoryFindFirstArgs>(args?: Prisma.SelectSubset<T, FeaturedCategoryFindFirstArgs<ExtArgs>>): Prisma.Prisma__FeaturedCategoryClient<runtime.Types.Result.GetResult<Prisma.$FeaturedCategoryPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first FeaturedCategory that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FeaturedCategoryFindFirstOrThrowArgs} args - Arguments to find a FeaturedCategory
   * @example
   * // Get one FeaturedCategory
   * const featuredCategory = await prisma.featuredCategory.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends FeaturedCategoryFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, FeaturedCategoryFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__FeaturedCategoryClient<runtime.Types.Result.GetResult<Prisma.$FeaturedCategoryPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more FeaturedCategories that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FeaturedCategoryFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all FeaturedCategories
   * const featuredCategories = await prisma.featuredCategory.findMany()
   * 
   * // Get first 10 FeaturedCategories
   * const featuredCategories = await prisma.featuredCategory.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const featuredCategoryWithIdOnly = await prisma.featuredCategory.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends FeaturedCategoryFindManyArgs>(args?: Prisma.SelectSubset<T, FeaturedCategoryFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FeaturedCategoryPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a FeaturedCategory.
   * @param {FeaturedCategoryCreateArgs} args - Arguments to create a FeaturedCategory.
   * @example
   * // Create one FeaturedCategory
   * const FeaturedCategory = await prisma.featuredCategory.create({
   *   data: {
   *     // ... data to create a FeaturedCategory
   *   }
   * })
   * 
   */
  create<T extends FeaturedCategoryCreateArgs>(args: Prisma.SelectSubset<T, FeaturedCategoryCreateArgs<ExtArgs>>): Prisma.Prisma__FeaturedCategoryClient<runtime.Types.Result.GetResult<Prisma.$FeaturedCategoryPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many FeaturedCategories.
   * @param {FeaturedCategoryCreateManyArgs} args - Arguments to create many FeaturedCategories.
   * @example
   * // Create many FeaturedCategories
   * const featuredCategory = await prisma.featuredCategory.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends FeaturedCategoryCreateManyArgs>(args?: Prisma.SelectSubset<T, FeaturedCategoryCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many FeaturedCategories and returns the data saved in the database.
   * @param {FeaturedCategoryCreateManyAndReturnArgs} args - Arguments to create many FeaturedCategories.
   * @example
   * // Create many FeaturedCategories
   * const featuredCategory = await prisma.featuredCategory.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many FeaturedCategories and only return the `id`
   * const featuredCategoryWithIdOnly = await prisma.featuredCategory.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends FeaturedCategoryCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, FeaturedCategoryCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FeaturedCategoryPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a FeaturedCategory.
   * @param {FeaturedCategoryDeleteArgs} args - Arguments to delete one FeaturedCategory.
   * @example
   * // Delete one FeaturedCategory
   * const FeaturedCategory = await prisma.featuredCategory.delete({
   *   where: {
   *     // ... filter to delete one FeaturedCategory
   *   }
   * })
   * 
   */
  delete<T extends FeaturedCategoryDeleteArgs>(args: Prisma.SelectSubset<T, FeaturedCategoryDeleteArgs<ExtArgs>>): Prisma.Prisma__FeaturedCategoryClient<runtime.Types.Result.GetResult<Prisma.$FeaturedCategoryPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one FeaturedCategory.
   * @param {FeaturedCategoryUpdateArgs} args - Arguments to update one FeaturedCategory.
   * @example
   * // Update one FeaturedCategory
   * const featuredCategory = await prisma.featuredCategory.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends FeaturedCategoryUpdateArgs>(args: Prisma.SelectSubset<T, FeaturedCategoryUpdateArgs<ExtArgs>>): Prisma.Prisma__FeaturedCategoryClient<runtime.Types.Result.GetResult<Prisma.$FeaturedCategoryPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more FeaturedCategories.
   * @param {FeaturedCategoryDeleteManyArgs} args - Arguments to filter FeaturedCategories to delete.
   * @example
   * // Delete a few FeaturedCategories
   * const { count } = await prisma.featuredCategory.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends FeaturedCategoryDeleteManyArgs>(args?: Prisma.SelectSubset<T, FeaturedCategoryDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more FeaturedCategories.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FeaturedCategoryUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many FeaturedCategories
   * const featuredCategory = await prisma.featuredCategory.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends FeaturedCategoryUpdateManyArgs>(args: Prisma.SelectSubset<T, FeaturedCategoryUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more FeaturedCategories and returns the data updated in the database.
   * @param {FeaturedCategoryUpdateManyAndReturnArgs} args - Arguments to update many FeaturedCategories.
   * @example
   * // Update many FeaturedCategories
   * const featuredCategory = await prisma.featuredCategory.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more FeaturedCategories and only return the `id`
   * const featuredCategoryWithIdOnly = await prisma.featuredCategory.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends FeaturedCategoryUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, FeaturedCategoryUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FeaturedCategoryPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one FeaturedCategory.
   * @param {FeaturedCategoryUpsertArgs} args - Arguments to update or create a FeaturedCategory.
   * @example
   * // Update or create a FeaturedCategory
   * const featuredCategory = await prisma.featuredCategory.upsert({
   *   create: {
   *     // ... data to create a FeaturedCategory
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the FeaturedCategory we want to update
   *   }
   * })
   */
  upsert<T extends FeaturedCategoryUpsertArgs>(args: Prisma.SelectSubset<T, FeaturedCategoryUpsertArgs<ExtArgs>>): Prisma.Prisma__FeaturedCategoryClient<runtime.Types.Result.GetResult<Prisma.$FeaturedCategoryPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of FeaturedCategories.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FeaturedCategoryCountArgs} args - Arguments to filter FeaturedCategories to count.
   * @example
   * // Count the number of FeaturedCategories
   * const count = await prisma.featuredCategory.count({
   *   where: {
   *     // ... the filter for the FeaturedCategories we want to count
   *   }
   * })
  **/
  count<T extends FeaturedCategoryCountArgs>(
    args?: Prisma.Subset<T, FeaturedCategoryCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], FeaturedCategoryCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a FeaturedCategory.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FeaturedCategoryAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends FeaturedCategoryAggregateArgs>(args: Prisma.Subset<T, FeaturedCategoryAggregateArgs>): Prisma.PrismaPromise<GetFeaturedCategoryAggregateType<T>>

  /**
   * Group by FeaturedCategory.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FeaturedCategoryGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends FeaturedCategoryGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: FeaturedCategoryGroupByArgs['orderBy'] }
      : { orderBy?: FeaturedCategoryGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, FeaturedCategoryGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetFeaturedCategoryGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the FeaturedCategory model
 */
readonly fields: FeaturedCategoryFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for FeaturedCategory.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__FeaturedCategoryClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  category<T extends Prisma.ProductCategoryDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProductCategoryDefaultArgs<ExtArgs>>): Prisma.Prisma__ProductCategoryClient<runtime.Types.Result.GetResult<Prisma.$ProductCategoryPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the FeaturedCategory model
 */
export interface FeaturedCategoryFieldRefs {
  readonly id: Prisma.FieldRef<"FeaturedCategory", 'String'>
  readonly category_id: Prisma.FieldRef<"FeaturedCategory", 'String'>
  readonly order: Prisma.FieldRef<"FeaturedCategory", 'Int'>
  readonly is_active: Prisma.FieldRef<"FeaturedCategory", 'Boolean'>
  readonly created_at: Prisma.FieldRef<"FeaturedCategory", 'DateTime'>
  readonly updated_at: Prisma.FieldRef<"FeaturedCategory", 'DateTime'>
}
    

// Custom InputTypes
/**
 * FeaturedCategory findUnique
 */
export type FeaturedCategoryFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FeaturedCategory
   */
  select?: Prisma.FeaturedCategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the FeaturedCategory
   */
  omit?: Prisma.FeaturedCategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FeaturedCategoryInclude<ExtArgs> | null
  /**
   * Filter, which FeaturedCategory to fetch.
   */
  where: Prisma.FeaturedCategoryWhereUniqueInput
}

/**
 * FeaturedCategory findUniqueOrThrow
 */
export type FeaturedCategoryFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FeaturedCategory
   */
  select?: Prisma.FeaturedCategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the FeaturedCategory
   */
  omit?: Prisma.FeaturedCategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FeaturedCategoryInclude<ExtArgs> | null
  /**
   * Filter, which FeaturedCategory to fetch.
   */
  where: Prisma.FeaturedCategoryWhereUniqueInput
}

/**
 * FeaturedCategory findFirst
 */
export type FeaturedCategoryFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FeaturedCategory
   */
  select?: Prisma.FeaturedCategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the FeaturedCategory
   */
  omit?: Prisma.FeaturedCategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FeaturedCategoryInclude<ExtArgs> | null
  /**
   * Filter, which FeaturedCategory to fetch.
   */
  where?: Prisma.FeaturedCategoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FeaturedCategories to fetch.
   */
  orderBy?: Prisma.FeaturedCategoryOrderByWithRelationInput | Prisma.FeaturedCategoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for FeaturedCategories.
   */
  cursor?: Prisma.FeaturedCategoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FeaturedCategories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FeaturedCategories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FeaturedCategories.
   */
  distinct?: Prisma.FeaturedCategoryScalarFieldEnum | Prisma.FeaturedCategoryScalarFieldEnum[]
}

/**
 * FeaturedCategory findFirstOrThrow
 */
export type FeaturedCategoryFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FeaturedCategory
   */
  select?: Prisma.FeaturedCategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the FeaturedCategory
   */
  omit?: Prisma.FeaturedCategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FeaturedCategoryInclude<ExtArgs> | null
  /**
   * Filter, which FeaturedCategory to fetch.
   */
  where?: Prisma.FeaturedCategoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FeaturedCategories to fetch.
   */
  orderBy?: Prisma.FeaturedCategoryOrderByWithRelationInput | Prisma.FeaturedCategoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for FeaturedCategories.
   */
  cursor?: Prisma.FeaturedCategoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FeaturedCategories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FeaturedCategories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FeaturedCategories.
   */
  distinct?: Prisma.FeaturedCategoryScalarFieldEnum | Prisma.FeaturedCategoryScalarFieldEnum[]
}

/**
 * FeaturedCategory findMany
 */
export type FeaturedCategoryFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FeaturedCategory
   */
  select?: Prisma.FeaturedCategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the FeaturedCategory
   */
  omit?: Prisma.FeaturedCategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FeaturedCategoryInclude<ExtArgs> | null
  /**
   * Filter, which FeaturedCategories to fetch.
   */
  where?: Prisma.FeaturedCategoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FeaturedCategories to fetch.
   */
  orderBy?: Prisma.FeaturedCategoryOrderByWithRelationInput | Prisma.FeaturedCategoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing FeaturedCategories.
   */
  cursor?: Prisma.FeaturedCategoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FeaturedCategories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FeaturedCategories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FeaturedCategories.
   */
  distinct?: Prisma.FeaturedCategoryScalarFieldEnum | Prisma.FeaturedCategoryScalarFieldEnum[]
}

/**
 * FeaturedCategory create
 */
export type FeaturedCategoryCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FeaturedCategory
   */
  select?: Prisma.FeaturedCategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the FeaturedCategory
   */
  omit?: Prisma.FeaturedCategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FeaturedCategoryInclude<ExtArgs> | null
  /**
   * The data needed to create a FeaturedCategory.
   */
  data: Prisma.XOR<Prisma.FeaturedCategoryCreateInput, Prisma.FeaturedCategoryUncheckedCreateInput>
}

/**
 * FeaturedCategory createMany
 */
export type FeaturedCategoryCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many FeaturedCategories.
   */
  data: Prisma.FeaturedCategoryCreateManyInput | Prisma.FeaturedCategoryCreateManyInput[]
}

/**
 * FeaturedCategory createManyAndReturn
 */
export type FeaturedCategoryCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FeaturedCategory
   */
  select?: Prisma.FeaturedCategorySelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the FeaturedCategory
   */
  omit?: Prisma.FeaturedCategoryOmit<ExtArgs> | null
  /**
   * The data used to create many FeaturedCategories.
   */
  data: Prisma.FeaturedCategoryCreateManyInput | Prisma.FeaturedCategoryCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FeaturedCategoryIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * FeaturedCategory update
 */
export type FeaturedCategoryUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FeaturedCategory
   */
  select?: Prisma.FeaturedCategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the FeaturedCategory
   */
  omit?: Prisma.FeaturedCategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FeaturedCategoryInclude<ExtArgs> | null
  /**
   * The data needed to update a FeaturedCategory.
   */
  data: Prisma.XOR<Prisma.FeaturedCategoryUpdateInput, Prisma.FeaturedCategoryUncheckedUpdateInput>
  /**
   * Choose, which FeaturedCategory to update.
   */
  where: Prisma.FeaturedCategoryWhereUniqueInput
}

/**
 * FeaturedCategory updateMany
 */
export type FeaturedCategoryUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update FeaturedCategories.
   */
  data: Prisma.XOR<Prisma.FeaturedCategoryUpdateManyMutationInput, Prisma.FeaturedCategoryUncheckedUpdateManyInput>
  /**
   * Filter which FeaturedCategories to update
   */
  where?: Prisma.FeaturedCategoryWhereInput
  /**
   * Limit how many FeaturedCategories to update.
   */
  limit?: number
}

/**
 * FeaturedCategory updateManyAndReturn
 */
export type FeaturedCategoryUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FeaturedCategory
   */
  select?: Prisma.FeaturedCategorySelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the FeaturedCategory
   */
  omit?: Prisma.FeaturedCategoryOmit<ExtArgs> | null
  /**
   * The data used to update FeaturedCategories.
   */
  data: Prisma.XOR<Prisma.FeaturedCategoryUpdateManyMutationInput, Prisma.FeaturedCategoryUncheckedUpdateManyInput>
  /**
   * Filter which FeaturedCategories to update
   */
  where?: Prisma.FeaturedCategoryWhereInput
  /**
   * Limit how many FeaturedCategories to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FeaturedCategoryIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * FeaturedCategory upsert
 */
export type FeaturedCategoryUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FeaturedCategory
   */
  select?: Prisma.FeaturedCategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the FeaturedCategory
   */
  omit?: Prisma.FeaturedCategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FeaturedCategoryInclude<ExtArgs> | null
  /**
   * The filter to search for the FeaturedCategory to update in case it exists.
   */
  where: Prisma.FeaturedCategoryWhereUniqueInput
  /**
   * In case the FeaturedCategory found by the `where` argument doesn't exist, create a new FeaturedCategory with this data.
   */
  create: Prisma.XOR<Prisma.FeaturedCategoryCreateInput, Prisma.FeaturedCategoryUncheckedCreateInput>
  /**
   * In case the FeaturedCategory was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.FeaturedCategoryUpdateInput, Prisma.FeaturedCategoryUncheckedUpdateInput>
}

/**
 * FeaturedCategory delete
 */
export type FeaturedCategoryDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FeaturedCategory
   */
  select?: Prisma.FeaturedCategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the FeaturedCategory
   */
  omit?: Prisma.FeaturedCategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FeaturedCategoryInclude<ExtArgs> | null
  /**
   * Filter which FeaturedCategory to delete.
   */
  where: Prisma.FeaturedCategoryWhereUniqueInput
}

/**
 * FeaturedCategory deleteMany
 */
export type FeaturedCategoryDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which FeaturedCategories to delete
   */
  where?: Prisma.FeaturedCategoryWhereInput
  /**
   * Limit how many FeaturedCategories to delete.
   */
  limit?: number
}

/**
 * FeaturedCategory without action
 */
export type FeaturedCategoryDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FeaturedCategory
   */
  select?: Prisma.FeaturedCategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the FeaturedCategory
   */
  omit?: Prisma.FeaturedCategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FeaturedCategoryInclude<ExtArgs> | null
}
