
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `FlashSale` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model FlashSale
 * 
 */
export type FlashSaleModel = runtime.Types.Result.DefaultSelection<Prisma.$FlashSalePayload>

export type AggregateFlashSale = {
  _count: FlashSaleCountAggregateOutputType | null
  _min: FlashSaleMinAggregateOutputType | null
  _max: FlashSaleMaxAggregateOutputType | null
}

export type FlashSaleMinAggregateOutputType = {
  id: string | null
  name: string | null
  start_time: Date | null
  end_time: Date | null
  created_at: Date | null
  updated_at: Date | null
  time_slot_id: string | null
}

export type FlashSaleMaxAggregateOutputType = {
  id: string | null
  name: string | null
  start_time: Date | null
  end_time: Date | null
  created_at: Date | null
  updated_at: Date | null
  time_slot_id: string | null
}

export type FlashSaleCountAggregateOutputType = {
  id: number
  name: number
  start_time: number
  end_time: number
  created_at: number
  updated_at: number
  time_slot_id: number
  _all: number
}


export type FlashSaleMinAggregateInputType = {
  id?: true
  name?: true
  start_time?: true
  end_time?: true
  created_at?: true
  updated_at?: true
  time_slot_id?: true
}

export type FlashSaleMaxAggregateInputType = {
  id?: true
  name?: true
  start_time?: true
  end_time?: true
  created_at?: true
  updated_at?: true
  time_slot_id?: true
}

export type FlashSaleCountAggregateInputType = {
  id?: true
  name?: true
  start_time?: true
  end_time?: true
  created_at?: true
  updated_at?: true
  time_slot_id?: true
  _all?: true
}

export type FlashSaleAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which FlashSale to aggregate.
   */
  where?: Prisma.FlashSaleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FlashSales to fetch.
   */
  orderBy?: Prisma.FlashSaleOrderByWithRelationInput | Prisma.FlashSaleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.FlashSaleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FlashSales from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FlashSales.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned FlashSales
  **/
  _count?: true | FlashSaleCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: FlashSaleMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: FlashSaleMaxAggregateInputType
}

export type GetFlashSaleAggregateType<T extends FlashSaleAggregateArgs> = {
      [P in keyof T & keyof AggregateFlashSale]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateFlashSale[P]>
    : Prisma.GetScalarType<T[P], AggregateFlashSale[P]>
}




export type FlashSaleGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.FlashSaleWhereInput
  orderBy?: Prisma.FlashSaleOrderByWithAggregationInput | Prisma.FlashSaleOrderByWithAggregationInput[]
  by: Prisma.FlashSaleScalarFieldEnum[] | Prisma.FlashSaleScalarFieldEnum
  having?: Prisma.FlashSaleScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: FlashSaleCountAggregateInputType | true
  _min?: FlashSaleMinAggregateInputType
  _max?: FlashSaleMaxAggregateInputType
}

export type FlashSaleGroupByOutputType = {
  id: string
  name: string
  start_time: Date
  end_time: Date
  created_at: Date
  updated_at: Date
  time_slot_id: string | null
  _count: FlashSaleCountAggregateOutputType | null
  _min: FlashSaleMinAggregateOutputType | null
  _max: FlashSaleMaxAggregateOutputType | null
}

export type GetFlashSaleGroupByPayload<T extends FlashSaleGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<FlashSaleGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof FlashSaleGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], FlashSaleGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], FlashSaleGroupByOutputType[P]>
      }
    >
  >



export type FlashSaleWhereInput = {
  AND?: Prisma.FlashSaleWhereInput | Prisma.FlashSaleWhereInput[]
  OR?: Prisma.FlashSaleWhereInput[]
  NOT?: Prisma.FlashSaleWhereInput | Prisma.FlashSaleWhereInput[]
  id?: Prisma.StringFilter<"FlashSale"> | string
  name?: Prisma.StringFilter<"FlashSale"> | string
  start_time?: Prisma.DateTimeFilter<"FlashSale"> | Date | string
  end_time?: Prisma.DateTimeFilter<"FlashSale"> | Date | string
  created_at?: Prisma.DateTimeFilter<"FlashSale"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"FlashSale"> | Date | string
  time_slot_id?: Prisma.StringNullableFilter<"FlashSale"> | string | null
  time_slot?: Prisma.XOR<Prisma.FlashSaleTimeSlotNullableScalarRelationFilter, Prisma.FlashSaleTimeSlotWhereInput> | null
  products?: Prisma.FlashSaleProductListRelationFilter
}

export type FlashSaleOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  start_time?: Prisma.SortOrder
  end_time?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  time_slot_id?: Prisma.SortOrderInput | Prisma.SortOrder
  time_slot?: Prisma.FlashSaleTimeSlotOrderByWithRelationInput
  products?: Prisma.FlashSaleProductOrderByRelationAggregateInput
}

export type FlashSaleWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.FlashSaleWhereInput | Prisma.FlashSaleWhereInput[]
  OR?: Prisma.FlashSaleWhereInput[]
  NOT?: Prisma.FlashSaleWhereInput | Prisma.FlashSaleWhereInput[]
  name?: Prisma.StringFilter<"FlashSale"> | string
  start_time?: Prisma.DateTimeFilter<"FlashSale"> | Date | string
  end_time?: Prisma.DateTimeFilter<"FlashSale"> | Date | string
  created_at?: Prisma.DateTimeFilter<"FlashSale"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"FlashSale"> | Date | string
  time_slot_id?: Prisma.StringNullableFilter<"FlashSale"> | string | null
  time_slot?: Prisma.XOR<Prisma.FlashSaleTimeSlotNullableScalarRelationFilter, Prisma.FlashSaleTimeSlotWhereInput> | null
  products?: Prisma.FlashSaleProductListRelationFilter
}, "id">

export type FlashSaleOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  start_time?: Prisma.SortOrder
  end_time?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  time_slot_id?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.FlashSaleCountOrderByAggregateInput
  _max?: Prisma.FlashSaleMaxOrderByAggregateInput
  _min?: Prisma.FlashSaleMinOrderByAggregateInput
}

export type FlashSaleScalarWhereWithAggregatesInput = {
  AND?: Prisma.FlashSaleScalarWhereWithAggregatesInput | Prisma.FlashSaleScalarWhereWithAggregatesInput[]
  OR?: Prisma.FlashSaleScalarWhereWithAggregatesInput[]
  NOT?: Prisma.FlashSaleScalarWhereWithAggregatesInput | Prisma.FlashSaleScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"FlashSale"> | string
  name?: Prisma.StringWithAggregatesFilter<"FlashSale"> | string
  start_time?: Prisma.DateTimeWithAggregatesFilter<"FlashSale"> | Date | string
  end_time?: Prisma.DateTimeWithAggregatesFilter<"FlashSale"> | Date | string
  created_at?: Prisma.DateTimeWithAggregatesFilter<"FlashSale"> | Date | string
  updated_at?: Prisma.DateTimeWithAggregatesFilter<"FlashSale"> | Date | string
  time_slot_id?: Prisma.StringNullableWithAggregatesFilter<"FlashSale"> | string | null
}

export type FlashSaleCreateInput = {
  id?: string
  name: string
  start_time: Date | string
  end_time: Date | string
  created_at?: Date | string
  updated_at?: Date | string
  time_slot?: Prisma.FlashSaleTimeSlotCreateNestedOneWithoutFlash_salesInput
  products?: Prisma.FlashSaleProductCreateNestedManyWithoutFlash_saleInput
}

export type FlashSaleUncheckedCreateInput = {
  id?: string
  name: string
  start_time: Date | string
  end_time: Date | string
  created_at?: Date | string
  updated_at?: Date | string
  time_slot_id?: string | null
  products?: Prisma.FlashSaleProductUncheckedCreateNestedManyWithoutFlash_saleInput
}

export type FlashSaleUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  start_time?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  end_time?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  time_slot?: Prisma.FlashSaleTimeSlotUpdateOneWithoutFlash_salesNestedInput
  products?: Prisma.FlashSaleProductUpdateManyWithoutFlash_saleNestedInput
}

export type FlashSaleUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  start_time?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  end_time?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  time_slot_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  products?: Prisma.FlashSaleProductUncheckedUpdateManyWithoutFlash_saleNestedInput
}

export type FlashSaleCreateManyInput = {
  id?: string
  name: string
  start_time: Date | string
  end_time: Date | string
  created_at?: Date | string
  updated_at?: Date | string
  time_slot_id?: string | null
}

export type FlashSaleUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  start_time?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  end_time?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FlashSaleUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  start_time?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  end_time?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  time_slot_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type FlashSaleListRelationFilter = {
  every?: Prisma.FlashSaleWhereInput
  some?: Prisma.FlashSaleWhereInput
  none?: Prisma.FlashSaleWhereInput
}

export type FlashSaleOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type FlashSaleCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  start_time?: Prisma.SortOrder
  end_time?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  time_slot_id?: Prisma.SortOrder
}

export type FlashSaleMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  start_time?: Prisma.SortOrder
  end_time?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  time_slot_id?: Prisma.SortOrder
}

export type FlashSaleMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  start_time?: Prisma.SortOrder
  end_time?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  time_slot_id?: Prisma.SortOrder
}

export type FlashSaleScalarRelationFilter = {
  is?: Prisma.FlashSaleWhereInput
  isNot?: Prisma.FlashSaleWhereInput
}

export type FlashSaleCreateNestedManyWithoutTime_slotInput = {
  create?: Prisma.XOR<Prisma.FlashSaleCreateWithoutTime_slotInput, Prisma.FlashSaleUncheckedCreateWithoutTime_slotInput> | Prisma.FlashSaleCreateWithoutTime_slotInput[] | Prisma.FlashSaleUncheckedCreateWithoutTime_slotInput[]
  connectOrCreate?: Prisma.FlashSaleCreateOrConnectWithoutTime_slotInput | Prisma.FlashSaleCreateOrConnectWithoutTime_slotInput[]
  createMany?: Prisma.FlashSaleCreateManyTime_slotInputEnvelope
  connect?: Prisma.FlashSaleWhereUniqueInput | Prisma.FlashSaleWhereUniqueInput[]
}

export type FlashSaleUncheckedCreateNestedManyWithoutTime_slotInput = {
  create?: Prisma.XOR<Prisma.FlashSaleCreateWithoutTime_slotInput, Prisma.FlashSaleUncheckedCreateWithoutTime_slotInput> | Prisma.FlashSaleCreateWithoutTime_slotInput[] | Prisma.FlashSaleUncheckedCreateWithoutTime_slotInput[]
  connectOrCreate?: Prisma.FlashSaleCreateOrConnectWithoutTime_slotInput | Prisma.FlashSaleCreateOrConnectWithoutTime_slotInput[]
  createMany?: Prisma.FlashSaleCreateManyTime_slotInputEnvelope
  connect?: Prisma.FlashSaleWhereUniqueInput | Prisma.FlashSaleWhereUniqueInput[]
}

export type FlashSaleUpdateManyWithoutTime_slotNestedInput = {
  create?: Prisma.XOR<Prisma.FlashSaleCreateWithoutTime_slotInput, Prisma.FlashSaleUncheckedCreateWithoutTime_slotInput> | Prisma.FlashSaleCreateWithoutTime_slotInput[] | Prisma.FlashSaleUncheckedCreateWithoutTime_slotInput[]
  connectOrCreate?: Prisma.FlashSaleCreateOrConnectWithoutTime_slotInput | Prisma.FlashSaleCreateOrConnectWithoutTime_slotInput[]
  upsert?: Prisma.FlashSaleUpsertWithWhereUniqueWithoutTime_slotInput | Prisma.FlashSaleUpsertWithWhereUniqueWithoutTime_slotInput[]
  createMany?: Prisma.FlashSaleCreateManyTime_slotInputEnvelope
  set?: Prisma.FlashSaleWhereUniqueInput | Prisma.FlashSaleWhereUniqueInput[]
  disconnect?: Prisma.FlashSaleWhereUniqueInput | Prisma.FlashSaleWhereUniqueInput[]
  delete?: Prisma.FlashSaleWhereUniqueInput | Prisma.FlashSaleWhereUniqueInput[]
  connect?: Prisma.FlashSaleWhereUniqueInput | Prisma.FlashSaleWhereUniqueInput[]
  update?: Prisma.FlashSaleUpdateWithWhereUniqueWithoutTime_slotInput | Prisma.FlashSaleUpdateWithWhereUniqueWithoutTime_slotInput[]
  updateMany?: Prisma.FlashSaleUpdateManyWithWhereWithoutTime_slotInput | Prisma.FlashSaleUpdateManyWithWhereWithoutTime_slotInput[]
  deleteMany?: Prisma.FlashSaleScalarWhereInput | Prisma.FlashSaleScalarWhereInput[]
}

export type FlashSaleUncheckedUpdateManyWithoutTime_slotNestedInput = {
  create?: Prisma.XOR<Prisma.FlashSaleCreateWithoutTime_slotInput, Prisma.FlashSaleUncheckedCreateWithoutTime_slotInput> | Prisma.FlashSaleCreateWithoutTime_slotInput[] | Prisma.FlashSaleUncheckedCreateWithoutTime_slotInput[]
  connectOrCreate?: Prisma.FlashSaleCreateOrConnectWithoutTime_slotInput | Prisma.FlashSaleCreateOrConnectWithoutTime_slotInput[]
  upsert?: Prisma.FlashSaleUpsertWithWhereUniqueWithoutTime_slotInput | Prisma.FlashSaleUpsertWithWhereUniqueWithoutTime_slotInput[]
  createMany?: Prisma.FlashSaleCreateManyTime_slotInputEnvelope
  set?: Prisma.FlashSaleWhereUniqueInput | Prisma.FlashSaleWhereUniqueInput[]
  disconnect?: Prisma.FlashSaleWhereUniqueInput | Prisma.FlashSaleWhereUniqueInput[]
  delete?: Prisma.FlashSaleWhereUniqueInput | Prisma.FlashSaleWhereUniqueInput[]
  connect?: Prisma.FlashSaleWhereUniqueInput | Prisma.FlashSaleWhereUniqueInput[]
  update?: Prisma.FlashSaleUpdateWithWhereUniqueWithoutTime_slotInput | Prisma.FlashSaleUpdateWithWhereUniqueWithoutTime_slotInput[]
  updateMany?: Prisma.FlashSaleUpdateManyWithWhereWithoutTime_slotInput | Prisma.FlashSaleUpdateManyWithWhereWithoutTime_slotInput[]
  deleteMany?: Prisma.FlashSaleScalarWhereInput | Prisma.FlashSaleScalarWhereInput[]
}

export type FlashSaleCreateNestedOneWithoutProductsInput = {
  create?: Prisma.XOR<Prisma.FlashSaleCreateWithoutProductsInput, Prisma.FlashSaleUncheckedCreateWithoutProductsInput>
  connectOrCreate?: Prisma.FlashSaleCreateOrConnectWithoutProductsInput
  connect?: Prisma.FlashSaleWhereUniqueInput
}

export type FlashSaleUpdateOneRequiredWithoutProductsNestedInput = {
  create?: Prisma.XOR<Prisma.FlashSaleCreateWithoutProductsInput, Prisma.FlashSaleUncheckedCreateWithoutProductsInput>
  connectOrCreate?: Prisma.FlashSaleCreateOrConnectWithoutProductsInput
  upsert?: Prisma.FlashSaleUpsertWithoutProductsInput
  connect?: Prisma.FlashSaleWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.FlashSaleUpdateToOneWithWhereWithoutProductsInput, Prisma.FlashSaleUpdateWithoutProductsInput>, Prisma.FlashSaleUncheckedUpdateWithoutProductsInput>
}

export type FlashSaleCreateWithoutTime_slotInput = {
  id?: string
  name: string
  start_time: Date | string
  end_time: Date | string
  created_at?: Date | string
  updated_at?: Date | string
  products?: Prisma.FlashSaleProductCreateNestedManyWithoutFlash_saleInput
}

export type FlashSaleUncheckedCreateWithoutTime_slotInput = {
  id?: string
  name: string
  start_time: Date | string
  end_time: Date | string
  created_at?: Date | string
  updated_at?: Date | string
  products?: Prisma.FlashSaleProductUncheckedCreateNestedManyWithoutFlash_saleInput
}

export type FlashSaleCreateOrConnectWithoutTime_slotInput = {
  where: Prisma.FlashSaleWhereUniqueInput
  create: Prisma.XOR<Prisma.FlashSaleCreateWithoutTime_slotInput, Prisma.FlashSaleUncheckedCreateWithoutTime_slotInput>
}

export type FlashSaleCreateManyTime_slotInputEnvelope = {
  data: Prisma.FlashSaleCreateManyTime_slotInput | Prisma.FlashSaleCreateManyTime_slotInput[]
  skipDuplicates?: boolean
}

export type FlashSaleUpsertWithWhereUniqueWithoutTime_slotInput = {
  where: Prisma.FlashSaleWhereUniqueInput
  update: Prisma.XOR<Prisma.FlashSaleUpdateWithoutTime_slotInput, Prisma.FlashSaleUncheckedUpdateWithoutTime_slotInput>
  create: Prisma.XOR<Prisma.FlashSaleCreateWithoutTime_slotInput, Prisma.FlashSaleUncheckedCreateWithoutTime_slotInput>
}

export type FlashSaleUpdateWithWhereUniqueWithoutTime_slotInput = {
  where: Prisma.FlashSaleWhereUniqueInput
  data: Prisma.XOR<Prisma.FlashSaleUpdateWithoutTime_slotInput, Prisma.FlashSaleUncheckedUpdateWithoutTime_slotInput>
}

export type FlashSaleUpdateManyWithWhereWithoutTime_slotInput = {
  where: Prisma.FlashSaleScalarWhereInput
  data: Prisma.XOR<Prisma.FlashSaleUpdateManyMutationInput, Prisma.FlashSaleUncheckedUpdateManyWithoutTime_slotInput>
}

export type FlashSaleScalarWhereInput = {
  AND?: Prisma.FlashSaleScalarWhereInput | Prisma.FlashSaleScalarWhereInput[]
  OR?: Prisma.FlashSaleScalarWhereInput[]
  NOT?: Prisma.FlashSaleScalarWhereInput | Prisma.FlashSaleScalarWhereInput[]
  id?: Prisma.StringFilter<"FlashSale"> | string
  name?: Prisma.StringFilter<"FlashSale"> | string
  start_time?: Prisma.DateTimeFilter<"FlashSale"> | Date | string
  end_time?: Prisma.DateTimeFilter<"FlashSale"> | Date | string
  created_at?: Prisma.DateTimeFilter<"FlashSale"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"FlashSale"> | Date | string
  time_slot_id?: Prisma.StringNullableFilter<"FlashSale"> | string | null
}

export type FlashSaleCreateWithoutProductsInput = {
  id?: string
  name: string
  start_time: Date | string
  end_time: Date | string
  created_at?: Date | string
  updated_at?: Date | string
  time_slot?: Prisma.FlashSaleTimeSlotCreateNestedOneWithoutFlash_salesInput
}

export type FlashSaleUncheckedCreateWithoutProductsInput = {
  id?: string
  name: string
  start_time: Date | string
  end_time: Date | string
  created_at?: Date | string
  updated_at?: Date | string
  time_slot_id?: string | null
}

export type FlashSaleCreateOrConnectWithoutProductsInput = {
  where: Prisma.FlashSaleWhereUniqueInput
  create: Prisma.XOR<Prisma.FlashSaleCreateWithoutProductsInput, Prisma.FlashSaleUncheckedCreateWithoutProductsInput>
}

export type FlashSaleUpsertWithoutProductsInput = {
  update: Prisma.XOR<Prisma.FlashSaleUpdateWithoutProductsInput, Prisma.FlashSaleUncheckedUpdateWithoutProductsInput>
  create: Prisma.XOR<Prisma.FlashSaleCreateWithoutProductsInput, Prisma.FlashSaleUncheckedCreateWithoutProductsInput>
  where?: Prisma.FlashSaleWhereInput
}

export type FlashSaleUpdateToOneWithWhereWithoutProductsInput = {
  where?: Prisma.FlashSaleWhereInput
  data: Prisma.XOR<Prisma.FlashSaleUpdateWithoutProductsInput, Prisma.FlashSaleUncheckedUpdateWithoutProductsInput>
}

export type FlashSaleUpdateWithoutProductsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  start_time?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  end_time?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  time_slot?: Prisma.FlashSaleTimeSlotUpdateOneWithoutFlash_salesNestedInput
}

export type FlashSaleUncheckedUpdateWithoutProductsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  start_time?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  end_time?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  time_slot_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type FlashSaleCreateManyTime_slotInput = {
  id?: string
  name: string
  start_time: Date | string
  end_time: Date | string
  created_at?: Date | string
  updated_at?: Date | string
}

export type FlashSaleUpdateWithoutTime_slotInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  start_time?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  end_time?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  products?: Prisma.FlashSaleProductUpdateManyWithoutFlash_saleNestedInput
}

export type FlashSaleUncheckedUpdateWithoutTime_slotInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  start_time?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  end_time?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  products?: Prisma.FlashSaleProductUncheckedUpdateManyWithoutFlash_saleNestedInput
}

export type FlashSaleUncheckedUpdateManyWithoutTime_slotInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  start_time?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  end_time?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type FlashSaleCountOutputType
 */

export type FlashSaleCountOutputType = {
  products: number
}

export type FlashSaleCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  products?: boolean | FlashSaleCountOutputTypeCountProductsArgs
}

/**
 * FlashSaleCountOutputType without action
 */
export type FlashSaleCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FlashSaleCountOutputType
   */
  select?: Prisma.FlashSaleCountOutputTypeSelect<ExtArgs> | null
}

/**
 * FlashSaleCountOutputType without action
 */
export type FlashSaleCountOutputTypeCountProductsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.FlashSaleProductWhereInput
}


export type FlashSaleSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  start_time?: boolean
  end_time?: boolean
  created_at?: boolean
  updated_at?: boolean
  time_slot_id?: boolean
  time_slot?: boolean | Prisma.FlashSale$time_slotArgs<ExtArgs>
  products?: boolean | Prisma.FlashSale$productsArgs<ExtArgs>
  _count?: boolean | Prisma.FlashSaleCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["flashSale"]>

export type FlashSaleSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  start_time?: boolean
  end_time?: boolean
  created_at?: boolean
  updated_at?: boolean
  time_slot_id?: boolean
  time_slot?: boolean | Prisma.FlashSale$time_slotArgs<ExtArgs>
}, ExtArgs["result"]["flashSale"]>

export type FlashSaleSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  start_time?: boolean
  end_time?: boolean
  created_at?: boolean
  updated_at?: boolean
  time_slot_id?: boolean
  time_slot?: boolean | Prisma.FlashSale$time_slotArgs<ExtArgs>
}, ExtArgs["result"]["flashSale"]>

export type FlashSaleSelectScalar = {
  id?: boolean
  name?: boolean
  start_time?: boolean
  end_time?: boolean
  created_at?: boolean
  updated_at?: boolean
  time_slot_id?: boolean
}

export type FlashSaleOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "start_time" | "end_time" | "created_at" | "updated_at" | "time_slot_id", ExtArgs["result"]["flashSale"]>
export type FlashSaleInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  time_slot?: boolean | Prisma.FlashSale$time_slotArgs<ExtArgs>
  products?: boolean | Prisma.FlashSale$productsArgs<ExtArgs>
  _count?: boolean | Prisma.FlashSaleCountOutputTypeDefaultArgs<ExtArgs>
}
export type FlashSaleIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  time_slot?: boolean | Prisma.FlashSale$time_slotArgs<ExtArgs>
}
export type FlashSaleIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  time_slot?: boolean | Prisma.FlashSale$time_slotArgs<ExtArgs>
}

export type $FlashSalePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "FlashSale"
  objects: {
    time_slot: Prisma.$FlashSaleTimeSlotPayload<ExtArgs> | null
    products: Prisma.$FlashSaleProductPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    start_time: Date
    end_time: Date
    created_at: Date
    updated_at: Date
    time_slot_id: string | null
  }, ExtArgs["result"]["flashSale"]>
  composites: {}
}

export type FlashSaleGetPayload<S extends boolean | null | undefined | FlashSaleDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$FlashSalePayload, S>

export type FlashSaleCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<FlashSaleFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: FlashSaleCountAggregateInputType | true
  }

export interface FlashSaleDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['FlashSale'], meta: { name: 'FlashSale' } }
  /**
   * Find zero or one FlashSale that matches the filter.
   * @param {FlashSaleFindUniqueArgs} args - Arguments to find a FlashSale
   * @example
   * // Get one FlashSale
   * const flashSale = await prisma.flashSale.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends FlashSaleFindUniqueArgs>(args: Prisma.SelectSubset<T, FlashSaleFindUniqueArgs<ExtArgs>>): Prisma.Prisma__FlashSaleClient<runtime.Types.Result.GetResult<Prisma.$FlashSalePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one FlashSale that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {FlashSaleFindUniqueOrThrowArgs} args - Arguments to find a FlashSale
   * @example
   * // Get one FlashSale
   * const flashSale = await prisma.flashSale.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends FlashSaleFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, FlashSaleFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__FlashSaleClient<runtime.Types.Result.GetResult<Prisma.$FlashSalePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first FlashSale that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FlashSaleFindFirstArgs} args - Arguments to find a FlashSale
   * @example
   * // Get one FlashSale
   * const flashSale = await prisma.flashSale.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends FlashSaleFindFirstArgs>(args?: Prisma.SelectSubset<T, FlashSaleFindFirstArgs<ExtArgs>>): Prisma.Prisma__FlashSaleClient<runtime.Types.Result.GetResult<Prisma.$FlashSalePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first FlashSale that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FlashSaleFindFirstOrThrowArgs} args - Arguments to find a FlashSale
   * @example
   * // Get one FlashSale
   * const flashSale = await prisma.flashSale.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends FlashSaleFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, FlashSaleFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__FlashSaleClient<runtime.Types.Result.GetResult<Prisma.$FlashSalePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more FlashSales that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FlashSaleFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all FlashSales
   * const flashSales = await prisma.flashSale.findMany()
   * 
   * // Get first 10 FlashSales
   * const flashSales = await prisma.flashSale.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const flashSaleWithIdOnly = await prisma.flashSale.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends FlashSaleFindManyArgs>(args?: Prisma.SelectSubset<T, FlashSaleFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FlashSalePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a FlashSale.
   * @param {FlashSaleCreateArgs} args - Arguments to create a FlashSale.
   * @example
   * // Create one FlashSale
   * const FlashSale = await prisma.flashSale.create({
   *   data: {
   *     // ... data to create a FlashSale
   *   }
   * })
   * 
   */
  create<T extends FlashSaleCreateArgs>(args: Prisma.SelectSubset<T, FlashSaleCreateArgs<ExtArgs>>): Prisma.Prisma__FlashSaleClient<runtime.Types.Result.GetResult<Prisma.$FlashSalePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many FlashSales.
   * @param {FlashSaleCreateManyArgs} args - Arguments to create many FlashSales.
   * @example
   * // Create many FlashSales
   * const flashSale = await prisma.flashSale.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends FlashSaleCreateManyArgs>(args?: Prisma.SelectSubset<T, FlashSaleCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many FlashSales and returns the data saved in the database.
   * @param {FlashSaleCreateManyAndReturnArgs} args - Arguments to create many FlashSales.
   * @example
   * // Create many FlashSales
   * const flashSale = await prisma.flashSale.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many FlashSales and only return the `id`
   * const flashSaleWithIdOnly = await prisma.flashSale.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends FlashSaleCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, FlashSaleCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FlashSalePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a FlashSale.
   * @param {FlashSaleDeleteArgs} args - Arguments to delete one FlashSale.
   * @example
   * // Delete one FlashSale
   * const FlashSale = await prisma.flashSale.delete({
   *   where: {
   *     // ... filter to delete one FlashSale
   *   }
   * })
   * 
   */
  delete<T extends FlashSaleDeleteArgs>(args: Prisma.SelectSubset<T, FlashSaleDeleteArgs<ExtArgs>>): Prisma.Prisma__FlashSaleClient<runtime.Types.Result.GetResult<Prisma.$FlashSalePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one FlashSale.
   * @param {FlashSaleUpdateArgs} args - Arguments to update one FlashSale.
   * @example
   * // Update one FlashSale
   * const flashSale = await prisma.flashSale.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends FlashSaleUpdateArgs>(args: Prisma.SelectSubset<T, FlashSaleUpdateArgs<ExtArgs>>): Prisma.Prisma__FlashSaleClient<runtime.Types.Result.GetResult<Prisma.$FlashSalePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more FlashSales.
   * @param {FlashSaleDeleteManyArgs} args - Arguments to filter FlashSales to delete.
   * @example
   * // Delete a few FlashSales
   * const { count } = await prisma.flashSale.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends FlashSaleDeleteManyArgs>(args?: Prisma.SelectSubset<T, FlashSaleDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more FlashSales.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FlashSaleUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many FlashSales
   * const flashSale = await prisma.flashSale.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends FlashSaleUpdateManyArgs>(args: Prisma.SelectSubset<T, FlashSaleUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more FlashSales and returns the data updated in the database.
   * @param {FlashSaleUpdateManyAndReturnArgs} args - Arguments to update many FlashSales.
   * @example
   * // Update many FlashSales
   * const flashSale = await prisma.flashSale.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more FlashSales and only return the `id`
   * const flashSaleWithIdOnly = await prisma.flashSale.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends FlashSaleUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, FlashSaleUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FlashSalePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one FlashSale.
   * @param {FlashSaleUpsertArgs} args - Arguments to update or create a FlashSale.
   * @example
   * // Update or create a FlashSale
   * const flashSale = await prisma.flashSale.upsert({
   *   create: {
   *     // ... data to create a FlashSale
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the FlashSale we want to update
   *   }
   * })
   */
  upsert<T extends FlashSaleUpsertArgs>(args: Prisma.SelectSubset<T, FlashSaleUpsertArgs<ExtArgs>>): Prisma.Prisma__FlashSaleClient<runtime.Types.Result.GetResult<Prisma.$FlashSalePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of FlashSales.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FlashSaleCountArgs} args - Arguments to filter FlashSales to count.
   * @example
   * // Count the number of FlashSales
   * const count = await prisma.flashSale.count({
   *   where: {
   *     // ... the filter for the FlashSales we want to count
   *   }
   * })
  **/
  count<T extends FlashSaleCountArgs>(
    args?: Prisma.Subset<T, FlashSaleCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], FlashSaleCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a FlashSale.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FlashSaleAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends FlashSaleAggregateArgs>(args: Prisma.Subset<T, FlashSaleAggregateArgs>): Prisma.PrismaPromise<GetFlashSaleAggregateType<T>>

  /**
   * Group by FlashSale.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FlashSaleGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends FlashSaleGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: FlashSaleGroupByArgs['orderBy'] }
      : { orderBy?: FlashSaleGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, FlashSaleGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetFlashSaleGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the FlashSale model
 */
readonly fields: FlashSaleFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for FlashSale.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__FlashSaleClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  time_slot<T extends Prisma.FlashSale$time_slotArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.FlashSale$time_slotArgs<ExtArgs>>): Prisma.Prisma__FlashSaleTimeSlotClient<runtime.Types.Result.GetResult<Prisma.$FlashSaleTimeSlotPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  products<T extends Prisma.FlashSale$productsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.FlashSale$productsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FlashSaleProductPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the FlashSale model
 */
export interface FlashSaleFieldRefs {
  readonly id: Prisma.FieldRef<"FlashSale", 'String'>
  readonly name: Prisma.FieldRef<"FlashSale", 'String'>
  readonly start_time: Prisma.FieldRef<"FlashSale", 'DateTime'>
  readonly end_time: Prisma.FieldRef<"FlashSale", 'DateTime'>
  readonly created_at: Prisma.FieldRef<"FlashSale", 'DateTime'>
  readonly updated_at: Prisma.FieldRef<"FlashSale", 'DateTime'>
  readonly time_slot_id: Prisma.FieldRef<"FlashSale", 'String'>
}
    

// Custom InputTypes
/**
 * FlashSale findUnique
 */
export type FlashSaleFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FlashSale
   */
  select?: Prisma.FlashSaleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FlashSale
   */
  omit?: Prisma.FlashSaleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FlashSaleInclude<ExtArgs> | null
  /**
   * Filter, which FlashSale to fetch.
   */
  where: Prisma.FlashSaleWhereUniqueInput
}

/**
 * FlashSale findUniqueOrThrow
 */
export type FlashSaleFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FlashSale
   */
  select?: Prisma.FlashSaleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FlashSale
   */
  omit?: Prisma.FlashSaleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FlashSaleInclude<ExtArgs> | null
  /**
   * Filter, which FlashSale to fetch.
   */
  where: Prisma.FlashSaleWhereUniqueInput
}

/**
 * FlashSale findFirst
 */
export type FlashSaleFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FlashSale
   */
  select?: Prisma.FlashSaleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FlashSale
   */
  omit?: Prisma.FlashSaleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FlashSaleInclude<ExtArgs> | null
  /**
   * Filter, which FlashSale to fetch.
   */
  where?: Prisma.FlashSaleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FlashSales to fetch.
   */
  orderBy?: Prisma.FlashSaleOrderByWithRelationInput | Prisma.FlashSaleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for FlashSales.
   */
  cursor?: Prisma.FlashSaleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FlashSales from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FlashSales.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FlashSales.
   */
  distinct?: Prisma.FlashSaleScalarFieldEnum | Prisma.FlashSaleScalarFieldEnum[]
}

/**
 * FlashSale findFirstOrThrow
 */
export type FlashSaleFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FlashSale
   */
  select?: Prisma.FlashSaleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FlashSale
   */
  omit?: Prisma.FlashSaleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FlashSaleInclude<ExtArgs> | null
  /**
   * Filter, which FlashSale to fetch.
   */
  where?: Prisma.FlashSaleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FlashSales to fetch.
   */
  orderBy?: Prisma.FlashSaleOrderByWithRelationInput | Prisma.FlashSaleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for FlashSales.
   */
  cursor?: Prisma.FlashSaleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FlashSales from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FlashSales.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FlashSales.
   */
  distinct?: Prisma.FlashSaleScalarFieldEnum | Prisma.FlashSaleScalarFieldEnum[]
}

/**
 * FlashSale findMany
 */
export type FlashSaleFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FlashSale
   */
  select?: Prisma.FlashSaleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FlashSale
   */
  omit?: Prisma.FlashSaleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FlashSaleInclude<ExtArgs> | null
  /**
   * Filter, which FlashSales to fetch.
   */
  where?: Prisma.FlashSaleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FlashSales to fetch.
   */
  orderBy?: Prisma.FlashSaleOrderByWithRelationInput | Prisma.FlashSaleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing FlashSales.
   */
  cursor?: Prisma.FlashSaleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FlashSales from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FlashSales.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FlashSales.
   */
  distinct?: Prisma.FlashSaleScalarFieldEnum | Prisma.FlashSaleScalarFieldEnum[]
}

/**
 * FlashSale create
 */
export type FlashSaleCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FlashSale
   */
  select?: Prisma.FlashSaleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FlashSale
   */
  omit?: Prisma.FlashSaleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FlashSaleInclude<ExtArgs> | null
  /**
   * The data needed to create a FlashSale.
   */
  data: Prisma.XOR<Prisma.FlashSaleCreateInput, Prisma.FlashSaleUncheckedCreateInput>
}

/**
 * FlashSale createMany
 */
export type FlashSaleCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many FlashSales.
   */
  data: Prisma.FlashSaleCreateManyInput | Prisma.FlashSaleCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * FlashSale createManyAndReturn
 */
export type FlashSaleCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FlashSale
   */
  select?: Prisma.FlashSaleSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the FlashSale
   */
  omit?: Prisma.FlashSaleOmit<ExtArgs> | null
  /**
   * The data used to create many FlashSales.
   */
  data: Prisma.FlashSaleCreateManyInput | Prisma.FlashSaleCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FlashSaleIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * FlashSale update
 */
export type FlashSaleUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FlashSale
   */
  select?: Prisma.FlashSaleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FlashSale
   */
  omit?: Prisma.FlashSaleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FlashSaleInclude<ExtArgs> | null
  /**
   * The data needed to update a FlashSale.
   */
  data: Prisma.XOR<Prisma.FlashSaleUpdateInput, Prisma.FlashSaleUncheckedUpdateInput>
  /**
   * Choose, which FlashSale to update.
   */
  where: Prisma.FlashSaleWhereUniqueInput
}

/**
 * FlashSale updateMany
 */
export type FlashSaleUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update FlashSales.
   */
  data: Prisma.XOR<Prisma.FlashSaleUpdateManyMutationInput, Prisma.FlashSaleUncheckedUpdateManyInput>
  /**
   * Filter which FlashSales to update
   */
  where?: Prisma.FlashSaleWhereInput
  /**
   * Limit how many FlashSales to update.
   */
  limit?: number
}

/**
 * FlashSale updateManyAndReturn
 */
export type FlashSaleUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FlashSale
   */
  select?: Prisma.FlashSaleSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the FlashSale
   */
  omit?: Prisma.FlashSaleOmit<ExtArgs> | null
  /**
   * The data used to update FlashSales.
   */
  data: Prisma.XOR<Prisma.FlashSaleUpdateManyMutationInput, Prisma.FlashSaleUncheckedUpdateManyInput>
  /**
   * Filter which FlashSales to update
   */
  where?: Prisma.FlashSaleWhereInput
  /**
   * Limit how many FlashSales to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FlashSaleIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * FlashSale upsert
 */
export type FlashSaleUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FlashSale
   */
  select?: Prisma.FlashSaleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FlashSale
   */
  omit?: Prisma.FlashSaleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FlashSaleInclude<ExtArgs> | null
  /**
   * The filter to search for the FlashSale to update in case it exists.
   */
  where: Prisma.FlashSaleWhereUniqueInput
  /**
   * In case the FlashSale found by the `where` argument doesn't exist, create a new FlashSale with this data.
   */
  create: Prisma.XOR<Prisma.FlashSaleCreateInput, Prisma.FlashSaleUncheckedCreateInput>
  /**
   * In case the FlashSale was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.FlashSaleUpdateInput, Prisma.FlashSaleUncheckedUpdateInput>
}

/**
 * FlashSale delete
 */
export type FlashSaleDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FlashSale
   */
  select?: Prisma.FlashSaleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FlashSale
   */
  omit?: Prisma.FlashSaleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FlashSaleInclude<ExtArgs> | null
  /**
   * Filter which FlashSale to delete.
   */
  where: Prisma.FlashSaleWhereUniqueInput
}

/**
 * FlashSale deleteMany
 */
export type FlashSaleDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which FlashSales to delete
   */
  where?: Prisma.FlashSaleWhereInput
  /**
   * Limit how many FlashSales to delete.
   */
  limit?: number
}

/**
 * FlashSale.time_slot
 */
export type FlashSale$time_slotArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FlashSaleTimeSlot
   */
  select?: Prisma.FlashSaleTimeSlotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FlashSaleTimeSlot
   */
  omit?: Prisma.FlashSaleTimeSlotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FlashSaleTimeSlotInclude<ExtArgs> | null
  where?: Prisma.FlashSaleTimeSlotWhereInput
}

/**
 * FlashSale.products
 */
export type FlashSale$productsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FlashSaleProduct
   */
  select?: Prisma.FlashSaleProductSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FlashSaleProduct
   */
  omit?: Prisma.FlashSaleProductOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FlashSaleProductInclude<ExtArgs> | null
  where?: Prisma.FlashSaleProductWhereInput
  orderBy?: Prisma.FlashSaleProductOrderByWithRelationInput | Prisma.FlashSaleProductOrderByWithRelationInput[]
  cursor?: Prisma.FlashSaleProductWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.FlashSaleProductScalarFieldEnum | Prisma.FlashSaleProductScalarFieldEnum[]
}

/**
 * FlashSale without action
 */
export type FlashSaleDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FlashSale
   */
  select?: Prisma.FlashSaleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FlashSale
   */
  omit?: Prisma.FlashSaleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FlashSaleInclude<ExtArgs> | null
}
