
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `HomepageSectionTranslation` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model HomepageSectionTranslation
 * 
 */
export type HomepageSectionTranslationModel = runtime.Types.Result.DefaultSelection<Prisma.$HomepageSectionTranslationPayload>

export type AggregateHomepageSectionTranslation = {
  _count: HomepageSectionTranslationCountAggregateOutputType | null
  _min: HomepageSectionTranslationMinAggregateOutputType | null
  _max: HomepageSectionTranslationMaxAggregateOutputType | null
}

export type HomepageSectionTranslationMinAggregateOutputType = {
  id: string | null
  homepage_section_id: string | null
  language_id: string | null
  title: string | null
}

export type HomepageSectionTranslationMaxAggregateOutputType = {
  id: string | null
  homepage_section_id: string | null
  language_id: string | null
  title: string | null
}

export type HomepageSectionTranslationCountAggregateOutputType = {
  id: number
  homepage_section_id: number
  language_id: number
  title: number
  _all: number
}


export type HomepageSectionTranslationMinAggregateInputType = {
  id?: true
  homepage_section_id?: true
  language_id?: true
  title?: true
}

export type HomepageSectionTranslationMaxAggregateInputType = {
  id?: true
  homepage_section_id?: true
  language_id?: true
  title?: true
}

export type HomepageSectionTranslationCountAggregateInputType = {
  id?: true
  homepage_section_id?: true
  language_id?: true
  title?: true
  _all?: true
}

export type HomepageSectionTranslationAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which HomepageSectionTranslation to aggregate.
   */
  where?: Prisma.HomepageSectionTranslationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of HomepageSectionTranslations to fetch.
   */
  orderBy?: Prisma.HomepageSectionTranslationOrderByWithRelationInput | Prisma.HomepageSectionTranslationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.HomepageSectionTranslationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` HomepageSectionTranslations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` HomepageSectionTranslations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned HomepageSectionTranslations
  **/
  _count?: true | HomepageSectionTranslationCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: HomepageSectionTranslationMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: HomepageSectionTranslationMaxAggregateInputType
}

export type GetHomepageSectionTranslationAggregateType<T extends HomepageSectionTranslationAggregateArgs> = {
      [P in keyof T & keyof AggregateHomepageSectionTranslation]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateHomepageSectionTranslation[P]>
    : Prisma.GetScalarType<T[P], AggregateHomepageSectionTranslation[P]>
}




export type HomepageSectionTranslationGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.HomepageSectionTranslationWhereInput
  orderBy?: Prisma.HomepageSectionTranslationOrderByWithAggregationInput | Prisma.HomepageSectionTranslationOrderByWithAggregationInput[]
  by: Prisma.HomepageSectionTranslationScalarFieldEnum[] | Prisma.HomepageSectionTranslationScalarFieldEnum
  having?: Prisma.HomepageSectionTranslationScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: HomepageSectionTranslationCountAggregateInputType | true
  _min?: HomepageSectionTranslationMinAggregateInputType
  _max?: HomepageSectionTranslationMaxAggregateInputType
}

export type HomepageSectionTranslationGroupByOutputType = {
  id: string
  homepage_section_id: string
  language_id: string
  title: string
  _count: HomepageSectionTranslationCountAggregateOutputType | null
  _min: HomepageSectionTranslationMinAggregateOutputType | null
  _max: HomepageSectionTranslationMaxAggregateOutputType | null
}

export type GetHomepageSectionTranslationGroupByPayload<T extends HomepageSectionTranslationGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<HomepageSectionTranslationGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof HomepageSectionTranslationGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], HomepageSectionTranslationGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], HomepageSectionTranslationGroupByOutputType[P]>
      }
    >
  >



export type HomepageSectionTranslationWhereInput = {
  AND?: Prisma.HomepageSectionTranslationWhereInput | Prisma.HomepageSectionTranslationWhereInput[]
  OR?: Prisma.HomepageSectionTranslationWhereInput[]
  NOT?: Prisma.HomepageSectionTranslationWhereInput | Prisma.HomepageSectionTranslationWhereInput[]
  id?: Prisma.StringFilter<"HomepageSectionTranslation"> | string
  homepage_section_id?: Prisma.StringFilter<"HomepageSectionTranslation"> | string
  language_id?: Prisma.StringFilter<"HomepageSectionTranslation"> | string
  title?: Prisma.StringFilter<"HomepageSectionTranslation"> | string
  homepage_section?: Prisma.XOR<Prisma.HomepageSectionScalarRelationFilter, Prisma.HomepageSectionWhereInput>
  language?: Prisma.XOR<Prisma.LanguageScalarRelationFilter, Prisma.LanguageWhereInput>
}

export type HomepageSectionTranslationOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  homepage_section_id?: Prisma.SortOrder
  language_id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  homepage_section?: Prisma.HomepageSectionOrderByWithRelationInput
  language?: Prisma.LanguageOrderByWithRelationInput
}

export type HomepageSectionTranslationWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  homepage_section_id_language_id?: Prisma.HomepageSectionTranslationHomepage_section_idLanguage_idCompoundUniqueInput
  AND?: Prisma.HomepageSectionTranslationWhereInput | Prisma.HomepageSectionTranslationWhereInput[]
  OR?: Prisma.HomepageSectionTranslationWhereInput[]
  NOT?: Prisma.HomepageSectionTranslationWhereInput | Prisma.HomepageSectionTranslationWhereInput[]
  homepage_section_id?: Prisma.StringFilter<"HomepageSectionTranslation"> | string
  language_id?: Prisma.StringFilter<"HomepageSectionTranslation"> | string
  title?: Prisma.StringFilter<"HomepageSectionTranslation"> | string
  homepage_section?: Prisma.XOR<Prisma.HomepageSectionScalarRelationFilter, Prisma.HomepageSectionWhereInput>
  language?: Prisma.XOR<Prisma.LanguageScalarRelationFilter, Prisma.LanguageWhereInput>
}, "id" | "homepage_section_id_language_id">

export type HomepageSectionTranslationOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  homepage_section_id?: Prisma.SortOrder
  language_id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  _count?: Prisma.HomepageSectionTranslationCountOrderByAggregateInput
  _max?: Prisma.HomepageSectionTranslationMaxOrderByAggregateInput
  _min?: Prisma.HomepageSectionTranslationMinOrderByAggregateInput
}

export type HomepageSectionTranslationScalarWhereWithAggregatesInput = {
  AND?: Prisma.HomepageSectionTranslationScalarWhereWithAggregatesInput | Prisma.HomepageSectionTranslationScalarWhereWithAggregatesInput[]
  OR?: Prisma.HomepageSectionTranslationScalarWhereWithAggregatesInput[]
  NOT?: Prisma.HomepageSectionTranslationScalarWhereWithAggregatesInput | Prisma.HomepageSectionTranslationScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"HomepageSectionTranslation"> | string
  homepage_section_id?: Prisma.StringWithAggregatesFilter<"HomepageSectionTranslation"> | string
  language_id?: Prisma.StringWithAggregatesFilter<"HomepageSectionTranslation"> | string
  title?: Prisma.StringWithAggregatesFilter<"HomepageSectionTranslation"> | string
}

export type HomepageSectionTranslationCreateInput = {
  id?: string
  title: string
  homepage_section: Prisma.HomepageSectionCreateNestedOneWithoutTranslationsInput
  language: Prisma.LanguageCreateNestedOneWithoutHomepage_section_translationsInput
}

export type HomepageSectionTranslationUncheckedCreateInput = {
  id?: string
  homepage_section_id: string
  language_id: string
  title: string
}

export type HomepageSectionTranslationUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  homepage_section?: Prisma.HomepageSectionUpdateOneRequiredWithoutTranslationsNestedInput
  language?: Prisma.LanguageUpdateOneRequiredWithoutHomepage_section_translationsNestedInput
}

export type HomepageSectionTranslationUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  homepage_section_id?: Prisma.StringFieldUpdateOperationsInput | string
  language_id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
}

export type HomepageSectionTranslationCreateManyInput = {
  id?: string
  homepage_section_id: string
  language_id: string
  title: string
}

export type HomepageSectionTranslationUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
}

export type HomepageSectionTranslationUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  homepage_section_id?: Prisma.StringFieldUpdateOperationsInput | string
  language_id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
}

export type HomepageSectionTranslationListRelationFilter = {
  every?: Prisma.HomepageSectionTranslationWhereInput
  some?: Prisma.HomepageSectionTranslationWhereInput
  none?: Prisma.HomepageSectionTranslationWhereInput
}

export type HomepageSectionTranslationOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type HomepageSectionTranslationHomepage_section_idLanguage_idCompoundUniqueInput = {
  homepage_section_id: string
  language_id: string
}

export type HomepageSectionTranslationCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  homepage_section_id?: Prisma.SortOrder
  language_id?: Prisma.SortOrder
  title?: Prisma.SortOrder
}

export type HomepageSectionTranslationMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  homepage_section_id?: Prisma.SortOrder
  language_id?: Prisma.SortOrder
  title?: Prisma.SortOrder
}

export type HomepageSectionTranslationMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  homepage_section_id?: Prisma.SortOrder
  language_id?: Prisma.SortOrder
  title?: Prisma.SortOrder
}

export type HomepageSectionTranslationCreateNestedManyWithoutHomepage_sectionInput = {
  create?: Prisma.XOR<Prisma.HomepageSectionTranslationCreateWithoutHomepage_sectionInput, Prisma.HomepageSectionTranslationUncheckedCreateWithoutHomepage_sectionInput> | Prisma.HomepageSectionTranslationCreateWithoutHomepage_sectionInput[] | Prisma.HomepageSectionTranslationUncheckedCreateWithoutHomepage_sectionInput[]
  connectOrCreate?: Prisma.HomepageSectionTranslationCreateOrConnectWithoutHomepage_sectionInput | Prisma.HomepageSectionTranslationCreateOrConnectWithoutHomepage_sectionInput[]
  createMany?: Prisma.HomepageSectionTranslationCreateManyHomepage_sectionInputEnvelope
  connect?: Prisma.HomepageSectionTranslationWhereUniqueInput | Prisma.HomepageSectionTranslationWhereUniqueInput[]
}

export type HomepageSectionTranslationUncheckedCreateNestedManyWithoutHomepage_sectionInput = {
  create?: Prisma.XOR<Prisma.HomepageSectionTranslationCreateWithoutHomepage_sectionInput, Prisma.HomepageSectionTranslationUncheckedCreateWithoutHomepage_sectionInput> | Prisma.HomepageSectionTranslationCreateWithoutHomepage_sectionInput[] | Prisma.HomepageSectionTranslationUncheckedCreateWithoutHomepage_sectionInput[]
  connectOrCreate?: Prisma.HomepageSectionTranslationCreateOrConnectWithoutHomepage_sectionInput | Prisma.HomepageSectionTranslationCreateOrConnectWithoutHomepage_sectionInput[]
  createMany?: Prisma.HomepageSectionTranslationCreateManyHomepage_sectionInputEnvelope
  connect?: Prisma.HomepageSectionTranslationWhereUniqueInput | Prisma.HomepageSectionTranslationWhereUniqueInput[]
}

export type HomepageSectionTranslationUpdateManyWithoutHomepage_sectionNestedInput = {
  create?: Prisma.XOR<Prisma.HomepageSectionTranslationCreateWithoutHomepage_sectionInput, Prisma.HomepageSectionTranslationUncheckedCreateWithoutHomepage_sectionInput> | Prisma.HomepageSectionTranslationCreateWithoutHomepage_sectionInput[] | Prisma.HomepageSectionTranslationUncheckedCreateWithoutHomepage_sectionInput[]
  connectOrCreate?: Prisma.HomepageSectionTranslationCreateOrConnectWithoutHomepage_sectionInput | Prisma.HomepageSectionTranslationCreateOrConnectWithoutHomepage_sectionInput[]
  upsert?: Prisma.HomepageSectionTranslationUpsertWithWhereUniqueWithoutHomepage_sectionInput | Prisma.HomepageSectionTranslationUpsertWithWhereUniqueWithoutHomepage_sectionInput[]
  createMany?: Prisma.HomepageSectionTranslationCreateManyHomepage_sectionInputEnvelope
  set?: Prisma.HomepageSectionTranslationWhereUniqueInput | Prisma.HomepageSectionTranslationWhereUniqueInput[]
  disconnect?: Prisma.HomepageSectionTranslationWhereUniqueInput | Prisma.HomepageSectionTranslationWhereUniqueInput[]
  delete?: Prisma.HomepageSectionTranslationWhereUniqueInput | Prisma.HomepageSectionTranslationWhereUniqueInput[]
  connect?: Prisma.HomepageSectionTranslationWhereUniqueInput | Prisma.HomepageSectionTranslationWhereUniqueInput[]
  update?: Prisma.HomepageSectionTranslationUpdateWithWhereUniqueWithoutHomepage_sectionInput | Prisma.HomepageSectionTranslationUpdateWithWhereUniqueWithoutHomepage_sectionInput[]
  updateMany?: Prisma.HomepageSectionTranslationUpdateManyWithWhereWithoutHomepage_sectionInput | Prisma.HomepageSectionTranslationUpdateManyWithWhereWithoutHomepage_sectionInput[]
  deleteMany?: Prisma.HomepageSectionTranslationScalarWhereInput | Prisma.HomepageSectionTranslationScalarWhereInput[]
}

export type HomepageSectionTranslationUncheckedUpdateManyWithoutHomepage_sectionNestedInput = {
  create?: Prisma.XOR<Prisma.HomepageSectionTranslationCreateWithoutHomepage_sectionInput, Prisma.HomepageSectionTranslationUncheckedCreateWithoutHomepage_sectionInput> | Prisma.HomepageSectionTranslationCreateWithoutHomepage_sectionInput[] | Prisma.HomepageSectionTranslationUncheckedCreateWithoutHomepage_sectionInput[]
  connectOrCreate?: Prisma.HomepageSectionTranslationCreateOrConnectWithoutHomepage_sectionInput | Prisma.HomepageSectionTranslationCreateOrConnectWithoutHomepage_sectionInput[]
  upsert?: Prisma.HomepageSectionTranslationUpsertWithWhereUniqueWithoutHomepage_sectionInput | Prisma.HomepageSectionTranslationUpsertWithWhereUniqueWithoutHomepage_sectionInput[]
  createMany?: Prisma.HomepageSectionTranslationCreateManyHomepage_sectionInputEnvelope
  set?: Prisma.HomepageSectionTranslationWhereUniqueInput | Prisma.HomepageSectionTranslationWhereUniqueInput[]
  disconnect?: Prisma.HomepageSectionTranslationWhereUniqueInput | Prisma.HomepageSectionTranslationWhereUniqueInput[]
  delete?: Prisma.HomepageSectionTranslationWhereUniqueInput | Prisma.HomepageSectionTranslationWhereUniqueInput[]
  connect?: Prisma.HomepageSectionTranslationWhereUniqueInput | Prisma.HomepageSectionTranslationWhereUniqueInput[]
  update?: Prisma.HomepageSectionTranslationUpdateWithWhereUniqueWithoutHomepage_sectionInput | Prisma.HomepageSectionTranslationUpdateWithWhereUniqueWithoutHomepage_sectionInput[]
  updateMany?: Prisma.HomepageSectionTranslationUpdateManyWithWhereWithoutHomepage_sectionInput | Prisma.HomepageSectionTranslationUpdateManyWithWhereWithoutHomepage_sectionInput[]
  deleteMany?: Prisma.HomepageSectionTranslationScalarWhereInput | Prisma.HomepageSectionTranslationScalarWhereInput[]
}

export type HomepageSectionTranslationCreateNestedManyWithoutLanguageInput = {
  create?: Prisma.XOR<Prisma.HomepageSectionTranslationCreateWithoutLanguageInput, Prisma.HomepageSectionTranslationUncheckedCreateWithoutLanguageInput> | Prisma.HomepageSectionTranslationCreateWithoutLanguageInput[] | Prisma.HomepageSectionTranslationUncheckedCreateWithoutLanguageInput[]
  connectOrCreate?: Prisma.HomepageSectionTranslationCreateOrConnectWithoutLanguageInput | Prisma.HomepageSectionTranslationCreateOrConnectWithoutLanguageInput[]
  createMany?: Prisma.HomepageSectionTranslationCreateManyLanguageInputEnvelope
  connect?: Prisma.HomepageSectionTranslationWhereUniqueInput | Prisma.HomepageSectionTranslationWhereUniqueInput[]
}

export type HomepageSectionTranslationUncheckedCreateNestedManyWithoutLanguageInput = {
  create?: Prisma.XOR<Prisma.HomepageSectionTranslationCreateWithoutLanguageInput, Prisma.HomepageSectionTranslationUncheckedCreateWithoutLanguageInput> | Prisma.HomepageSectionTranslationCreateWithoutLanguageInput[] | Prisma.HomepageSectionTranslationUncheckedCreateWithoutLanguageInput[]
  connectOrCreate?: Prisma.HomepageSectionTranslationCreateOrConnectWithoutLanguageInput | Prisma.HomepageSectionTranslationCreateOrConnectWithoutLanguageInput[]
  createMany?: Prisma.HomepageSectionTranslationCreateManyLanguageInputEnvelope
  connect?: Prisma.HomepageSectionTranslationWhereUniqueInput | Prisma.HomepageSectionTranslationWhereUniqueInput[]
}

export type HomepageSectionTranslationUpdateManyWithoutLanguageNestedInput = {
  create?: Prisma.XOR<Prisma.HomepageSectionTranslationCreateWithoutLanguageInput, Prisma.HomepageSectionTranslationUncheckedCreateWithoutLanguageInput> | Prisma.HomepageSectionTranslationCreateWithoutLanguageInput[] | Prisma.HomepageSectionTranslationUncheckedCreateWithoutLanguageInput[]
  connectOrCreate?: Prisma.HomepageSectionTranslationCreateOrConnectWithoutLanguageInput | Prisma.HomepageSectionTranslationCreateOrConnectWithoutLanguageInput[]
  upsert?: Prisma.HomepageSectionTranslationUpsertWithWhereUniqueWithoutLanguageInput | Prisma.HomepageSectionTranslationUpsertWithWhereUniqueWithoutLanguageInput[]
  createMany?: Prisma.HomepageSectionTranslationCreateManyLanguageInputEnvelope
  set?: Prisma.HomepageSectionTranslationWhereUniqueInput | Prisma.HomepageSectionTranslationWhereUniqueInput[]
  disconnect?: Prisma.HomepageSectionTranslationWhereUniqueInput | Prisma.HomepageSectionTranslationWhereUniqueInput[]
  delete?: Prisma.HomepageSectionTranslationWhereUniqueInput | Prisma.HomepageSectionTranslationWhereUniqueInput[]
  connect?: Prisma.HomepageSectionTranslationWhereUniqueInput | Prisma.HomepageSectionTranslationWhereUniqueInput[]
  update?: Prisma.HomepageSectionTranslationUpdateWithWhereUniqueWithoutLanguageInput | Prisma.HomepageSectionTranslationUpdateWithWhereUniqueWithoutLanguageInput[]
  updateMany?: Prisma.HomepageSectionTranslationUpdateManyWithWhereWithoutLanguageInput | Prisma.HomepageSectionTranslationUpdateManyWithWhereWithoutLanguageInput[]
  deleteMany?: Prisma.HomepageSectionTranslationScalarWhereInput | Prisma.HomepageSectionTranslationScalarWhereInput[]
}

export type HomepageSectionTranslationUncheckedUpdateManyWithoutLanguageNestedInput = {
  create?: Prisma.XOR<Prisma.HomepageSectionTranslationCreateWithoutLanguageInput, Prisma.HomepageSectionTranslationUncheckedCreateWithoutLanguageInput> | Prisma.HomepageSectionTranslationCreateWithoutLanguageInput[] | Prisma.HomepageSectionTranslationUncheckedCreateWithoutLanguageInput[]
  connectOrCreate?: Prisma.HomepageSectionTranslationCreateOrConnectWithoutLanguageInput | Prisma.HomepageSectionTranslationCreateOrConnectWithoutLanguageInput[]
  upsert?: Prisma.HomepageSectionTranslationUpsertWithWhereUniqueWithoutLanguageInput | Prisma.HomepageSectionTranslationUpsertWithWhereUniqueWithoutLanguageInput[]
  createMany?: Prisma.HomepageSectionTranslationCreateManyLanguageInputEnvelope
  set?: Prisma.HomepageSectionTranslationWhereUniqueInput | Prisma.HomepageSectionTranslationWhereUniqueInput[]
  disconnect?: Prisma.HomepageSectionTranslationWhereUniqueInput | Prisma.HomepageSectionTranslationWhereUniqueInput[]
  delete?: Prisma.HomepageSectionTranslationWhereUniqueInput | Prisma.HomepageSectionTranslationWhereUniqueInput[]
  connect?: Prisma.HomepageSectionTranslationWhereUniqueInput | Prisma.HomepageSectionTranslationWhereUniqueInput[]
  update?: Prisma.HomepageSectionTranslationUpdateWithWhereUniqueWithoutLanguageInput | Prisma.HomepageSectionTranslationUpdateWithWhereUniqueWithoutLanguageInput[]
  updateMany?: Prisma.HomepageSectionTranslationUpdateManyWithWhereWithoutLanguageInput | Prisma.HomepageSectionTranslationUpdateManyWithWhereWithoutLanguageInput[]
  deleteMany?: Prisma.HomepageSectionTranslationScalarWhereInput | Prisma.HomepageSectionTranslationScalarWhereInput[]
}

export type HomepageSectionTranslationCreateWithoutHomepage_sectionInput = {
  id?: string
  title: string
  language: Prisma.LanguageCreateNestedOneWithoutHomepage_section_translationsInput
}

export type HomepageSectionTranslationUncheckedCreateWithoutHomepage_sectionInput = {
  id?: string
  language_id: string
  title: string
}

export type HomepageSectionTranslationCreateOrConnectWithoutHomepage_sectionInput = {
  where: Prisma.HomepageSectionTranslationWhereUniqueInput
  create: Prisma.XOR<Prisma.HomepageSectionTranslationCreateWithoutHomepage_sectionInput, Prisma.HomepageSectionTranslationUncheckedCreateWithoutHomepage_sectionInput>
}

export type HomepageSectionTranslationCreateManyHomepage_sectionInputEnvelope = {
  data: Prisma.HomepageSectionTranslationCreateManyHomepage_sectionInput | Prisma.HomepageSectionTranslationCreateManyHomepage_sectionInput[]
}

export type HomepageSectionTranslationUpsertWithWhereUniqueWithoutHomepage_sectionInput = {
  where: Prisma.HomepageSectionTranslationWhereUniqueInput
  update: Prisma.XOR<Prisma.HomepageSectionTranslationUpdateWithoutHomepage_sectionInput, Prisma.HomepageSectionTranslationUncheckedUpdateWithoutHomepage_sectionInput>
  create: Prisma.XOR<Prisma.HomepageSectionTranslationCreateWithoutHomepage_sectionInput, Prisma.HomepageSectionTranslationUncheckedCreateWithoutHomepage_sectionInput>
}

export type HomepageSectionTranslationUpdateWithWhereUniqueWithoutHomepage_sectionInput = {
  where: Prisma.HomepageSectionTranslationWhereUniqueInput
  data: Prisma.XOR<Prisma.HomepageSectionTranslationUpdateWithoutHomepage_sectionInput, Prisma.HomepageSectionTranslationUncheckedUpdateWithoutHomepage_sectionInput>
}

export type HomepageSectionTranslationUpdateManyWithWhereWithoutHomepage_sectionInput = {
  where: Prisma.HomepageSectionTranslationScalarWhereInput
  data: Prisma.XOR<Prisma.HomepageSectionTranslationUpdateManyMutationInput, Prisma.HomepageSectionTranslationUncheckedUpdateManyWithoutHomepage_sectionInput>
}

export type HomepageSectionTranslationScalarWhereInput = {
  AND?: Prisma.HomepageSectionTranslationScalarWhereInput | Prisma.HomepageSectionTranslationScalarWhereInput[]
  OR?: Prisma.HomepageSectionTranslationScalarWhereInput[]
  NOT?: Prisma.HomepageSectionTranslationScalarWhereInput | Prisma.HomepageSectionTranslationScalarWhereInput[]
  id?: Prisma.StringFilter<"HomepageSectionTranslation"> | string
  homepage_section_id?: Prisma.StringFilter<"HomepageSectionTranslation"> | string
  language_id?: Prisma.StringFilter<"HomepageSectionTranslation"> | string
  title?: Prisma.StringFilter<"HomepageSectionTranslation"> | string
}

export type HomepageSectionTranslationCreateWithoutLanguageInput = {
  id?: string
  title: string
  homepage_section: Prisma.HomepageSectionCreateNestedOneWithoutTranslationsInput
}

export type HomepageSectionTranslationUncheckedCreateWithoutLanguageInput = {
  id?: string
  homepage_section_id: string
  title: string
}

export type HomepageSectionTranslationCreateOrConnectWithoutLanguageInput = {
  where: Prisma.HomepageSectionTranslationWhereUniqueInput
  create: Prisma.XOR<Prisma.HomepageSectionTranslationCreateWithoutLanguageInput, Prisma.HomepageSectionTranslationUncheckedCreateWithoutLanguageInput>
}

export type HomepageSectionTranslationCreateManyLanguageInputEnvelope = {
  data: Prisma.HomepageSectionTranslationCreateManyLanguageInput | Prisma.HomepageSectionTranslationCreateManyLanguageInput[]
}

export type HomepageSectionTranslationUpsertWithWhereUniqueWithoutLanguageInput = {
  where: Prisma.HomepageSectionTranslationWhereUniqueInput
  update: Prisma.XOR<Prisma.HomepageSectionTranslationUpdateWithoutLanguageInput, Prisma.HomepageSectionTranslationUncheckedUpdateWithoutLanguageInput>
  create: Prisma.XOR<Prisma.HomepageSectionTranslationCreateWithoutLanguageInput, Prisma.HomepageSectionTranslationUncheckedCreateWithoutLanguageInput>
}

export type HomepageSectionTranslationUpdateWithWhereUniqueWithoutLanguageInput = {
  where: Prisma.HomepageSectionTranslationWhereUniqueInput
  data: Prisma.XOR<Prisma.HomepageSectionTranslationUpdateWithoutLanguageInput, Prisma.HomepageSectionTranslationUncheckedUpdateWithoutLanguageInput>
}

export type HomepageSectionTranslationUpdateManyWithWhereWithoutLanguageInput = {
  where: Prisma.HomepageSectionTranslationScalarWhereInput
  data: Prisma.XOR<Prisma.HomepageSectionTranslationUpdateManyMutationInput, Prisma.HomepageSectionTranslationUncheckedUpdateManyWithoutLanguageInput>
}

export type HomepageSectionTranslationCreateManyHomepage_sectionInput = {
  id?: string
  language_id: string
  title: string
}

export type HomepageSectionTranslationUpdateWithoutHomepage_sectionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  language?: Prisma.LanguageUpdateOneRequiredWithoutHomepage_section_translationsNestedInput
}

export type HomepageSectionTranslationUncheckedUpdateWithoutHomepage_sectionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  language_id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
}

export type HomepageSectionTranslationUncheckedUpdateManyWithoutHomepage_sectionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  language_id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
}

export type HomepageSectionTranslationCreateManyLanguageInput = {
  id?: string
  homepage_section_id: string
  title: string
}

export type HomepageSectionTranslationUpdateWithoutLanguageInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  homepage_section?: Prisma.HomepageSectionUpdateOneRequiredWithoutTranslationsNestedInput
}

export type HomepageSectionTranslationUncheckedUpdateWithoutLanguageInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  homepage_section_id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
}

export type HomepageSectionTranslationUncheckedUpdateManyWithoutLanguageInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  homepage_section_id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
}



export type HomepageSectionTranslationSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  homepage_section_id?: boolean
  language_id?: boolean
  title?: boolean
  homepage_section?: boolean | Prisma.HomepageSectionDefaultArgs<ExtArgs>
  language?: boolean | Prisma.LanguageDefaultArgs<ExtArgs>
}, ExtArgs["result"]["homepageSectionTranslation"]>

export type HomepageSectionTranslationSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  homepage_section_id?: boolean
  language_id?: boolean
  title?: boolean
  homepage_section?: boolean | Prisma.HomepageSectionDefaultArgs<ExtArgs>
  language?: boolean | Prisma.LanguageDefaultArgs<ExtArgs>
}, ExtArgs["result"]["homepageSectionTranslation"]>

export type HomepageSectionTranslationSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  homepage_section_id?: boolean
  language_id?: boolean
  title?: boolean
  homepage_section?: boolean | Prisma.HomepageSectionDefaultArgs<ExtArgs>
  language?: boolean | Prisma.LanguageDefaultArgs<ExtArgs>
}, ExtArgs["result"]["homepageSectionTranslation"]>

export type HomepageSectionTranslationSelectScalar = {
  id?: boolean
  homepage_section_id?: boolean
  language_id?: boolean
  title?: boolean
}

export type HomepageSectionTranslationOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "homepage_section_id" | "language_id" | "title", ExtArgs["result"]["homepageSectionTranslation"]>
export type HomepageSectionTranslationInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  homepage_section?: boolean | Prisma.HomepageSectionDefaultArgs<ExtArgs>
  language?: boolean | Prisma.LanguageDefaultArgs<ExtArgs>
}
export type HomepageSectionTranslationIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  homepage_section?: boolean | Prisma.HomepageSectionDefaultArgs<ExtArgs>
  language?: boolean | Prisma.LanguageDefaultArgs<ExtArgs>
}
export type HomepageSectionTranslationIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  homepage_section?: boolean | Prisma.HomepageSectionDefaultArgs<ExtArgs>
  language?: boolean | Prisma.LanguageDefaultArgs<ExtArgs>
}

export type $HomepageSectionTranslationPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "HomepageSectionTranslation"
  objects: {
    homepage_section: Prisma.$HomepageSectionPayload<ExtArgs>
    language: Prisma.$LanguagePayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    homepage_section_id: string
    language_id: string
    title: string
  }, ExtArgs["result"]["homepageSectionTranslation"]>
  composites: {}
}

export type HomepageSectionTranslationGetPayload<S extends boolean | null | undefined | HomepageSectionTranslationDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$HomepageSectionTranslationPayload, S>

export type HomepageSectionTranslationCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<HomepageSectionTranslationFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: HomepageSectionTranslationCountAggregateInputType | true
  }

export interface HomepageSectionTranslationDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['HomepageSectionTranslation'], meta: { name: 'HomepageSectionTranslation' } }
  /**
   * Find zero or one HomepageSectionTranslation that matches the filter.
   * @param {HomepageSectionTranslationFindUniqueArgs} args - Arguments to find a HomepageSectionTranslation
   * @example
   * // Get one HomepageSectionTranslation
   * const homepageSectionTranslation = await prisma.homepageSectionTranslation.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends HomepageSectionTranslationFindUniqueArgs>(args: Prisma.SelectSubset<T, HomepageSectionTranslationFindUniqueArgs<ExtArgs>>): Prisma.Prisma__HomepageSectionTranslationClient<runtime.Types.Result.GetResult<Prisma.$HomepageSectionTranslationPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one HomepageSectionTranslation that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {HomepageSectionTranslationFindUniqueOrThrowArgs} args - Arguments to find a HomepageSectionTranslation
   * @example
   * // Get one HomepageSectionTranslation
   * const homepageSectionTranslation = await prisma.homepageSectionTranslation.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends HomepageSectionTranslationFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, HomepageSectionTranslationFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__HomepageSectionTranslationClient<runtime.Types.Result.GetResult<Prisma.$HomepageSectionTranslationPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first HomepageSectionTranslation that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HomepageSectionTranslationFindFirstArgs} args - Arguments to find a HomepageSectionTranslation
   * @example
   * // Get one HomepageSectionTranslation
   * const homepageSectionTranslation = await prisma.homepageSectionTranslation.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends HomepageSectionTranslationFindFirstArgs>(args?: Prisma.SelectSubset<T, HomepageSectionTranslationFindFirstArgs<ExtArgs>>): Prisma.Prisma__HomepageSectionTranslationClient<runtime.Types.Result.GetResult<Prisma.$HomepageSectionTranslationPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first HomepageSectionTranslation that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HomepageSectionTranslationFindFirstOrThrowArgs} args - Arguments to find a HomepageSectionTranslation
   * @example
   * // Get one HomepageSectionTranslation
   * const homepageSectionTranslation = await prisma.homepageSectionTranslation.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends HomepageSectionTranslationFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, HomepageSectionTranslationFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__HomepageSectionTranslationClient<runtime.Types.Result.GetResult<Prisma.$HomepageSectionTranslationPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more HomepageSectionTranslations that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HomepageSectionTranslationFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all HomepageSectionTranslations
   * const homepageSectionTranslations = await prisma.homepageSectionTranslation.findMany()
   * 
   * // Get first 10 HomepageSectionTranslations
   * const homepageSectionTranslations = await prisma.homepageSectionTranslation.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const homepageSectionTranslationWithIdOnly = await prisma.homepageSectionTranslation.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends HomepageSectionTranslationFindManyArgs>(args?: Prisma.SelectSubset<T, HomepageSectionTranslationFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$HomepageSectionTranslationPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a HomepageSectionTranslation.
   * @param {HomepageSectionTranslationCreateArgs} args - Arguments to create a HomepageSectionTranslation.
   * @example
   * // Create one HomepageSectionTranslation
   * const HomepageSectionTranslation = await prisma.homepageSectionTranslation.create({
   *   data: {
   *     // ... data to create a HomepageSectionTranslation
   *   }
   * })
   * 
   */
  create<T extends HomepageSectionTranslationCreateArgs>(args: Prisma.SelectSubset<T, HomepageSectionTranslationCreateArgs<ExtArgs>>): Prisma.Prisma__HomepageSectionTranslationClient<runtime.Types.Result.GetResult<Prisma.$HomepageSectionTranslationPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many HomepageSectionTranslations.
   * @param {HomepageSectionTranslationCreateManyArgs} args - Arguments to create many HomepageSectionTranslations.
   * @example
   * // Create many HomepageSectionTranslations
   * const homepageSectionTranslation = await prisma.homepageSectionTranslation.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends HomepageSectionTranslationCreateManyArgs>(args?: Prisma.SelectSubset<T, HomepageSectionTranslationCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many HomepageSectionTranslations and returns the data saved in the database.
   * @param {HomepageSectionTranslationCreateManyAndReturnArgs} args - Arguments to create many HomepageSectionTranslations.
   * @example
   * // Create many HomepageSectionTranslations
   * const homepageSectionTranslation = await prisma.homepageSectionTranslation.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many HomepageSectionTranslations and only return the `id`
   * const homepageSectionTranslationWithIdOnly = await prisma.homepageSectionTranslation.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends HomepageSectionTranslationCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, HomepageSectionTranslationCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$HomepageSectionTranslationPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a HomepageSectionTranslation.
   * @param {HomepageSectionTranslationDeleteArgs} args - Arguments to delete one HomepageSectionTranslation.
   * @example
   * // Delete one HomepageSectionTranslation
   * const HomepageSectionTranslation = await prisma.homepageSectionTranslation.delete({
   *   where: {
   *     // ... filter to delete one HomepageSectionTranslation
   *   }
   * })
   * 
   */
  delete<T extends HomepageSectionTranslationDeleteArgs>(args: Prisma.SelectSubset<T, HomepageSectionTranslationDeleteArgs<ExtArgs>>): Prisma.Prisma__HomepageSectionTranslationClient<runtime.Types.Result.GetResult<Prisma.$HomepageSectionTranslationPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one HomepageSectionTranslation.
   * @param {HomepageSectionTranslationUpdateArgs} args - Arguments to update one HomepageSectionTranslation.
   * @example
   * // Update one HomepageSectionTranslation
   * const homepageSectionTranslation = await prisma.homepageSectionTranslation.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends HomepageSectionTranslationUpdateArgs>(args: Prisma.SelectSubset<T, HomepageSectionTranslationUpdateArgs<ExtArgs>>): Prisma.Prisma__HomepageSectionTranslationClient<runtime.Types.Result.GetResult<Prisma.$HomepageSectionTranslationPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more HomepageSectionTranslations.
   * @param {HomepageSectionTranslationDeleteManyArgs} args - Arguments to filter HomepageSectionTranslations to delete.
   * @example
   * // Delete a few HomepageSectionTranslations
   * const { count } = await prisma.homepageSectionTranslation.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends HomepageSectionTranslationDeleteManyArgs>(args?: Prisma.SelectSubset<T, HomepageSectionTranslationDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more HomepageSectionTranslations.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HomepageSectionTranslationUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many HomepageSectionTranslations
   * const homepageSectionTranslation = await prisma.homepageSectionTranslation.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends HomepageSectionTranslationUpdateManyArgs>(args: Prisma.SelectSubset<T, HomepageSectionTranslationUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more HomepageSectionTranslations and returns the data updated in the database.
   * @param {HomepageSectionTranslationUpdateManyAndReturnArgs} args - Arguments to update many HomepageSectionTranslations.
   * @example
   * // Update many HomepageSectionTranslations
   * const homepageSectionTranslation = await prisma.homepageSectionTranslation.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more HomepageSectionTranslations and only return the `id`
   * const homepageSectionTranslationWithIdOnly = await prisma.homepageSectionTranslation.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends HomepageSectionTranslationUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, HomepageSectionTranslationUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$HomepageSectionTranslationPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one HomepageSectionTranslation.
   * @param {HomepageSectionTranslationUpsertArgs} args - Arguments to update or create a HomepageSectionTranslation.
   * @example
   * // Update or create a HomepageSectionTranslation
   * const homepageSectionTranslation = await prisma.homepageSectionTranslation.upsert({
   *   create: {
   *     // ... data to create a HomepageSectionTranslation
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the HomepageSectionTranslation we want to update
   *   }
   * })
   */
  upsert<T extends HomepageSectionTranslationUpsertArgs>(args: Prisma.SelectSubset<T, HomepageSectionTranslationUpsertArgs<ExtArgs>>): Prisma.Prisma__HomepageSectionTranslationClient<runtime.Types.Result.GetResult<Prisma.$HomepageSectionTranslationPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of HomepageSectionTranslations.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HomepageSectionTranslationCountArgs} args - Arguments to filter HomepageSectionTranslations to count.
   * @example
   * // Count the number of HomepageSectionTranslations
   * const count = await prisma.homepageSectionTranslation.count({
   *   where: {
   *     // ... the filter for the HomepageSectionTranslations we want to count
   *   }
   * })
  **/
  count<T extends HomepageSectionTranslationCountArgs>(
    args?: Prisma.Subset<T, HomepageSectionTranslationCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], HomepageSectionTranslationCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a HomepageSectionTranslation.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HomepageSectionTranslationAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends HomepageSectionTranslationAggregateArgs>(args: Prisma.Subset<T, HomepageSectionTranslationAggregateArgs>): Prisma.PrismaPromise<GetHomepageSectionTranslationAggregateType<T>>

  /**
   * Group by HomepageSectionTranslation.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HomepageSectionTranslationGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends HomepageSectionTranslationGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: HomepageSectionTranslationGroupByArgs['orderBy'] }
      : { orderBy?: HomepageSectionTranslationGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, HomepageSectionTranslationGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetHomepageSectionTranslationGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the HomepageSectionTranslation model
 */
readonly fields: HomepageSectionTranslationFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for HomepageSectionTranslation.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__HomepageSectionTranslationClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  homepage_section<T extends Prisma.HomepageSectionDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.HomepageSectionDefaultArgs<ExtArgs>>): Prisma.Prisma__HomepageSectionClient<runtime.Types.Result.GetResult<Prisma.$HomepageSectionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  language<T extends Prisma.LanguageDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.LanguageDefaultArgs<ExtArgs>>): Prisma.Prisma__LanguageClient<runtime.Types.Result.GetResult<Prisma.$LanguagePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the HomepageSectionTranslation model
 */
export interface HomepageSectionTranslationFieldRefs {
  readonly id: Prisma.FieldRef<"HomepageSectionTranslation", 'String'>
  readonly homepage_section_id: Prisma.FieldRef<"HomepageSectionTranslation", 'String'>
  readonly language_id: Prisma.FieldRef<"HomepageSectionTranslation", 'String'>
  readonly title: Prisma.FieldRef<"HomepageSectionTranslation", 'String'>
}
    

// Custom InputTypes
/**
 * HomepageSectionTranslation findUnique
 */
export type HomepageSectionTranslationFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HomepageSectionTranslation
   */
  select?: Prisma.HomepageSectionTranslationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the HomepageSectionTranslation
   */
  omit?: Prisma.HomepageSectionTranslationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HomepageSectionTranslationInclude<ExtArgs> | null
  /**
   * Filter, which HomepageSectionTranslation to fetch.
   */
  where: Prisma.HomepageSectionTranslationWhereUniqueInput
}

/**
 * HomepageSectionTranslation findUniqueOrThrow
 */
export type HomepageSectionTranslationFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HomepageSectionTranslation
   */
  select?: Prisma.HomepageSectionTranslationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the HomepageSectionTranslation
   */
  omit?: Prisma.HomepageSectionTranslationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HomepageSectionTranslationInclude<ExtArgs> | null
  /**
   * Filter, which HomepageSectionTranslation to fetch.
   */
  where: Prisma.HomepageSectionTranslationWhereUniqueInput
}

/**
 * HomepageSectionTranslation findFirst
 */
export type HomepageSectionTranslationFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HomepageSectionTranslation
   */
  select?: Prisma.HomepageSectionTranslationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the HomepageSectionTranslation
   */
  omit?: Prisma.HomepageSectionTranslationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HomepageSectionTranslationInclude<ExtArgs> | null
  /**
   * Filter, which HomepageSectionTranslation to fetch.
   */
  where?: Prisma.HomepageSectionTranslationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of HomepageSectionTranslations to fetch.
   */
  orderBy?: Prisma.HomepageSectionTranslationOrderByWithRelationInput | Prisma.HomepageSectionTranslationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for HomepageSectionTranslations.
   */
  cursor?: Prisma.HomepageSectionTranslationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` HomepageSectionTranslations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` HomepageSectionTranslations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of HomepageSectionTranslations.
   */
  distinct?: Prisma.HomepageSectionTranslationScalarFieldEnum | Prisma.HomepageSectionTranslationScalarFieldEnum[]
}

/**
 * HomepageSectionTranslation findFirstOrThrow
 */
export type HomepageSectionTranslationFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HomepageSectionTranslation
   */
  select?: Prisma.HomepageSectionTranslationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the HomepageSectionTranslation
   */
  omit?: Prisma.HomepageSectionTranslationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HomepageSectionTranslationInclude<ExtArgs> | null
  /**
   * Filter, which HomepageSectionTranslation to fetch.
   */
  where?: Prisma.HomepageSectionTranslationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of HomepageSectionTranslations to fetch.
   */
  orderBy?: Prisma.HomepageSectionTranslationOrderByWithRelationInput | Prisma.HomepageSectionTranslationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for HomepageSectionTranslations.
   */
  cursor?: Prisma.HomepageSectionTranslationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` HomepageSectionTranslations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` HomepageSectionTranslations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of HomepageSectionTranslations.
   */
  distinct?: Prisma.HomepageSectionTranslationScalarFieldEnum | Prisma.HomepageSectionTranslationScalarFieldEnum[]
}

/**
 * HomepageSectionTranslation findMany
 */
export type HomepageSectionTranslationFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HomepageSectionTranslation
   */
  select?: Prisma.HomepageSectionTranslationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the HomepageSectionTranslation
   */
  omit?: Prisma.HomepageSectionTranslationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HomepageSectionTranslationInclude<ExtArgs> | null
  /**
   * Filter, which HomepageSectionTranslations to fetch.
   */
  where?: Prisma.HomepageSectionTranslationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of HomepageSectionTranslations to fetch.
   */
  orderBy?: Prisma.HomepageSectionTranslationOrderByWithRelationInput | Prisma.HomepageSectionTranslationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing HomepageSectionTranslations.
   */
  cursor?: Prisma.HomepageSectionTranslationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` HomepageSectionTranslations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` HomepageSectionTranslations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of HomepageSectionTranslations.
   */
  distinct?: Prisma.HomepageSectionTranslationScalarFieldEnum | Prisma.HomepageSectionTranslationScalarFieldEnum[]
}

/**
 * HomepageSectionTranslation create
 */
export type HomepageSectionTranslationCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HomepageSectionTranslation
   */
  select?: Prisma.HomepageSectionTranslationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the HomepageSectionTranslation
   */
  omit?: Prisma.HomepageSectionTranslationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HomepageSectionTranslationInclude<ExtArgs> | null
  /**
   * The data needed to create a HomepageSectionTranslation.
   */
  data: Prisma.XOR<Prisma.HomepageSectionTranslationCreateInput, Prisma.HomepageSectionTranslationUncheckedCreateInput>
}

/**
 * HomepageSectionTranslation createMany
 */
export type HomepageSectionTranslationCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many HomepageSectionTranslations.
   */
  data: Prisma.HomepageSectionTranslationCreateManyInput | Prisma.HomepageSectionTranslationCreateManyInput[]
}

/**
 * HomepageSectionTranslation createManyAndReturn
 */
export type HomepageSectionTranslationCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HomepageSectionTranslation
   */
  select?: Prisma.HomepageSectionTranslationSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the HomepageSectionTranslation
   */
  omit?: Prisma.HomepageSectionTranslationOmit<ExtArgs> | null
  /**
   * The data used to create many HomepageSectionTranslations.
   */
  data: Prisma.HomepageSectionTranslationCreateManyInput | Prisma.HomepageSectionTranslationCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HomepageSectionTranslationIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * HomepageSectionTranslation update
 */
export type HomepageSectionTranslationUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HomepageSectionTranslation
   */
  select?: Prisma.HomepageSectionTranslationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the HomepageSectionTranslation
   */
  omit?: Prisma.HomepageSectionTranslationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HomepageSectionTranslationInclude<ExtArgs> | null
  /**
   * The data needed to update a HomepageSectionTranslation.
   */
  data: Prisma.XOR<Prisma.HomepageSectionTranslationUpdateInput, Prisma.HomepageSectionTranslationUncheckedUpdateInput>
  /**
   * Choose, which HomepageSectionTranslation to update.
   */
  where: Prisma.HomepageSectionTranslationWhereUniqueInput
}

/**
 * HomepageSectionTranslation updateMany
 */
export type HomepageSectionTranslationUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update HomepageSectionTranslations.
   */
  data: Prisma.XOR<Prisma.HomepageSectionTranslationUpdateManyMutationInput, Prisma.HomepageSectionTranslationUncheckedUpdateManyInput>
  /**
   * Filter which HomepageSectionTranslations to update
   */
  where?: Prisma.HomepageSectionTranslationWhereInput
  /**
   * Limit how many HomepageSectionTranslations to update.
   */
  limit?: number
}

/**
 * HomepageSectionTranslation updateManyAndReturn
 */
export type HomepageSectionTranslationUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HomepageSectionTranslation
   */
  select?: Prisma.HomepageSectionTranslationSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the HomepageSectionTranslation
   */
  omit?: Prisma.HomepageSectionTranslationOmit<ExtArgs> | null
  /**
   * The data used to update HomepageSectionTranslations.
   */
  data: Prisma.XOR<Prisma.HomepageSectionTranslationUpdateManyMutationInput, Prisma.HomepageSectionTranslationUncheckedUpdateManyInput>
  /**
   * Filter which HomepageSectionTranslations to update
   */
  where?: Prisma.HomepageSectionTranslationWhereInput
  /**
   * Limit how many HomepageSectionTranslations to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HomepageSectionTranslationIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * HomepageSectionTranslation upsert
 */
export type HomepageSectionTranslationUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HomepageSectionTranslation
   */
  select?: Prisma.HomepageSectionTranslationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the HomepageSectionTranslation
   */
  omit?: Prisma.HomepageSectionTranslationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HomepageSectionTranslationInclude<ExtArgs> | null
  /**
   * The filter to search for the HomepageSectionTranslation to update in case it exists.
   */
  where: Prisma.HomepageSectionTranslationWhereUniqueInput
  /**
   * In case the HomepageSectionTranslation found by the `where` argument doesn't exist, create a new HomepageSectionTranslation with this data.
   */
  create: Prisma.XOR<Prisma.HomepageSectionTranslationCreateInput, Prisma.HomepageSectionTranslationUncheckedCreateInput>
  /**
   * In case the HomepageSectionTranslation was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.HomepageSectionTranslationUpdateInput, Prisma.HomepageSectionTranslationUncheckedUpdateInput>
}

/**
 * HomepageSectionTranslation delete
 */
export type HomepageSectionTranslationDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HomepageSectionTranslation
   */
  select?: Prisma.HomepageSectionTranslationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the HomepageSectionTranslation
   */
  omit?: Prisma.HomepageSectionTranslationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HomepageSectionTranslationInclude<ExtArgs> | null
  /**
   * Filter which HomepageSectionTranslation to delete.
   */
  where: Prisma.HomepageSectionTranslationWhereUniqueInput
}

/**
 * HomepageSectionTranslation deleteMany
 */
export type HomepageSectionTranslationDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which HomepageSectionTranslations to delete
   */
  where?: Prisma.HomepageSectionTranslationWhereInput
  /**
   * Limit how many HomepageSectionTranslations to delete.
   */
  limit?: number
}

/**
 * HomepageSectionTranslation without action
 */
export type HomepageSectionTranslationDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HomepageSectionTranslation
   */
  select?: Prisma.HomepageSectionTranslationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the HomepageSectionTranslation
   */
  omit?: Prisma.HomepageSectionTranslationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HomepageSectionTranslationInclude<ExtArgs> | null
}
