
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Image` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Image
 * 
 */
export type ImageModel = runtime.Types.Result.DefaultSelection<Prisma.$ImagePayload>

export type AggregateImage = {
  _count: ImageCountAggregateOutputType | null
  _avg: ImageAvgAggregateOutputType | null
  _sum: ImageSumAggregateOutputType | null
  _min: ImageMinAggregateOutputType | null
  _max: ImageMaxAggregateOutputType | null
}

export type ImageAvgAggregateOutputType = {
  width: number | null
  height: number | null
  bytes: number | null
}

export type ImageSumAggregateOutputType = {
  width: number | null
  height: number | null
  bytes: number | null
}

export type ImageMinAggregateOutputType = {
  id: string | null
  url: string | null
  public_id: string | null
  width: number | null
  height: number | null
  format: string | null
  bytes: number | null
  created_at: Date | null
  updated_at: Date | null
}

export type ImageMaxAggregateOutputType = {
  id: string | null
  url: string | null
  public_id: string | null
  width: number | null
  height: number | null
  format: string | null
  bytes: number | null
  created_at: Date | null
  updated_at: Date | null
}

export type ImageCountAggregateOutputType = {
  id: number
  url: number
  public_id: number
  width: number
  height: number
  format: number
  bytes: number
  created_at: number
  updated_at: number
  _all: number
}


export type ImageAvgAggregateInputType = {
  width?: true
  height?: true
  bytes?: true
}

export type ImageSumAggregateInputType = {
  width?: true
  height?: true
  bytes?: true
}

export type ImageMinAggregateInputType = {
  id?: true
  url?: true
  public_id?: true
  width?: true
  height?: true
  format?: true
  bytes?: true
  created_at?: true
  updated_at?: true
}

export type ImageMaxAggregateInputType = {
  id?: true
  url?: true
  public_id?: true
  width?: true
  height?: true
  format?: true
  bytes?: true
  created_at?: true
  updated_at?: true
}

export type ImageCountAggregateInputType = {
  id?: true
  url?: true
  public_id?: true
  width?: true
  height?: true
  format?: true
  bytes?: true
  created_at?: true
  updated_at?: true
  _all?: true
}

export type ImageAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Image to aggregate.
   */
  where?: Prisma.ImageWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Images to fetch.
   */
  orderBy?: Prisma.ImageOrderByWithRelationInput | Prisma.ImageOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ImageWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Images from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Images.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Images
  **/
  _count?: true | ImageCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ImageAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ImageSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ImageMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ImageMaxAggregateInputType
}

export type GetImageAggregateType<T extends ImageAggregateArgs> = {
      [P in keyof T & keyof AggregateImage]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateImage[P]>
    : Prisma.GetScalarType<T[P], AggregateImage[P]>
}




export type ImageGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ImageWhereInput
  orderBy?: Prisma.ImageOrderByWithAggregationInput | Prisma.ImageOrderByWithAggregationInput[]
  by: Prisma.ImageScalarFieldEnum[] | Prisma.ImageScalarFieldEnum
  having?: Prisma.ImageScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ImageCountAggregateInputType | true
  _avg?: ImageAvgAggregateInputType
  _sum?: ImageSumAggregateInputType
  _min?: ImageMinAggregateInputType
  _max?: ImageMaxAggregateInputType
}

export type ImageGroupByOutputType = {
  id: string
  url: string
  public_id: string
  width: number | null
  height: number | null
  format: string | null
  bytes: number | null
  created_at: Date
  updated_at: Date
  _count: ImageCountAggregateOutputType | null
  _avg: ImageAvgAggregateOutputType | null
  _sum: ImageSumAggregateOutputType | null
  _min: ImageMinAggregateOutputType | null
  _max: ImageMaxAggregateOutputType | null
}

export type GetImageGroupByPayload<T extends ImageGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ImageGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ImageGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ImageGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ImageGroupByOutputType[P]>
      }
    >
  >



export type ImageWhereInput = {
  AND?: Prisma.ImageWhereInput | Prisma.ImageWhereInput[]
  OR?: Prisma.ImageWhereInput[]
  NOT?: Prisma.ImageWhereInput | Prisma.ImageWhereInput[]
  id?: Prisma.StringFilter<"Image"> | string
  url?: Prisma.StringFilter<"Image"> | string
  public_id?: Prisma.StringFilter<"Image"> | string
  width?: Prisma.IntNullableFilter<"Image"> | number | null
  height?: Prisma.IntNullableFilter<"Image"> | number | null
  format?: Prisma.StringNullableFilter<"Image"> | string | null
  bytes?: Prisma.IntNullableFilter<"Image"> | number | null
  created_at?: Prisma.DateTimeFilter<"Image"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"Image"> | Date | string
  user?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
  product?: Prisma.XOR<Prisma.ProductNullableScalarRelationFilter, Prisma.ProductWhereInput> | null
  category?: Prisma.XOR<Prisma.ProductCategoryNullableScalarRelationFilter, Prisma.ProductCategoryWhereInput> | null
  brand_logo?: Prisma.XOR<Prisma.BrandNullableScalarRelationFilter, Prisma.BrandWhereInput> | null
  brand_banner?: Prisma.XOR<Prisma.BrandNullableScalarRelationFilter, Prisma.BrandWhereInput> | null
  help_contact_submission_images?: Prisma.HelpContactSubmissionImageListRelationFilter
}

export type ImageOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  url?: Prisma.SortOrder
  public_id?: Prisma.SortOrder
  width?: Prisma.SortOrderInput | Prisma.SortOrder
  height?: Prisma.SortOrderInput | Prisma.SortOrder
  format?: Prisma.SortOrderInput | Prisma.SortOrder
  bytes?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
  product?: Prisma.ProductOrderByWithRelationInput
  category?: Prisma.ProductCategoryOrderByWithRelationInput
  brand_logo?: Prisma.BrandOrderByWithRelationInput
  brand_banner?: Prisma.BrandOrderByWithRelationInput
  help_contact_submission_images?: Prisma.HelpContactSubmissionImageOrderByRelationAggregateInput
}

export type ImageWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.ImageWhereInput | Prisma.ImageWhereInput[]
  OR?: Prisma.ImageWhereInput[]
  NOT?: Prisma.ImageWhereInput | Prisma.ImageWhereInput[]
  url?: Prisma.StringFilter<"Image"> | string
  public_id?: Prisma.StringFilter<"Image"> | string
  width?: Prisma.IntNullableFilter<"Image"> | number | null
  height?: Prisma.IntNullableFilter<"Image"> | number | null
  format?: Prisma.StringNullableFilter<"Image"> | string | null
  bytes?: Prisma.IntNullableFilter<"Image"> | number | null
  created_at?: Prisma.DateTimeFilter<"Image"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"Image"> | Date | string
  user?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
  product?: Prisma.XOR<Prisma.ProductNullableScalarRelationFilter, Prisma.ProductWhereInput> | null
  category?: Prisma.XOR<Prisma.ProductCategoryNullableScalarRelationFilter, Prisma.ProductCategoryWhereInput> | null
  brand_logo?: Prisma.XOR<Prisma.BrandNullableScalarRelationFilter, Prisma.BrandWhereInput> | null
  brand_banner?: Prisma.XOR<Prisma.BrandNullableScalarRelationFilter, Prisma.BrandWhereInput> | null
  help_contact_submission_images?: Prisma.HelpContactSubmissionImageListRelationFilter
}, "id">

export type ImageOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  url?: Prisma.SortOrder
  public_id?: Prisma.SortOrder
  width?: Prisma.SortOrderInput | Prisma.SortOrder
  height?: Prisma.SortOrderInput | Prisma.SortOrder
  format?: Prisma.SortOrderInput | Prisma.SortOrder
  bytes?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  _count?: Prisma.ImageCountOrderByAggregateInput
  _avg?: Prisma.ImageAvgOrderByAggregateInput
  _max?: Prisma.ImageMaxOrderByAggregateInput
  _min?: Prisma.ImageMinOrderByAggregateInput
  _sum?: Prisma.ImageSumOrderByAggregateInput
}

export type ImageScalarWhereWithAggregatesInput = {
  AND?: Prisma.ImageScalarWhereWithAggregatesInput | Prisma.ImageScalarWhereWithAggregatesInput[]
  OR?: Prisma.ImageScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ImageScalarWhereWithAggregatesInput | Prisma.ImageScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Image"> | string
  url?: Prisma.StringWithAggregatesFilter<"Image"> | string
  public_id?: Prisma.StringWithAggregatesFilter<"Image"> | string
  width?: Prisma.IntNullableWithAggregatesFilter<"Image"> | number | null
  height?: Prisma.IntNullableWithAggregatesFilter<"Image"> | number | null
  format?: Prisma.StringNullableWithAggregatesFilter<"Image"> | string | null
  bytes?: Prisma.IntNullableWithAggregatesFilter<"Image"> | number | null
  created_at?: Prisma.DateTimeWithAggregatesFilter<"Image"> | Date | string
  updated_at?: Prisma.DateTimeWithAggregatesFilter<"Image"> | Date | string
}

export type ImageCreateInput = {
  id?: string
  url: string
  public_id: string
  width?: number | null
  height?: number | null
  format?: string | null
  bytes?: number | null
  created_at?: Date | string
  updated_at?: Date | string
  user?: Prisma.UserCreateNestedOneWithoutAvatarInput
  product?: Prisma.ProductCreateNestedOneWithoutThumbnailInput
  category?: Prisma.ProductCategoryCreateNestedOneWithoutImageInput
  brand_logo?: Prisma.BrandCreateNestedOneWithoutLogoInput
  brand_banner?: Prisma.BrandCreateNestedOneWithoutBannerInput
  help_contact_submission_images?: Prisma.HelpContactSubmissionImageCreateNestedManyWithoutImageInput
}

export type ImageUncheckedCreateInput = {
  id?: string
  url: string
  public_id: string
  width?: number | null
  height?: number | null
  format?: string | null
  bytes?: number | null
  created_at?: Date | string
  updated_at?: Date | string
  user?: Prisma.UserUncheckedCreateNestedOneWithoutAvatarInput
  product?: Prisma.ProductUncheckedCreateNestedOneWithoutThumbnailInput
  category?: Prisma.ProductCategoryUncheckedCreateNestedOneWithoutImageInput
  brand_logo?: Prisma.BrandUncheckedCreateNestedOneWithoutLogoInput
  brand_banner?: Prisma.BrandUncheckedCreateNestedOneWithoutBannerInput
  help_contact_submission_images?: Prisma.HelpContactSubmissionImageUncheckedCreateNestedManyWithoutImageInput
}

export type ImageUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  public_id?: Prisma.StringFieldUpdateOperationsInput | string
  width?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  height?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  format?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bytes?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneWithoutAvatarNestedInput
  product?: Prisma.ProductUpdateOneWithoutThumbnailNestedInput
  category?: Prisma.ProductCategoryUpdateOneWithoutImageNestedInput
  brand_logo?: Prisma.BrandUpdateOneWithoutLogoNestedInput
  brand_banner?: Prisma.BrandUpdateOneWithoutBannerNestedInput
  help_contact_submission_images?: Prisma.HelpContactSubmissionImageUpdateManyWithoutImageNestedInput
}

export type ImageUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  public_id?: Prisma.StringFieldUpdateOperationsInput | string
  width?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  height?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  format?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bytes?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUncheckedUpdateOneWithoutAvatarNestedInput
  product?: Prisma.ProductUncheckedUpdateOneWithoutThumbnailNestedInput
  category?: Prisma.ProductCategoryUncheckedUpdateOneWithoutImageNestedInput
  brand_logo?: Prisma.BrandUncheckedUpdateOneWithoutLogoNestedInput
  brand_banner?: Prisma.BrandUncheckedUpdateOneWithoutBannerNestedInput
  help_contact_submission_images?: Prisma.HelpContactSubmissionImageUncheckedUpdateManyWithoutImageNestedInput
}

export type ImageCreateManyInput = {
  id?: string
  url: string
  public_id: string
  width?: number | null
  height?: number | null
  format?: string | null
  bytes?: number | null
  created_at?: Date | string
  updated_at?: Date | string
}

export type ImageUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  public_id?: Prisma.StringFieldUpdateOperationsInput | string
  width?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  height?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  format?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bytes?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ImageUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  public_id?: Prisma.StringFieldUpdateOperationsInput | string
  width?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  height?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  format?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bytes?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ImageNullableScalarRelationFilter = {
  is?: Prisma.ImageWhereInput | null
  isNot?: Prisma.ImageWhereInput | null
}

export type ImageScalarRelationFilter = {
  is?: Prisma.ImageWhereInput
  isNot?: Prisma.ImageWhereInput
}

export type ImageCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  url?: Prisma.SortOrder
  public_id?: Prisma.SortOrder
  width?: Prisma.SortOrder
  height?: Prisma.SortOrder
  format?: Prisma.SortOrder
  bytes?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type ImageAvgOrderByAggregateInput = {
  width?: Prisma.SortOrder
  height?: Prisma.SortOrder
  bytes?: Prisma.SortOrder
}

export type ImageMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  url?: Prisma.SortOrder
  public_id?: Prisma.SortOrder
  width?: Prisma.SortOrder
  height?: Prisma.SortOrder
  format?: Prisma.SortOrder
  bytes?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type ImageMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  url?: Prisma.SortOrder
  public_id?: Prisma.SortOrder
  width?: Prisma.SortOrder
  height?: Prisma.SortOrder
  format?: Prisma.SortOrder
  bytes?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type ImageSumOrderByAggregateInput = {
  width?: Prisma.SortOrder
  height?: Prisma.SortOrder
  bytes?: Prisma.SortOrder
}

export type ImageCreateNestedOneWithoutBrand_logoInput = {
  create?: Prisma.XOR<Prisma.ImageCreateWithoutBrand_logoInput, Prisma.ImageUncheckedCreateWithoutBrand_logoInput>
  connectOrCreate?: Prisma.ImageCreateOrConnectWithoutBrand_logoInput
  connect?: Prisma.ImageWhereUniqueInput
}

export type ImageCreateNestedOneWithoutBrand_bannerInput = {
  create?: Prisma.XOR<Prisma.ImageCreateWithoutBrand_bannerInput, Prisma.ImageUncheckedCreateWithoutBrand_bannerInput>
  connectOrCreate?: Prisma.ImageCreateOrConnectWithoutBrand_bannerInput
  connect?: Prisma.ImageWhereUniqueInput
}

export type ImageUpdateOneWithoutBrand_logoNestedInput = {
  create?: Prisma.XOR<Prisma.ImageCreateWithoutBrand_logoInput, Prisma.ImageUncheckedCreateWithoutBrand_logoInput>
  connectOrCreate?: Prisma.ImageCreateOrConnectWithoutBrand_logoInput
  upsert?: Prisma.ImageUpsertWithoutBrand_logoInput
  disconnect?: Prisma.ImageWhereInput | boolean
  delete?: Prisma.ImageWhereInput | boolean
  connect?: Prisma.ImageWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ImageUpdateToOneWithWhereWithoutBrand_logoInput, Prisma.ImageUpdateWithoutBrand_logoInput>, Prisma.ImageUncheckedUpdateWithoutBrand_logoInput>
}

export type ImageUpdateOneWithoutBrand_bannerNestedInput = {
  create?: Prisma.XOR<Prisma.ImageCreateWithoutBrand_bannerInput, Prisma.ImageUncheckedCreateWithoutBrand_bannerInput>
  connectOrCreate?: Prisma.ImageCreateOrConnectWithoutBrand_bannerInput
  upsert?: Prisma.ImageUpsertWithoutBrand_bannerInput
  disconnect?: Prisma.ImageWhereInput | boolean
  delete?: Prisma.ImageWhereInput | boolean
  connect?: Prisma.ImageWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ImageUpdateToOneWithWhereWithoutBrand_bannerInput, Prisma.ImageUpdateWithoutBrand_bannerInput>, Prisma.ImageUncheckedUpdateWithoutBrand_bannerInput>
}

export type ImageCreateNestedOneWithoutCategoryInput = {
  create?: Prisma.XOR<Prisma.ImageCreateWithoutCategoryInput, Prisma.ImageUncheckedCreateWithoutCategoryInput>
  connectOrCreate?: Prisma.ImageCreateOrConnectWithoutCategoryInput
  connect?: Prisma.ImageWhereUniqueInput
}

export type ImageUpdateOneWithoutCategoryNestedInput = {
  create?: Prisma.XOR<Prisma.ImageCreateWithoutCategoryInput, Prisma.ImageUncheckedCreateWithoutCategoryInput>
  connectOrCreate?: Prisma.ImageCreateOrConnectWithoutCategoryInput
  upsert?: Prisma.ImageUpsertWithoutCategoryInput
  disconnect?: Prisma.ImageWhereInput | boolean
  delete?: Prisma.ImageWhereInput | boolean
  connect?: Prisma.ImageWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ImageUpdateToOneWithWhereWithoutCategoryInput, Prisma.ImageUpdateWithoutCategoryInput>, Prisma.ImageUncheckedUpdateWithoutCategoryInput>
}

export type ImageCreateNestedOneWithoutHelp_contact_submission_imagesInput = {
  create?: Prisma.XOR<Prisma.ImageCreateWithoutHelp_contact_submission_imagesInput, Prisma.ImageUncheckedCreateWithoutHelp_contact_submission_imagesInput>
  connectOrCreate?: Prisma.ImageCreateOrConnectWithoutHelp_contact_submission_imagesInput
  connect?: Prisma.ImageWhereUniqueInput
}

export type ImageUpdateOneRequiredWithoutHelp_contact_submission_imagesNestedInput = {
  create?: Prisma.XOR<Prisma.ImageCreateWithoutHelp_contact_submission_imagesInput, Prisma.ImageUncheckedCreateWithoutHelp_contact_submission_imagesInput>
  connectOrCreate?: Prisma.ImageCreateOrConnectWithoutHelp_contact_submission_imagesInput
  upsert?: Prisma.ImageUpsertWithoutHelp_contact_submission_imagesInput
  connect?: Prisma.ImageWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ImageUpdateToOneWithWhereWithoutHelp_contact_submission_imagesInput, Prisma.ImageUpdateWithoutHelp_contact_submission_imagesInput>, Prisma.ImageUncheckedUpdateWithoutHelp_contact_submission_imagesInput>
}

export type ImageCreateNestedOneWithoutProductInput = {
  create?: Prisma.XOR<Prisma.ImageCreateWithoutProductInput, Prisma.ImageUncheckedCreateWithoutProductInput>
  connectOrCreate?: Prisma.ImageCreateOrConnectWithoutProductInput
  connect?: Prisma.ImageWhereUniqueInput
}

export type ImageUpdateOneWithoutProductNestedInput = {
  create?: Prisma.XOR<Prisma.ImageCreateWithoutProductInput, Prisma.ImageUncheckedCreateWithoutProductInput>
  connectOrCreate?: Prisma.ImageCreateOrConnectWithoutProductInput
  upsert?: Prisma.ImageUpsertWithoutProductInput
  disconnect?: Prisma.ImageWhereInput | boolean
  delete?: Prisma.ImageWhereInput | boolean
  connect?: Prisma.ImageWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ImageUpdateToOneWithWhereWithoutProductInput, Prisma.ImageUpdateWithoutProductInput>, Prisma.ImageUncheckedUpdateWithoutProductInput>
}

export type ImageCreateNestedOneWithoutUserInput = {
  create?: Prisma.XOR<Prisma.ImageCreateWithoutUserInput, Prisma.ImageUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.ImageCreateOrConnectWithoutUserInput
  connect?: Prisma.ImageWhereUniqueInput
}

export type ImageUpdateOneWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.ImageCreateWithoutUserInput, Prisma.ImageUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.ImageCreateOrConnectWithoutUserInput
  upsert?: Prisma.ImageUpsertWithoutUserInput
  disconnect?: Prisma.ImageWhereInput | boolean
  delete?: Prisma.ImageWhereInput | boolean
  connect?: Prisma.ImageWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ImageUpdateToOneWithWhereWithoutUserInput, Prisma.ImageUpdateWithoutUserInput>, Prisma.ImageUncheckedUpdateWithoutUserInput>
}

export type ImageCreateWithoutBrand_logoInput = {
  id?: string
  url: string
  public_id: string
  width?: number | null
  height?: number | null
  format?: string | null
  bytes?: number | null
  created_at?: Date | string
  updated_at?: Date | string
  user?: Prisma.UserCreateNestedOneWithoutAvatarInput
  product?: Prisma.ProductCreateNestedOneWithoutThumbnailInput
  category?: Prisma.ProductCategoryCreateNestedOneWithoutImageInput
  brand_banner?: Prisma.BrandCreateNestedOneWithoutBannerInput
  help_contact_submission_images?: Prisma.HelpContactSubmissionImageCreateNestedManyWithoutImageInput
}

export type ImageUncheckedCreateWithoutBrand_logoInput = {
  id?: string
  url: string
  public_id: string
  width?: number | null
  height?: number | null
  format?: string | null
  bytes?: number | null
  created_at?: Date | string
  updated_at?: Date | string
  user?: Prisma.UserUncheckedCreateNestedOneWithoutAvatarInput
  product?: Prisma.ProductUncheckedCreateNestedOneWithoutThumbnailInput
  category?: Prisma.ProductCategoryUncheckedCreateNestedOneWithoutImageInput
  brand_banner?: Prisma.BrandUncheckedCreateNestedOneWithoutBannerInput
  help_contact_submission_images?: Prisma.HelpContactSubmissionImageUncheckedCreateNestedManyWithoutImageInput
}

export type ImageCreateOrConnectWithoutBrand_logoInput = {
  where: Prisma.ImageWhereUniqueInput
  create: Prisma.XOR<Prisma.ImageCreateWithoutBrand_logoInput, Prisma.ImageUncheckedCreateWithoutBrand_logoInput>
}

export type ImageCreateWithoutBrand_bannerInput = {
  id?: string
  url: string
  public_id: string
  width?: number | null
  height?: number | null
  format?: string | null
  bytes?: number | null
  created_at?: Date | string
  updated_at?: Date | string
  user?: Prisma.UserCreateNestedOneWithoutAvatarInput
  product?: Prisma.ProductCreateNestedOneWithoutThumbnailInput
  category?: Prisma.ProductCategoryCreateNestedOneWithoutImageInput
  brand_logo?: Prisma.BrandCreateNestedOneWithoutLogoInput
  help_contact_submission_images?: Prisma.HelpContactSubmissionImageCreateNestedManyWithoutImageInput
}

export type ImageUncheckedCreateWithoutBrand_bannerInput = {
  id?: string
  url: string
  public_id: string
  width?: number | null
  height?: number | null
  format?: string | null
  bytes?: number | null
  created_at?: Date | string
  updated_at?: Date | string
  user?: Prisma.UserUncheckedCreateNestedOneWithoutAvatarInput
  product?: Prisma.ProductUncheckedCreateNestedOneWithoutThumbnailInput
  category?: Prisma.ProductCategoryUncheckedCreateNestedOneWithoutImageInput
  brand_logo?: Prisma.BrandUncheckedCreateNestedOneWithoutLogoInput
  help_contact_submission_images?: Prisma.HelpContactSubmissionImageUncheckedCreateNestedManyWithoutImageInput
}

export type ImageCreateOrConnectWithoutBrand_bannerInput = {
  where: Prisma.ImageWhereUniqueInput
  create: Prisma.XOR<Prisma.ImageCreateWithoutBrand_bannerInput, Prisma.ImageUncheckedCreateWithoutBrand_bannerInput>
}

export type ImageUpsertWithoutBrand_logoInput = {
  update: Prisma.XOR<Prisma.ImageUpdateWithoutBrand_logoInput, Prisma.ImageUncheckedUpdateWithoutBrand_logoInput>
  create: Prisma.XOR<Prisma.ImageCreateWithoutBrand_logoInput, Prisma.ImageUncheckedCreateWithoutBrand_logoInput>
  where?: Prisma.ImageWhereInput
}

export type ImageUpdateToOneWithWhereWithoutBrand_logoInput = {
  where?: Prisma.ImageWhereInput
  data: Prisma.XOR<Prisma.ImageUpdateWithoutBrand_logoInput, Prisma.ImageUncheckedUpdateWithoutBrand_logoInput>
}

export type ImageUpdateWithoutBrand_logoInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  public_id?: Prisma.StringFieldUpdateOperationsInput | string
  width?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  height?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  format?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bytes?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneWithoutAvatarNestedInput
  product?: Prisma.ProductUpdateOneWithoutThumbnailNestedInput
  category?: Prisma.ProductCategoryUpdateOneWithoutImageNestedInput
  brand_banner?: Prisma.BrandUpdateOneWithoutBannerNestedInput
  help_contact_submission_images?: Prisma.HelpContactSubmissionImageUpdateManyWithoutImageNestedInput
}

export type ImageUncheckedUpdateWithoutBrand_logoInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  public_id?: Prisma.StringFieldUpdateOperationsInput | string
  width?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  height?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  format?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bytes?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUncheckedUpdateOneWithoutAvatarNestedInput
  product?: Prisma.ProductUncheckedUpdateOneWithoutThumbnailNestedInput
  category?: Prisma.ProductCategoryUncheckedUpdateOneWithoutImageNestedInput
  brand_banner?: Prisma.BrandUncheckedUpdateOneWithoutBannerNestedInput
  help_contact_submission_images?: Prisma.HelpContactSubmissionImageUncheckedUpdateManyWithoutImageNestedInput
}

export type ImageUpsertWithoutBrand_bannerInput = {
  update: Prisma.XOR<Prisma.ImageUpdateWithoutBrand_bannerInput, Prisma.ImageUncheckedUpdateWithoutBrand_bannerInput>
  create: Prisma.XOR<Prisma.ImageCreateWithoutBrand_bannerInput, Prisma.ImageUncheckedCreateWithoutBrand_bannerInput>
  where?: Prisma.ImageWhereInput
}

export type ImageUpdateToOneWithWhereWithoutBrand_bannerInput = {
  where?: Prisma.ImageWhereInput
  data: Prisma.XOR<Prisma.ImageUpdateWithoutBrand_bannerInput, Prisma.ImageUncheckedUpdateWithoutBrand_bannerInput>
}

export type ImageUpdateWithoutBrand_bannerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  public_id?: Prisma.StringFieldUpdateOperationsInput | string
  width?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  height?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  format?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bytes?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneWithoutAvatarNestedInput
  product?: Prisma.ProductUpdateOneWithoutThumbnailNestedInput
  category?: Prisma.ProductCategoryUpdateOneWithoutImageNestedInput
  brand_logo?: Prisma.BrandUpdateOneWithoutLogoNestedInput
  help_contact_submission_images?: Prisma.HelpContactSubmissionImageUpdateManyWithoutImageNestedInput
}

export type ImageUncheckedUpdateWithoutBrand_bannerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  public_id?: Prisma.StringFieldUpdateOperationsInput | string
  width?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  height?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  format?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bytes?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUncheckedUpdateOneWithoutAvatarNestedInput
  product?: Prisma.ProductUncheckedUpdateOneWithoutThumbnailNestedInput
  category?: Prisma.ProductCategoryUncheckedUpdateOneWithoutImageNestedInput
  brand_logo?: Prisma.BrandUncheckedUpdateOneWithoutLogoNestedInput
  help_contact_submission_images?: Prisma.HelpContactSubmissionImageUncheckedUpdateManyWithoutImageNestedInput
}

export type ImageCreateWithoutCategoryInput = {
  id?: string
  url: string
  public_id: string
  width?: number | null
  height?: number | null
  format?: string | null
  bytes?: number | null
  created_at?: Date | string
  updated_at?: Date | string
  user?: Prisma.UserCreateNestedOneWithoutAvatarInput
  product?: Prisma.ProductCreateNestedOneWithoutThumbnailInput
  brand_logo?: Prisma.BrandCreateNestedOneWithoutLogoInput
  brand_banner?: Prisma.BrandCreateNestedOneWithoutBannerInput
  help_contact_submission_images?: Prisma.HelpContactSubmissionImageCreateNestedManyWithoutImageInput
}

export type ImageUncheckedCreateWithoutCategoryInput = {
  id?: string
  url: string
  public_id: string
  width?: number | null
  height?: number | null
  format?: string | null
  bytes?: number | null
  created_at?: Date | string
  updated_at?: Date | string
  user?: Prisma.UserUncheckedCreateNestedOneWithoutAvatarInput
  product?: Prisma.ProductUncheckedCreateNestedOneWithoutThumbnailInput
  brand_logo?: Prisma.BrandUncheckedCreateNestedOneWithoutLogoInput
  brand_banner?: Prisma.BrandUncheckedCreateNestedOneWithoutBannerInput
  help_contact_submission_images?: Prisma.HelpContactSubmissionImageUncheckedCreateNestedManyWithoutImageInput
}

export type ImageCreateOrConnectWithoutCategoryInput = {
  where: Prisma.ImageWhereUniqueInput
  create: Prisma.XOR<Prisma.ImageCreateWithoutCategoryInput, Prisma.ImageUncheckedCreateWithoutCategoryInput>
}

export type ImageUpsertWithoutCategoryInput = {
  update: Prisma.XOR<Prisma.ImageUpdateWithoutCategoryInput, Prisma.ImageUncheckedUpdateWithoutCategoryInput>
  create: Prisma.XOR<Prisma.ImageCreateWithoutCategoryInput, Prisma.ImageUncheckedCreateWithoutCategoryInput>
  where?: Prisma.ImageWhereInput
}

export type ImageUpdateToOneWithWhereWithoutCategoryInput = {
  where?: Prisma.ImageWhereInput
  data: Prisma.XOR<Prisma.ImageUpdateWithoutCategoryInput, Prisma.ImageUncheckedUpdateWithoutCategoryInput>
}

export type ImageUpdateWithoutCategoryInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  public_id?: Prisma.StringFieldUpdateOperationsInput | string
  width?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  height?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  format?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bytes?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneWithoutAvatarNestedInput
  product?: Prisma.ProductUpdateOneWithoutThumbnailNestedInput
  brand_logo?: Prisma.BrandUpdateOneWithoutLogoNestedInput
  brand_banner?: Prisma.BrandUpdateOneWithoutBannerNestedInput
  help_contact_submission_images?: Prisma.HelpContactSubmissionImageUpdateManyWithoutImageNestedInput
}

export type ImageUncheckedUpdateWithoutCategoryInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  public_id?: Prisma.StringFieldUpdateOperationsInput | string
  width?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  height?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  format?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bytes?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUncheckedUpdateOneWithoutAvatarNestedInput
  product?: Prisma.ProductUncheckedUpdateOneWithoutThumbnailNestedInput
  brand_logo?: Prisma.BrandUncheckedUpdateOneWithoutLogoNestedInput
  brand_banner?: Prisma.BrandUncheckedUpdateOneWithoutBannerNestedInput
  help_contact_submission_images?: Prisma.HelpContactSubmissionImageUncheckedUpdateManyWithoutImageNestedInput
}

export type ImageCreateWithoutHelp_contact_submission_imagesInput = {
  id?: string
  url: string
  public_id: string
  width?: number | null
  height?: number | null
  format?: string | null
  bytes?: number | null
  created_at?: Date | string
  updated_at?: Date | string
  user?: Prisma.UserCreateNestedOneWithoutAvatarInput
  product?: Prisma.ProductCreateNestedOneWithoutThumbnailInput
  category?: Prisma.ProductCategoryCreateNestedOneWithoutImageInput
  brand_logo?: Prisma.BrandCreateNestedOneWithoutLogoInput
  brand_banner?: Prisma.BrandCreateNestedOneWithoutBannerInput
}

export type ImageUncheckedCreateWithoutHelp_contact_submission_imagesInput = {
  id?: string
  url: string
  public_id: string
  width?: number | null
  height?: number | null
  format?: string | null
  bytes?: number | null
  created_at?: Date | string
  updated_at?: Date | string
  user?: Prisma.UserUncheckedCreateNestedOneWithoutAvatarInput
  product?: Prisma.ProductUncheckedCreateNestedOneWithoutThumbnailInput
  category?: Prisma.ProductCategoryUncheckedCreateNestedOneWithoutImageInput
  brand_logo?: Prisma.BrandUncheckedCreateNestedOneWithoutLogoInput
  brand_banner?: Prisma.BrandUncheckedCreateNestedOneWithoutBannerInput
}

export type ImageCreateOrConnectWithoutHelp_contact_submission_imagesInput = {
  where: Prisma.ImageWhereUniqueInput
  create: Prisma.XOR<Prisma.ImageCreateWithoutHelp_contact_submission_imagesInput, Prisma.ImageUncheckedCreateWithoutHelp_contact_submission_imagesInput>
}

export type ImageUpsertWithoutHelp_contact_submission_imagesInput = {
  update: Prisma.XOR<Prisma.ImageUpdateWithoutHelp_contact_submission_imagesInput, Prisma.ImageUncheckedUpdateWithoutHelp_contact_submission_imagesInput>
  create: Prisma.XOR<Prisma.ImageCreateWithoutHelp_contact_submission_imagesInput, Prisma.ImageUncheckedCreateWithoutHelp_contact_submission_imagesInput>
  where?: Prisma.ImageWhereInput
}

export type ImageUpdateToOneWithWhereWithoutHelp_contact_submission_imagesInput = {
  where?: Prisma.ImageWhereInput
  data: Prisma.XOR<Prisma.ImageUpdateWithoutHelp_contact_submission_imagesInput, Prisma.ImageUncheckedUpdateWithoutHelp_contact_submission_imagesInput>
}

export type ImageUpdateWithoutHelp_contact_submission_imagesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  public_id?: Prisma.StringFieldUpdateOperationsInput | string
  width?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  height?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  format?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bytes?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneWithoutAvatarNestedInput
  product?: Prisma.ProductUpdateOneWithoutThumbnailNestedInput
  category?: Prisma.ProductCategoryUpdateOneWithoutImageNestedInput
  brand_logo?: Prisma.BrandUpdateOneWithoutLogoNestedInput
  brand_banner?: Prisma.BrandUpdateOneWithoutBannerNestedInput
}

export type ImageUncheckedUpdateWithoutHelp_contact_submission_imagesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  public_id?: Prisma.StringFieldUpdateOperationsInput | string
  width?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  height?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  format?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bytes?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUncheckedUpdateOneWithoutAvatarNestedInput
  product?: Prisma.ProductUncheckedUpdateOneWithoutThumbnailNestedInput
  category?: Prisma.ProductCategoryUncheckedUpdateOneWithoutImageNestedInput
  brand_logo?: Prisma.BrandUncheckedUpdateOneWithoutLogoNestedInput
  brand_banner?: Prisma.BrandUncheckedUpdateOneWithoutBannerNestedInput
}

export type ImageCreateWithoutProductInput = {
  id?: string
  url: string
  public_id: string
  width?: number | null
  height?: number | null
  format?: string | null
  bytes?: number | null
  created_at?: Date | string
  updated_at?: Date | string
  user?: Prisma.UserCreateNestedOneWithoutAvatarInput
  category?: Prisma.ProductCategoryCreateNestedOneWithoutImageInput
  brand_logo?: Prisma.BrandCreateNestedOneWithoutLogoInput
  brand_banner?: Prisma.BrandCreateNestedOneWithoutBannerInput
  help_contact_submission_images?: Prisma.HelpContactSubmissionImageCreateNestedManyWithoutImageInput
}

export type ImageUncheckedCreateWithoutProductInput = {
  id?: string
  url: string
  public_id: string
  width?: number | null
  height?: number | null
  format?: string | null
  bytes?: number | null
  created_at?: Date | string
  updated_at?: Date | string
  user?: Prisma.UserUncheckedCreateNestedOneWithoutAvatarInput
  category?: Prisma.ProductCategoryUncheckedCreateNestedOneWithoutImageInput
  brand_logo?: Prisma.BrandUncheckedCreateNestedOneWithoutLogoInput
  brand_banner?: Prisma.BrandUncheckedCreateNestedOneWithoutBannerInput
  help_contact_submission_images?: Prisma.HelpContactSubmissionImageUncheckedCreateNestedManyWithoutImageInput
}

export type ImageCreateOrConnectWithoutProductInput = {
  where: Prisma.ImageWhereUniqueInput
  create: Prisma.XOR<Prisma.ImageCreateWithoutProductInput, Prisma.ImageUncheckedCreateWithoutProductInput>
}

export type ImageUpsertWithoutProductInput = {
  update: Prisma.XOR<Prisma.ImageUpdateWithoutProductInput, Prisma.ImageUncheckedUpdateWithoutProductInput>
  create: Prisma.XOR<Prisma.ImageCreateWithoutProductInput, Prisma.ImageUncheckedCreateWithoutProductInput>
  where?: Prisma.ImageWhereInput
}

export type ImageUpdateToOneWithWhereWithoutProductInput = {
  where?: Prisma.ImageWhereInput
  data: Prisma.XOR<Prisma.ImageUpdateWithoutProductInput, Prisma.ImageUncheckedUpdateWithoutProductInput>
}

export type ImageUpdateWithoutProductInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  public_id?: Prisma.StringFieldUpdateOperationsInput | string
  width?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  height?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  format?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bytes?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneWithoutAvatarNestedInput
  category?: Prisma.ProductCategoryUpdateOneWithoutImageNestedInput
  brand_logo?: Prisma.BrandUpdateOneWithoutLogoNestedInput
  brand_banner?: Prisma.BrandUpdateOneWithoutBannerNestedInput
  help_contact_submission_images?: Prisma.HelpContactSubmissionImageUpdateManyWithoutImageNestedInput
}

export type ImageUncheckedUpdateWithoutProductInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  public_id?: Prisma.StringFieldUpdateOperationsInput | string
  width?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  height?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  format?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bytes?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUncheckedUpdateOneWithoutAvatarNestedInput
  category?: Prisma.ProductCategoryUncheckedUpdateOneWithoutImageNestedInput
  brand_logo?: Prisma.BrandUncheckedUpdateOneWithoutLogoNestedInput
  brand_banner?: Prisma.BrandUncheckedUpdateOneWithoutBannerNestedInput
  help_contact_submission_images?: Prisma.HelpContactSubmissionImageUncheckedUpdateManyWithoutImageNestedInput
}

export type ImageCreateWithoutUserInput = {
  id?: string
  url: string
  public_id: string
  width?: number | null
  height?: number | null
  format?: string | null
  bytes?: number | null
  created_at?: Date | string
  updated_at?: Date | string
  product?: Prisma.ProductCreateNestedOneWithoutThumbnailInput
  category?: Prisma.ProductCategoryCreateNestedOneWithoutImageInput
  brand_logo?: Prisma.BrandCreateNestedOneWithoutLogoInput
  brand_banner?: Prisma.BrandCreateNestedOneWithoutBannerInput
  help_contact_submission_images?: Prisma.HelpContactSubmissionImageCreateNestedManyWithoutImageInput
}

export type ImageUncheckedCreateWithoutUserInput = {
  id?: string
  url: string
  public_id: string
  width?: number | null
  height?: number | null
  format?: string | null
  bytes?: number | null
  created_at?: Date | string
  updated_at?: Date | string
  product?: Prisma.ProductUncheckedCreateNestedOneWithoutThumbnailInput
  category?: Prisma.ProductCategoryUncheckedCreateNestedOneWithoutImageInput
  brand_logo?: Prisma.BrandUncheckedCreateNestedOneWithoutLogoInput
  brand_banner?: Prisma.BrandUncheckedCreateNestedOneWithoutBannerInput
  help_contact_submission_images?: Prisma.HelpContactSubmissionImageUncheckedCreateNestedManyWithoutImageInput
}

export type ImageCreateOrConnectWithoutUserInput = {
  where: Prisma.ImageWhereUniqueInput
  create: Prisma.XOR<Prisma.ImageCreateWithoutUserInput, Prisma.ImageUncheckedCreateWithoutUserInput>
}

export type ImageUpsertWithoutUserInput = {
  update: Prisma.XOR<Prisma.ImageUpdateWithoutUserInput, Prisma.ImageUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.ImageCreateWithoutUserInput, Prisma.ImageUncheckedCreateWithoutUserInput>
  where?: Prisma.ImageWhereInput
}

export type ImageUpdateToOneWithWhereWithoutUserInput = {
  where?: Prisma.ImageWhereInput
  data: Prisma.XOR<Prisma.ImageUpdateWithoutUserInput, Prisma.ImageUncheckedUpdateWithoutUserInput>
}

export type ImageUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  public_id?: Prisma.StringFieldUpdateOperationsInput | string
  width?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  height?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  format?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bytes?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  product?: Prisma.ProductUpdateOneWithoutThumbnailNestedInput
  category?: Prisma.ProductCategoryUpdateOneWithoutImageNestedInput
  brand_logo?: Prisma.BrandUpdateOneWithoutLogoNestedInput
  brand_banner?: Prisma.BrandUpdateOneWithoutBannerNestedInput
  help_contact_submission_images?: Prisma.HelpContactSubmissionImageUpdateManyWithoutImageNestedInput
}

export type ImageUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  public_id?: Prisma.StringFieldUpdateOperationsInput | string
  width?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  height?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  format?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bytes?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  product?: Prisma.ProductUncheckedUpdateOneWithoutThumbnailNestedInput
  category?: Prisma.ProductCategoryUncheckedUpdateOneWithoutImageNestedInput
  brand_logo?: Prisma.BrandUncheckedUpdateOneWithoutLogoNestedInput
  brand_banner?: Prisma.BrandUncheckedUpdateOneWithoutBannerNestedInput
  help_contact_submission_images?: Prisma.HelpContactSubmissionImageUncheckedUpdateManyWithoutImageNestedInput
}


/**
 * Count Type ImageCountOutputType
 */

export type ImageCountOutputType = {
  help_contact_submission_images: number
}

export type ImageCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  help_contact_submission_images?: boolean | ImageCountOutputTypeCountHelp_contact_submission_imagesArgs
}

/**
 * ImageCountOutputType without action
 */
export type ImageCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ImageCountOutputType
   */
  select?: Prisma.ImageCountOutputTypeSelect<ExtArgs> | null
}

/**
 * ImageCountOutputType without action
 */
export type ImageCountOutputTypeCountHelp_contact_submission_imagesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.HelpContactSubmissionImageWhereInput
}


export type ImageSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  url?: boolean
  public_id?: boolean
  width?: boolean
  height?: boolean
  format?: boolean
  bytes?: boolean
  created_at?: boolean
  updated_at?: boolean
  user?: boolean | Prisma.Image$userArgs<ExtArgs>
  product?: boolean | Prisma.Image$productArgs<ExtArgs>
  category?: boolean | Prisma.Image$categoryArgs<ExtArgs>
  brand_logo?: boolean | Prisma.Image$brand_logoArgs<ExtArgs>
  brand_banner?: boolean | Prisma.Image$brand_bannerArgs<ExtArgs>
  help_contact_submission_images?: boolean | Prisma.Image$help_contact_submission_imagesArgs<ExtArgs>
  _count?: boolean | Prisma.ImageCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["image"]>

export type ImageSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  url?: boolean
  public_id?: boolean
  width?: boolean
  height?: boolean
  format?: boolean
  bytes?: boolean
  created_at?: boolean
  updated_at?: boolean
}, ExtArgs["result"]["image"]>

export type ImageSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  url?: boolean
  public_id?: boolean
  width?: boolean
  height?: boolean
  format?: boolean
  bytes?: boolean
  created_at?: boolean
  updated_at?: boolean
}, ExtArgs["result"]["image"]>

export type ImageSelectScalar = {
  id?: boolean
  url?: boolean
  public_id?: boolean
  width?: boolean
  height?: boolean
  format?: boolean
  bytes?: boolean
  created_at?: boolean
  updated_at?: boolean
}

export type ImageOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "url" | "public_id" | "width" | "height" | "format" | "bytes" | "created_at" | "updated_at", ExtArgs["result"]["image"]>
export type ImageInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.Image$userArgs<ExtArgs>
  product?: boolean | Prisma.Image$productArgs<ExtArgs>
  category?: boolean | Prisma.Image$categoryArgs<ExtArgs>
  brand_logo?: boolean | Prisma.Image$brand_logoArgs<ExtArgs>
  brand_banner?: boolean | Prisma.Image$brand_bannerArgs<ExtArgs>
  help_contact_submission_images?: boolean | Prisma.Image$help_contact_submission_imagesArgs<ExtArgs>
  _count?: boolean | Prisma.ImageCountOutputTypeDefaultArgs<ExtArgs>
}
export type ImageIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type ImageIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $ImagePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Image"
  objects: {
    user: Prisma.$UserPayload<ExtArgs> | null
    product: Prisma.$ProductPayload<ExtArgs> | null
    category: Prisma.$ProductCategoryPayload<ExtArgs> | null
    brand_logo: Prisma.$BrandPayload<ExtArgs> | null
    brand_banner: Prisma.$BrandPayload<ExtArgs> | null
    help_contact_submission_images: Prisma.$HelpContactSubmissionImagePayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    url: string
    public_id: string
    width: number | null
    height: number | null
    format: string | null
    bytes: number | null
    created_at: Date
    updated_at: Date
  }, ExtArgs["result"]["image"]>
  composites: {}
}

export type ImageGetPayload<S extends boolean | null | undefined | ImageDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ImagePayload, S>

export type ImageCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ImageFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ImageCountAggregateInputType | true
  }

export interface ImageDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Image'], meta: { name: 'Image' } }
  /**
   * Find zero or one Image that matches the filter.
   * @param {ImageFindUniqueArgs} args - Arguments to find a Image
   * @example
   * // Get one Image
   * const image = await prisma.image.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ImageFindUniqueArgs>(args: Prisma.SelectSubset<T, ImageFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ImageClient<runtime.Types.Result.GetResult<Prisma.$ImagePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Image that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ImageFindUniqueOrThrowArgs} args - Arguments to find a Image
   * @example
   * // Get one Image
   * const image = await prisma.image.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ImageFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ImageFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ImageClient<runtime.Types.Result.GetResult<Prisma.$ImagePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Image that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ImageFindFirstArgs} args - Arguments to find a Image
   * @example
   * // Get one Image
   * const image = await prisma.image.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ImageFindFirstArgs>(args?: Prisma.SelectSubset<T, ImageFindFirstArgs<ExtArgs>>): Prisma.Prisma__ImageClient<runtime.Types.Result.GetResult<Prisma.$ImagePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Image that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ImageFindFirstOrThrowArgs} args - Arguments to find a Image
   * @example
   * // Get one Image
   * const image = await prisma.image.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ImageFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ImageFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ImageClient<runtime.Types.Result.GetResult<Prisma.$ImagePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Images that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ImageFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Images
   * const images = await prisma.image.findMany()
   * 
   * // Get first 10 Images
   * const images = await prisma.image.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const imageWithIdOnly = await prisma.image.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ImageFindManyArgs>(args?: Prisma.SelectSubset<T, ImageFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ImagePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Image.
   * @param {ImageCreateArgs} args - Arguments to create a Image.
   * @example
   * // Create one Image
   * const Image = await prisma.image.create({
   *   data: {
   *     // ... data to create a Image
   *   }
   * })
   * 
   */
  create<T extends ImageCreateArgs>(args: Prisma.SelectSubset<T, ImageCreateArgs<ExtArgs>>): Prisma.Prisma__ImageClient<runtime.Types.Result.GetResult<Prisma.$ImagePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Images.
   * @param {ImageCreateManyArgs} args - Arguments to create many Images.
   * @example
   * // Create many Images
   * const image = await prisma.image.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ImageCreateManyArgs>(args?: Prisma.SelectSubset<T, ImageCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Images and returns the data saved in the database.
   * @param {ImageCreateManyAndReturnArgs} args - Arguments to create many Images.
   * @example
   * // Create many Images
   * const image = await prisma.image.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Images and only return the `id`
   * const imageWithIdOnly = await prisma.image.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ImageCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ImageCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ImagePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Image.
   * @param {ImageDeleteArgs} args - Arguments to delete one Image.
   * @example
   * // Delete one Image
   * const Image = await prisma.image.delete({
   *   where: {
   *     // ... filter to delete one Image
   *   }
   * })
   * 
   */
  delete<T extends ImageDeleteArgs>(args: Prisma.SelectSubset<T, ImageDeleteArgs<ExtArgs>>): Prisma.Prisma__ImageClient<runtime.Types.Result.GetResult<Prisma.$ImagePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Image.
   * @param {ImageUpdateArgs} args - Arguments to update one Image.
   * @example
   * // Update one Image
   * const image = await prisma.image.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ImageUpdateArgs>(args: Prisma.SelectSubset<T, ImageUpdateArgs<ExtArgs>>): Prisma.Prisma__ImageClient<runtime.Types.Result.GetResult<Prisma.$ImagePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Images.
   * @param {ImageDeleteManyArgs} args - Arguments to filter Images to delete.
   * @example
   * // Delete a few Images
   * const { count } = await prisma.image.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ImageDeleteManyArgs>(args?: Prisma.SelectSubset<T, ImageDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Images.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ImageUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Images
   * const image = await prisma.image.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ImageUpdateManyArgs>(args: Prisma.SelectSubset<T, ImageUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Images and returns the data updated in the database.
   * @param {ImageUpdateManyAndReturnArgs} args - Arguments to update many Images.
   * @example
   * // Update many Images
   * const image = await prisma.image.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Images and only return the `id`
   * const imageWithIdOnly = await prisma.image.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ImageUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ImageUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ImagePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Image.
   * @param {ImageUpsertArgs} args - Arguments to update or create a Image.
   * @example
   * // Update or create a Image
   * const image = await prisma.image.upsert({
   *   create: {
   *     // ... data to create a Image
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Image we want to update
   *   }
   * })
   */
  upsert<T extends ImageUpsertArgs>(args: Prisma.SelectSubset<T, ImageUpsertArgs<ExtArgs>>): Prisma.Prisma__ImageClient<runtime.Types.Result.GetResult<Prisma.$ImagePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Images.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ImageCountArgs} args - Arguments to filter Images to count.
   * @example
   * // Count the number of Images
   * const count = await prisma.image.count({
   *   where: {
   *     // ... the filter for the Images we want to count
   *   }
   * })
  **/
  count<T extends ImageCountArgs>(
    args?: Prisma.Subset<T, ImageCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ImageCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Image.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ImageAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ImageAggregateArgs>(args: Prisma.Subset<T, ImageAggregateArgs>): Prisma.PrismaPromise<GetImageAggregateType<T>>

  /**
   * Group by Image.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ImageGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ImageGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ImageGroupByArgs['orderBy'] }
      : { orderBy?: ImageGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ImageGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetImageGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Image model
 */
readonly fields: ImageFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Image.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ImageClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.Image$userArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Image$userArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  product<T extends Prisma.Image$productArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Image$productArgs<ExtArgs>>): Prisma.Prisma__ProductClient<runtime.Types.Result.GetResult<Prisma.$ProductPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  category<T extends Prisma.Image$categoryArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Image$categoryArgs<ExtArgs>>): Prisma.Prisma__ProductCategoryClient<runtime.Types.Result.GetResult<Prisma.$ProductCategoryPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  brand_logo<T extends Prisma.Image$brand_logoArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Image$brand_logoArgs<ExtArgs>>): Prisma.Prisma__BrandClient<runtime.Types.Result.GetResult<Prisma.$BrandPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  brand_banner<T extends Prisma.Image$brand_bannerArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Image$brand_bannerArgs<ExtArgs>>): Prisma.Prisma__BrandClient<runtime.Types.Result.GetResult<Prisma.$BrandPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  help_contact_submission_images<T extends Prisma.Image$help_contact_submission_imagesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Image$help_contact_submission_imagesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$HelpContactSubmissionImagePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Image model
 */
export interface ImageFieldRefs {
  readonly id: Prisma.FieldRef<"Image", 'String'>
  readonly url: Prisma.FieldRef<"Image", 'String'>
  readonly public_id: Prisma.FieldRef<"Image", 'String'>
  readonly width: Prisma.FieldRef<"Image", 'Int'>
  readonly height: Prisma.FieldRef<"Image", 'Int'>
  readonly format: Prisma.FieldRef<"Image", 'String'>
  readonly bytes: Prisma.FieldRef<"Image", 'Int'>
  readonly created_at: Prisma.FieldRef<"Image", 'DateTime'>
  readonly updated_at: Prisma.FieldRef<"Image", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Image findUnique
 */
export type ImageFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Image
   */
  select?: Prisma.ImageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Image
   */
  omit?: Prisma.ImageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ImageInclude<ExtArgs> | null
  /**
   * Filter, which Image to fetch.
   */
  where: Prisma.ImageWhereUniqueInput
}

/**
 * Image findUniqueOrThrow
 */
export type ImageFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Image
   */
  select?: Prisma.ImageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Image
   */
  omit?: Prisma.ImageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ImageInclude<ExtArgs> | null
  /**
   * Filter, which Image to fetch.
   */
  where: Prisma.ImageWhereUniqueInput
}

/**
 * Image findFirst
 */
export type ImageFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Image
   */
  select?: Prisma.ImageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Image
   */
  omit?: Prisma.ImageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ImageInclude<ExtArgs> | null
  /**
   * Filter, which Image to fetch.
   */
  where?: Prisma.ImageWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Images to fetch.
   */
  orderBy?: Prisma.ImageOrderByWithRelationInput | Prisma.ImageOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Images.
   */
  cursor?: Prisma.ImageWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Images from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Images.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Images.
   */
  distinct?: Prisma.ImageScalarFieldEnum | Prisma.ImageScalarFieldEnum[]
}

/**
 * Image findFirstOrThrow
 */
export type ImageFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Image
   */
  select?: Prisma.ImageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Image
   */
  omit?: Prisma.ImageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ImageInclude<ExtArgs> | null
  /**
   * Filter, which Image to fetch.
   */
  where?: Prisma.ImageWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Images to fetch.
   */
  orderBy?: Prisma.ImageOrderByWithRelationInput | Prisma.ImageOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Images.
   */
  cursor?: Prisma.ImageWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Images from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Images.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Images.
   */
  distinct?: Prisma.ImageScalarFieldEnum | Prisma.ImageScalarFieldEnum[]
}

/**
 * Image findMany
 */
export type ImageFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Image
   */
  select?: Prisma.ImageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Image
   */
  omit?: Prisma.ImageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ImageInclude<ExtArgs> | null
  /**
   * Filter, which Images to fetch.
   */
  where?: Prisma.ImageWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Images to fetch.
   */
  orderBy?: Prisma.ImageOrderByWithRelationInput | Prisma.ImageOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Images.
   */
  cursor?: Prisma.ImageWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Images from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Images.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Images.
   */
  distinct?: Prisma.ImageScalarFieldEnum | Prisma.ImageScalarFieldEnum[]
}

/**
 * Image create
 */
export type ImageCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Image
   */
  select?: Prisma.ImageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Image
   */
  omit?: Prisma.ImageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ImageInclude<ExtArgs> | null
  /**
   * The data needed to create a Image.
   */
  data: Prisma.XOR<Prisma.ImageCreateInput, Prisma.ImageUncheckedCreateInput>
}

/**
 * Image createMany
 */
export type ImageCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Images.
   */
  data: Prisma.ImageCreateManyInput | Prisma.ImageCreateManyInput[]
}

/**
 * Image createManyAndReturn
 */
export type ImageCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Image
   */
  select?: Prisma.ImageSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Image
   */
  omit?: Prisma.ImageOmit<ExtArgs> | null
  /**
   * The data used to create many Images.
   */
  data: Prisma.ImageCreateManyInput | Prisma.ImageCreateManyInput[]
}

/**
 * Image update
 */
export type ImageUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Image
   */
  select?: Prisma.ImageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Image
   */
  omit?: Prisma.ImageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ImageInclude<ExtArgs> | null
  /**
   * The data needed to update a Image.
   */
  data: Prisma.XOR<Prisma.ImageUpdateInput, Prisma.ImageUncheckedUpdateInput>
  /**
   * Choose, which Image to update.
   */
  where: Prisma.ImageWhereUniqueInput
}

/**
 * Image updateMany
 */
export type ImageUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Images.
   */
  data: Prisma.XOR<Prisma.ImageUpdateManyMutationInput, Prisma.ImageUncheckedUpdateManyInput>
  /**
   * Filter which Images to update
   */
  where?: Prisma.ImageWhereInput
  /**
   * Limit how many Images to update.
   */
  limit?: number
}

/**
 * Image updateManyAndReturn
 */
export type ImageUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Image
   */
  select?: Prisma.ImageSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Image
   */
  omit?: Prisma.ImageOmit<ExtArgs> | null
  /**
   * The data used to update Images.
   */
  data: Prisma.XOR<Prisma.ImageUpdateManyMutationInput, Prisma.ImageUncheckedUpdateManyInput>
  /**
   * Filter which Images to update
   */
  where?: Prisma.ImageWhereInput
  /**
   * Limit how many Images to update.
   */
  limit?: number
}

/**
 * Image upsert
 */
export type ImageUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Image
   */
  select?: Prisma.ImageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Image
   */
  omit?: Prisma.ImageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ImageInclude<ExtArgs> | null
  /**
   * The filter to search for the Image to update in case it exists.
   */
  where: Prisma.ImageWhereUniqueInput
  /**
   * In case the Image found by the `where` argument doesn't exist, create a new Image with this data.
   */
  create: Prisma.XOR<Prisma.ImageCreateInput, Prisma.ImageUncheckedCreateInput>
  /**
   * In case the Image was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ImageUpdateInput, Prisma.ImageUncheckedUpdateInput>
}

/**
 * Image delete
 */
export type ImageDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Image
   */
  select?: Prisma.ImageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Image
   */
  omit?: Prisma.ImageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ImageInclude<ExtArgs> | null
  /**
   * Filter which Image to delete.
   */
  where: Prisma.ImageWhereUniqueInput
}

/**
 * Image deleteMany
 */
export type ImageDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Images to delete
   */
  where?: Prisma.ImageWhereInput
  /**
   * Limit how many Images to delete.
   */
  limit?: number
}

/**
 * Image.user
 */
export type Image$userArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  where?: Prisma.UserWhereInput
}

/**
 * Image.product
 */
export type Image$productArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Product
   */
  select?: Prisma.ProductSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Product
   */
  omit?: Prisma.ProductOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductInclude<ExtArgs> | null
  where?: Prisma.ProductWhereInput
}

/**
 * Image.category
 */
export type Image$categoryArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductCategory
   */
  select?: Prisma.ProductCategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductCategory
   */
  omit?: Prisma.ProductCategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductCategoryInclude<ExtArgs> | null
  where?: Prisma.ProductCategoryWhereInput
}

/**
 * Image.brand_logo
 */
export type Image$brand_logoArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Brand
   */
  select?: Prisma.BrandSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Brand
   */
  omit?: Prisma.BrandOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BrandInclude<ExtArgs> | null
  where?: Prisma.BrandWhereInput
}

/**
 * Image.brand_banner
 */
export type Image$brand_bannerArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Brand
   */
  select?: Prisma.BrandSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Brand
   */
  omit?: Prisma.BrandOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BrandInclude<ExtArgs> | null
  where?: Prisma.BrandWhereInput
}

/**
 * Image.help_contact_submission_images
 */
export type Image$help_contact_submission_imagesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HelpContactSubmissionImage
   */
  select?: Prisma.HelpContactSubmissionImageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the HelpContactSubmissionImage
   */
  omit?: Prisma.HelpContactSubmissionImageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HelpContactSubmissionImageInclude<ExtArgs> | null
  where?: Prisma.HelpContactSubmissionImageWhereInput
  orderBy?: Prisma.HelpContactSubmissionImageOrderByWithRelationInput | Prisma.HelpContactSubmissionImageOrderByWithRelationInput[]
  cursor?: Prisma.HelpContactSubmissionImageWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.HelpContactSubmissionImageScalarFieldEnum | Prisma.HelpContactSubmissionImageScalarFieldEnum[]
}

/**
 * Image without action
 */
export type ImageDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Image
   */
  select?: Prisma.ImageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Image
   */
  omit?: Prisma.ImageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ImageInclude<ExtArgs> | null
}
