
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ProductCategoryTranslation` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ProductCategoryTranslation
 * 
 */
export type ProductCategoryTranslationModel = runtime.Types.Result.DefaultSelection<Prisma.$ProductCategoryTranslationPayload>

export type AggregateProductCategoryTranslation = {
  _count: ProductCategoryTranslationCountAggregateOutputType | null
  _min: ProductCategoryTranslationMinAggregateOutputType | null
  _max: ProductCategoryTranslationMaxAggregateOutputType | null
}

export type ProductCategoryTranslationMinAggregateOutputType = {
  id: string | null
  category_id: string | null
  language_id: string | null
  name: string | null
  description: string | null
}

export type ProductCategoryTranslationMaxAggregateOutputType = {
  id: string | null
  category_id: string | null
  language_id: string | null
  name: string | null
  description: string | null
}

export type ProductCategoryTranslationCountAggregateOutputType = {
  id: number
  category_id: number
  language_id: number
  name: number
  description: number
  _all: number
}


export type ProductCategoryTranslationMinAggregateInputType = {
  id?: true
  category_id?: true
  language_id?: true
  name?: true
  description?: true
}

export type ProductCategoryTranslationMaxAggregateInputType = {
  id?: true
  category_id?: true
  language_id?: true
  name?: true
  description?: true
}

export type ProductCategoryTranslationCountAggregateInputType = {
  id?: true
  category_id?: true
  language_id?: true
  name?: true
  description?: true
  _all?: true
}

export type ProductCategoryTranslationAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ProductCategoryTranslation to aggregate.
   */
  where?: Prisma.ProductCategoryTranslationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProductCategoryTranslations to fetch.
   */
  orderBy?: Prisma.ProductCategoryTranslationOrderByWithRelationInput | Prisma.ProductCategoryTranslationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ProductCategoryTranslationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProductCategoryTranslations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProductCategoryTranslations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ProductCategoryTranslations
  **/
  _count?: true | ProductCategoryTranslationCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ProductCategoryTranslationMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ProductCategoryTranslationMaxAggregateInputType
}

export type GetProductCategoryTranslationAggregateType<T extends ProductCategoryTranslationAggregateArgs> = {
      [P in keyof T & keyof AggregateProductCategoryTranslation]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateProductCategoryTranslation[P]>
    : Prisma.GetScalarType<T[P], AggregateProductCategoryTranslation[P]>
}




export type ProductCategoryTranslationGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ProductCategoryTranslationWhereInput
  orderBy?: Prisma.ProductCategoryTranslationOrderByWithAggregationInput | Prisma.ProductCategoryTranslationOrderByWithAggregationInput[]
  by: Prisma.ProductCategoryTranslationScalarFieldEnum[] | Prisma.ProductCategoryTranslationScalarFieldEnum
  having?: Prisma.ProductCategoryTranslationScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ProductCategoryTranslationCountAggregateInputType | true
  _min?: ProductCategoryTranslationMinAggregateInputType
  _max?: ProductCategoryTranslationMaxAggregateInputType
}

export type ProductCategoryTranslationGroupByOutputType = {
  id: string
  category_id: string
  language_id: string
  name: string
  description: string | null
  _count: ProductCategoryTranslationCountAggregateOutputType | null
  _min: ProductCategoryTranslationMinAggregateOutputType | null
  _max: ProductCategoryTranslationMaxAggregateOutputType | null
}

export type GetProductCategoryTranslationGroupByPayload<T extends ProductCategoryTranslationGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ProductCategoryTranslationGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ProductCategoryTranslationGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ProductCategoryTranslationGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ProductCategoryTranslationGroupByOutputType[P]>
      }
    >
  >



export type ProductCategoryTranslationWhereInput = {
  AND?: Prisma.ProductCategoryTranslationWhereInput | Prisma.ProductCategoryTranslationWhereInput[]
  OR?: Prisma.ProductCategoryTranslationWhereInput[]
  NOT?: Prisma.ProductCategoryTranslationWhereInput | Prisma.ProductCategoryTranslationWhereInput[]
  id?: Prisma.StringFilter<"ProductCategoryTranslation"> | string
  category_id?: Prisma.StringFilter<"ProductCategoryTranslation"> | string
  language_id?: Prisma.StringFilter<"ProductCategoryTranslation"> | string
  name?: Prisma.StringFilter<"ProductCategoryTranslation"> | string
  description?: Prisma.StringNullableFilter<"ProductCategoryTranslation"> | string | null
  category?: Prisma.XOR<Prisma.ProductCategoryScalarRelationFilter, Prisma.ProductCategoryWhereInput>
  language?: Prisma.XOR<Prisma.LanguageScalarRelationFilter, Prisma.LanguageWhereInput>
}

export type ProductCategoryTranslationOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  category_id?: Prisma.SortOrder
  language_id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  category?: Prisma.ProductCategoryOrderByWithRelationInput
  language?: Prisma.LanguageOrderByWithRelationInput
}

export type ProductCategoryTranslationWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  category_id_language_id?: Prisma.ProductCategoryTranslationCategory_idLanguage_idCompoundUniqueInput
  AND?: Prisma.ProductCategoryTranslationWhereInput | Prisma.ProductCategoryTranslationWhereInput[]
  OR?: Prisma.ProductCategoryTranslationWhereInput[]
  NOT?: Prisma.ProductCategoryTranslationWhereInput | Prisma.ProductCategoryTranslationWhereInput[]
  category_id?: Prisma.StringFilter<"ProductCategoryTranslation"> | string
  language_id?: Prisma.StringFilter<"ProductCategoryTranslation"> | string
  name?: Prisma.StringFilter<"ProductCategoryTranslation"> | string
  description?: Prisma.StringNullableFilter<"ProductCategoryTranslation"> | string | null
  category?: Prisma.XOR<Prisma.ProductCategoryScalarRelationFilter, Prisma.ProductCategoryWhereInput>
  language?: Prisma.XOR<Prisma.LanguageScalarRelationFilter, Prisma.LanguageWhereInput>
}, "id" | "category_id_language_id">

export type ProductCategoryTranslationOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  category_id?: Prisma.SortOrder
  language_id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.ProductCategoryTranslationCountOrderByAggregateInput
  _max?: Prisma.ProductCategoryTranslationMaxOrderByAggregateInput
  _min?: Prisma.ProductCategoryTranslationMinOrderByAggregateInput
}

export type ProductCategoryTranslationScalarWhereWithAggregatesInput = {
  AND?: Prisma.ProductCategoryTranslationScalarWhereWithAggregatesInput | Prisma.ProductCategoryTranslationScalarWhereWithAggregatesInput[]
  OR?: Prisma.ProductCategoryTranslationScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ProductCategoryTranslationScalarWhereWithAggregatesInput | Prisma.ProductCategoryTranslationScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ProductCategoryTranslation"> | string
  category_id?: Prisma.StringWithAggregatesFilter<"ProductCategoryTranslation"> | string
  language_id?: Prisma.StringWithAggregatesFilter<"ProductCategoryTranslation"> | string
  name?: Prisma.StringWithAggregatesFilter<"ProductCategoryTranslation"> | string
  description?: Prisma.StringNullableWithAggregatesFilter<"ProductCategoryTranslation"> | string | null
}

export type ProductCategoryTranslationCreateInput = {
  id?: string
  name: string
  description?: string | null
  category: Prisma.ProductCategoryCreateNestedOneWithoutTranslationsInput
  language: Prisma.LanguageCreateNestedOneWithoutCategory_translationsInput
}

export type ProductCategoryTranslationUncheckedCreateInput = {
  id?: string
  category_id: string
  language_id: string
  name: string
  description?: string | null
}

export type ProductCategoryTranslationUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  category?: Prisma.ProductCategoryUpdateOneRequiredWithoutTranslationsNestedInput
  language?: Prisma.LanguageUpdateOneRequiredWithoutCategory_translationsNestedInput
}

export type ProductCategoryTranslationUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  category_id?: Prisma.StringFieldUpdateOperationsInput | string
  language_id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type ProductCategoryTranslationCreateManyInput = {
  id?: string
  category_id: string
  language_id: string
  name: string
  description?: string | null
}

export type ProductCategoryTranslationUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type ProductCategoryTranslationUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  category_id?: Prisma.StringFieldUpdateOperationsInput | string
  language_id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type ProductCategoryTranslationListRelationFilter = {
  every?: Prisma.ProductCategoryTranslationWhereInput
  some?: Prisma.ProductCategoryTranslationWhereInput
  none?: Prisma.ProductCategoryTranslationWhereInput
}

export type ProductCategoryTranslationOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ProductCategoryTranslationCategory_idLanguage_idCompoundUniqueInput = {
  category_id: string
  language_id: string
}

export type ProductCategoryTranslationCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  category_id?: Prisma.SortOrder
  language_id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
}

export type ProductCategoryTranslationMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  category_id?: Prisma.SortOrder
  language_id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
}

export type ProductCategoryTranslationMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  category_id?: Prisma.SortOrder
  language_id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
}

export type ProductCategoryTranslationCreateNestedManyWithoutCategoryInput = {
  create?: Prisma.XOR<Prisma.ProductCategoryTranslationCreateWithoutCategoryInput, Prisma.ProductCategoryTranslationUncheckedCreateWithoutCategoryInput> | Prisma.ProductCategoryTranslationCreateWithoutCategoryInput[] | Prisma.ProductCategoryTranslationUncheckedCreateWithoutCategoryInput[]
  connectOrCreate?: Prisma.ProductCategoryTranslationCreateOrConnectWithoutCategoryInput | Prisma.ProductCategoryTranslationCreateOrConnectWithoutCategoryInput[]
  createMany?: Prisma.ProductCategoryTranslationCreateManyCategoryInputEnvelope
  connect?: Prisma.ProductCategoryTranslationWhereUniqueInput | Prisma.ProductCategoryTranslationWhereUniqueInput[]
}

export type ProductCategoryTranslationUncheckedCreateNestedManyWithoutCategoryInput = {
  create?: Prisma.XOR<Prisma.ProductCategoryTranslationCreateWithoutCategoryInput, Prisma.ProductCategoryTranslationUncheckedCreateWithoutCategoryInput> | Prisma.ProductCategoryTranslationCreateWithoutCategoryInput[] | Prisma.ProductCategoryTranslationUncheckedCreateWithoutCategoryInput[]
  connectOrCreate?: Prisma.ProductCategoryTranslationCreateOrConnectWithoutCategoryInput | Prisma.ProductCategoryTranslationCreateOrConnectWithoutCategoryInput[]
  createMany?: Prisma.ProductCategoryTranslationCreateManyCategoryInputEnvelope
  connect?: Prisma.ProductCategoryTranslationWhereUniqueInput | Prisma.ProductCategoryTranslationWhereUniqueInput[]
}

export type ProductCategoryTranslationUpdateManyWithoutCategoryNestedInput = {
  create?: Prisma.XOR<Prisma.ProductCategoryTranslationCreateWithoutCategoryInput, Prisma.ProductCategoryTranslationUncheckedCreateWithoutCategoryInput> | Prisma.ProductCategoryTranslationCreateWithoutCategoryInput[] | Prisma.ProductCategoryTranslationUncheckedCreateWithoutCategoryInput[]
  connectOrCreate?: Prisma.ProductCategoryTranslationCreateOrConnectWithoutCategoryInput | Prisma.ProductCategoryTranslationCreateOrConnectWithoutCategoryInput[]
  upsert?: Prisma.ProductCategoryTranslationUpsertWithWhereUniqueWithoutCategoryInput | Prisma.ProductCategoryTranslationUpsertWithWhereUniqueWithoutCategoryInput[]
  createMany?: Prisma.ProductCategoryTranslationCreateManyCategoryInputEnvelope
  set?: Prisma.ProductCategoryTranslationWhereUniqueInput | Prisma.ProductCategoryTranslationWhereUniqueInput[]
  disconnect?: Prisma.ProductCategoryTranslationWhereUniqueInput | Prisma.ProductCategoryTranslationWhereUniqueInput[]
  delete?: Prisma.ProductCategoryTranslationWhereUniqueInput | Prisma.ProductCategoryTranslationWhereUniqueInput[]
  connect?: Prisma.ProductCategoryTranslationWhereUniqueInput | Prisma.ProductCategoryTranslationWhereUniqueInput[]
  update?: Prisma.ProductCategoryTranslationUpdateWithWhereUniqueWithoutCategoryInput | Prisma.ProductCategoryTranslationUpdateWithWhereUniqueWithoutCategoryInput[]
  updateMany?: Prisma.ProductCategoryTranslationUpdateManyWithWhereWithoutCategoryInput | Prisma.ProductCategoryTranslationUpdateManyWithWhereWithoutCategoryInput[]
  deleteMany?: Prisma.ProductCategoryTranslationScalarWhereInput | Prisma.ProductCategoryTranslationScalarWhereInput[]
}

export type ProductCategoryTranslationUncheckedUpdateManyWithoutCategoryNestedInput = {
  create?: Prisma.XOR<Prisma.ProductCategoryTranslationCreateWithoutCategoryInput, Prisma.ProductCategoryTranslationUncheckedCreateWithoutCategoryInput> | Prisma.ProductCategoryTranslationCreateWithoutCategoryInput[] | Prisma.ProductCategoryTranslationUncheckedCreateWithoutCategoryInput[]
  connectOrCreate?: Prisma.ProductCategoryTranslationCreateOrConnectWithoutCategoryInput | Prisma.ProductCategoryTranslationCreateOrConnectWithoutCategoryInput[]
  upsert?: Prisma.ProductCategoryTranslationUpsertWithWhereUniqueWithoutCategoryInput | Prisma.ProductCategoryTranslationUpsertWithWhereUniqueWithoutCategoryInput[]
  createMany?: Prisma.ProductCategoryTranslationCreateManyCategoryInputEnvelope
  set?: Prisma.ProductCategoryTranslationWhereUniqueInput | Prisma.ProductCategoryTranslationWhereUniqueInput[]
  disconnect?: Prisma.ProductCategoryTranslationWhereUniqueInput | Prisma.ProductCategoryTranslationWhereUniqueInput[]
  delete?: Prisma.ProductCategoryTranslationWhereUniqueInput | Prisma.ProductCategoryTranslationWhereUniqueInput[]
  connect?: Prisma.ProductCategoryTranslationWhereUniqueInput | Prisma.ProductCategoryTranslationWhereUniqueInput[]
  update?: Prisma.ProductCategoryTranslationUpdateWithWhereUniqueWithoutCategoryInput | Prisma.ProductCategoryTranslationUpdateWithWhereUniqueWithoutCategoryInput[]
  updateMany?: Prisma.ProductCategoryTranslationUpdateManyWithWhereWithoutCategoryInput | Prisma.ProductCategoryTranslationUpdateManyWithWhereWithoutCategoryInput[]
  deleteMany?: Prisma.ProductCategoryTranslationScalarWhereInput | Prisma.ProductCategoryTranslationScalarWhereInput[]
}

export type ProductCategoryTranslationCreateNestedManyWithoutLanguageInput = {
  create?: Prisma.XOR<Prisma.ProductCategoryTranslationCreateWithoutLanguageInput, Prisma.ProductCategoryTranslationUncheckedCreateWithoutLanguageInput> | Prisma.ProductCategoryTranslationCreateWithoutLanguageInput[] | Prisma.ProductCategoryTranslationUncheckedCreateWithoutLanguageInput[]
  connectOrCreate?: Prisma.ProductCategoryTranslationCreateOrConnectWithoutLanguageInput | Prisma.ProductCategoryTranslationCreateOrConnectWithoutLanguageInput[]
  createMany?: Prisma.ProductCategoryTranslationCreateManyLanguageInputEnvelope
  connect?: Prisma.ProductCategoryTranslationWhereUniqueInput | Prisma.ProductCategoryTranslationWhereUniqueInput[]
}

export type ProductCategoryTranslationUncheckedCreateNestedManyWithoutLanguageInput = {
  create?: Prisma.XOR<Prisma.ProductCategoryTranslationCreateWithoutLanguageInput, Prisma.ProductCategoryTranslationUncheckedCreateWithoutLanguageInput> | Prisma.ProductCategoryTranslationCreateWithoutLanguageInput[] | Prisma.ProductCategoryTranslationUncheckedCreateWithoutLanguageInput[]
  connectOrCreate?: Prisma.ProductCategoryTranslationCreateOrConnectWithoutLanguageInput | Prisma.ProductCategoryTranslationCreateOrConnectWithoutLanguageInput[]
  createMany?: Prisma.ProductCategoryTranslationCreateManyLanguageInputEnvelope
  connect?: Prisma.ProductCategoryTranslationWhereUniqueInput | Prisma.ProductCategoryTranslationWhereUniqueInput[]
}

export type ProductCategoryTranslationUpdateManyWithoutLanguageNestedInput = {
  create?: Prisma.XOR<Prisma.ProductCategoryTranslationCreateWithoutLanguageInput, Prisma.ProductCategoryTranslationUncheckedCreateWithoutLanguageInput> | Prisma.ProductCategoryTranslationCreateWithoutLanguageInput[] | Prisma.ProductCategoryTranslationUncheckedCreateWithoutLanguageInput[]
  connectOrCreate?: Prisma.ProductCategoryTranslationCreateOrConnectWithoutLanguageInput | Prisma.ProductCategoryTranslationCreateOrConnectWithoutLanguageInput[]
  upsert?: Prisma.ProductCategoryTranslationUpsertWithWhereUniqueWithoutLanguageInput | Prisma.ProductCategoryTranslationUpsertWithWhereUniqueWithoutLanguageInput[]
  createMany?: Prisma.ProductCategoryTranslationCreateManyLanguageInputEnvelope
  set?: Prisma.ProductCategoryTranslationWhereUniqueInput | Prisma.ProductCategoryTranslationWhereUniqueInput[]
  disconnect?: Prisma.ProductCategoryTranslationWhereUniqueInput | Prisma.ProductCategoryTranslationWhereUniqueInput[]
  delete?: Prisma.ProductCategoryTranslationWhereUniqueInput | Prisma.ProductCategoryTranslationWhereUniqueInput[]
  connect?: Prisma.ProductCategoryTranslationWhereUniqueInput | Prisma.ProductCategoryTranslationWhereUniqueInput[]
  update?: Prisma.ProductCategoryTranslationUpdateWithWhereUniqueWithoutLanguageInput | Prisma.ProductCategoryTranslationUpdateWithWhereUniqueWithoutLanguageInput[]
  updateMany?: Prisma.ProductCategoryTranslationUpdateManyWithWhereWithoutLanguageInput | Prisma.ProductCategoryTranslationUpdateManyWithWhereWithoutLanguageInput[]
  deleteMany?: Prisma.ProductCategoryTranslationScalarWhereInput | Prisma.ProductCategoryTranslationScalarWhereInput[]
}

export type ProductCategoryTranslationUncheckedUpdateManyWithoutLanguageNestedInput = {
  create?: Prisma.XOR<Prisma.ProductCategoryTranslationCreateWithoutLanguageInput, Prisma.ProductCategoryTranslationUncheckedCreateWithoutLanguageInput> | Prisma.ProductCategoryTranslationCreateWithoutLanguageInput[] | Prisma.ProductCategoryTranslationUncheckedCreateWithoutLanguageInput[]
  connectOrCreate?: Prisma.ProductCategoryTranslationCreateOrConnectWithoutLanguageInput | Prisma.ProductCategoryTranslationCreateOrConnectWithoutLanguageInput[]
  upsert?: Prisma.ProductCategoryTranslationUpsertWithWhereUniqueWithoutLanguageInput | Prisma.ProductCategoryTranslationUpsertWithWhereUniqueWithoutLanguageInput[]
  createMany?: Prisma.ProductCategoryTranslationCreateManyLanguageInputEnvelope
  set?: Prisma.ProductCategoryTranslationWhereUniqueInput | Prisma.ProductCategoryTranslationWhereUniqueInput[]
  disconnect?: Prisma.ProductCategoryTranslationWhereUniqueInput | Prisma.ProductCategoryTranslationWhereUniqueInput[]
  delete?: Prisma.ProductCategoryTranslationWhereUniqueInput | Prisma.ProductCategoryTranslationWhereUniqueInput[]
  connect?: Prisma.ProductCategoryTranslationWhereUniqueInput | Prisma.ProductCategoryTranslationWhereUniqueInput[]
  update?: Prisma.ProductCategoryTranslationUpdateWithWhereUniqueWithoutLanguageInput | Prisma.ProductCategoryTranslationUpdateWithWhereUniqueWithoutLanguageInput[]
  updateMany?: Prisma.ProductCategoryTranslationUpdateManyWithWhereWithoutLanguageInput | Prisma.ProductCategoryTranslationUpdateManyWithWhereWithoutLanguageInput[]
  deleteMany?: Prisma.ProductCategoryTranslationScalarWhereInput | Prisma.ProductCategoryTranslationScalarWhereInput[]
}

export type ProductCategoryTranslationCreateWithoutCategoryInput = {
  id?: string
  name: string
  description?: string | null
  language: Prisma.LanguageCreateNestedOneWithoutCategory_translationsInput
}

export type ProductCategoryTranslationUncheckedCreateWithoutCategoryInput = {
  id?: string
  language_id: string
  name: string
  description?: string | null
}

export type ProductCategoryTranslationCreateOrConnectWithoutCategoryInput = {
  where: Prisma.ProductCategoryTranslationWhereUniqueInput
  create: Prisma.XOR<Prisma.ProductCategoryTranslationCreateWithoutCategoryInput, Prisma.ProductCategoryTranslationUncheckedCreateWithoutCategoryInput>
}

export type ProductCategoryTranslationCreateManyCategoryInputEnvelope = {
  data: Prisma.ProductCategoryTranslationCreateManyCategoryInput | Prisma.ProductCategoryTranslationCreateManyCategoryInput[]
  skipDuplicates?: boolean
}

export type ProductCategoryTranslationUpsertWithWhereUniqueWithoutCategoryInput = {
  where: Prisma.ProductCategoryTranslationWhereUniqueInput
  update: Prisma.XOR<Prisma.ProductCategoryTranslationUpdateWithoutCategoryInput, Prisma.ProductCategoryTranslationUncheckedUpdateWithoutCategoryInput>
  create: Prisma.XOR<Prisma.ProductCategoryTranslationCreateWithoutCategoryInput, Prisma.ProductCategoryTranslationUncheckedCreateWithoutCategoryInput>
}

export type ProductCategoryTranslationUpdateWithWhereUniqueWithoutCategoryInput = {
  where: Prisma.ProductCategoryTranslationWhereUniqueInput
  data: Prisma.XOR<Prisma.ProductCategoryTranslationUpdateWithoutCategoryInput, Prisma.ProductCategoryTranslationUncheckedUpdateWithoutCategoryInput>
}

export type ProductCategoryTranslationUpdateManyWithWhereWithoutCategoryInput = {
  where: Prisma.ProductCategoryTranslationScalarWhereInput
  data: Prisma.XOR<Prisma.ProductCategoryTranslationUpdateManyMutationInput, Prisma.ProductCategoryTranslationUncheckedUpdateManyWithoutCategoryInput>
}

export type ProductCategoryTranslationScalarWhereInput = {
  AND?: Prisma.ProductCategoryTranslationScalarWhereInput | Prisma.ProductCategoryTranslationScalarWhereInput[]
  OR?: Prisma.ProductCategoryTranslationScalarWhereInput[]
  NOT?: Prisma.ProductCategoryTranslationScalarWhereInput | Prisma.ProductCategoryTranslationScalarWhereInput[]
  id?: Prisma.StringFilter<"ProductCategoryTranslation"> | string
  category_id?: Prisma.StringFilter<"ProductCategoryTranslation"> | string
  language_id?: Prisma.StringFilter<"ProductCategoryTranslation"> | string
  name?: Prisma.StringFilter<"ProductCategoryTranslation"> | string
  description?: Prisma.StringNullableFilter<"ProductCategoryTranslation"> | string | null
}

export type ProductCategoryTranslationCreateWithoutLanguageInput = {
  id?: string
  name: string
  description?: string | null
  category: Prisma.ProductCategoryCreateNestedOneWithoutTranslationsInput
}

export type ProductCategoryTranslationUncheckedCreateWithoutLanguageInput = {
  id?: string
  category_id: string
  name: string
  description?: string | null
}

export type ProductCategoryTranslationCreateOrConnectWithoutLanguageInput = {
  where: Prisma.ProductCategoryTranslationWhereUniqueInput
  create: Prisma.XOR<Prisma.ProductCategoryTranslationCreateWithoutLanguageInput, Prisma.ProductCategoryTranslationUncheckedCreateWithoutLanguageInput>
}

export type ProductCategoryTranslationCreateManyLanguageInputEnvelope = {
  data: Prisma.ProductCategoryTranslationCreateManyLanguageInput | Prisma.ProductCategoryTranslationCreateManyLanguageInput[]
  skipDuplicates?: boolean
}

export type ProductCategoryTranslationUpsertWithWhereUniqueWithoutLanguageInput = {
  where: Prisma.ProductCategoryTranslationWhereUniqueInput
  update: Prisma.XOR<Prisma.ProductCategoryTranslationUpdateWithoutLanguageInput, Prisma.ProductCategoryTranslationUncheckedUpdateWithoutLanguageInput>
  create: Prisma.XOR<Prisma.ProductCategoryTranslationCreateWithoutLanguageInput, Prisma.ProductCategoryTranslationUncheckedCreateWithoutLanguageInput>
}

export type ProductCategoryTranslationUpdateWithWhereUniqueWithoutLanguageInput = {
  where: Prisma.ProductCategoryTranslationWhereUniqueInput
  data: Prisma.XOR<Prisma.ProductCategoryTranslationUpdateWithoutLanguageInput, Prisma.ProductCategoryTranslationUncheckedUpdateWithoutLanguageInput>
}

export type ProductCategoryTranslationUpdateManyWithWhereWithoutLanguageInput = {
  where: Prisma.ProductCategoryTranslationScalarWhereInput
  data: Prisma.XOR<Prisma.ProductCategoryTranslationUpdateManyMutationInput, Prisma.ProductCategoryTranslationUncheckedUpdateManyWithoutLanguageInput>
}

export type ProductCategoryTranslationCreateManyCategoryInput = {
  id?: string
  language_id: string
  name: string
  description?: string | null
}

export type ProductCategoryTranslationUpdateWithoutCategoryInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  language?: Prisma.LanguageUpdateOneRequiredWithoutCategory_translationsNestedInput
}

export type ProductCategoryTranslationUncheckedUpdateWithoutCategoryInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  language_id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type ProductCategoryTranslationUncheckedUpdateManyWithoutCategoryInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  language_id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type ProductCategoryTranslationCreateManyLanguageInput = {
  id?: string
  category_id: string
  name: string
  description?: string | null
}

export type ProductCategoryTranslationUpdateWithoutLanguageInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  category?: Prisma.ProductCategoryUpdateOneRequiredWithoutTranslationsNestedInput
}

export type ProductCategoryTranslationUncheckedUpdateWithoutLanguageInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  category_id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type ProductCategoryTranslationUncheckedUpdateManyWithoutLanguageInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  category_id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}



export type ProductCategoryTranslationSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  category_id?: boolean
  language_id?: boolean
  name?: boolean
  description?: boolean
  category?: boolean | Prisma.ProductCategoryDefaultArgs<ExtArgs>
  language?: boolean | Prisma.LanguageDefaultArgs<ExtArgs>
}, ExtArgs["result"]["productCategoryTranslation"]>

export type ProductCategoryTranslationSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  category_id?: boolean
  language_id?: boolean
  name?: boolean
  description?: boolean
  category?: boolean | Prisma.ProductCategoryDefaultArgs<ExtArgs>
  language?: boolean | Prisma.LanguageDefaultArgs<ExtArgs>
}, ExtArgs["result"]["productCategoryTranslation"]>

export type ProductCategoryTranslationSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  category_id?: boolean
  language_id?: boolean
  name?: boolean
  description?: boolean
  category?: boolean | Prisma.ProductCategoryDefaultArgs<ExtArgs>
  language?: boolean | Prisma.LanguageDefaultArgs<ExtArgs>
}, ExtArgs["result"]["productCategoryTranslation"]>

export type ProductCategoryTranslationSelectScalar = {
  id?: boolean
  category_id?: boolean
  language_id?: boolean
  name?: boolean
  description?: boolean
}

export type ProductCategoryTranslationOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "category_id" | "language_id" | "name" | "description", ExtArgs["result"]["productCategoryTranslation"]>
export type ProductCategoryTranslationInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  category?: boolean | Prisma.ProductCategoryDefaultArgs<ExtArgs>
  language?: boolean | Prisma.LanguageDefaultArgs<ExtArgs>
}
export type ProductCategoryTranslationIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  category?: boolean | Prisma.ProductCategoryDefaultArgs<ExtArgs>
  language?: boolean | Prisma.LanguageDefaultArgs<ExtArgs>
}
export type ProductCategoryTranslationIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  category?: boolean | Prisma.ProductCategoryDefaultArgs<ExtArgs>
  language?: boolean | Prisma.LanguageDefaultArgs<ExtArgs>
}

export type $ProductCategoryTranslationPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ProductCategoryTranslation"
  objects: {
    category: Prisma.$ProductCategoryPayload<ExtArgs>
    language: Prisma.$LanguagePayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    category_id: string
    language_id: string
    name: string
    description: string | null
  }, ExtArgs["result"]["productCategoryTranslation"]>
  composites: {}
}

export type ProductCategoryTranslationGetPayload<S extends boolean | null | undefined | ProductCategoryTranslationDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ProductCategoryTranslationPayload, S>

export type ProductCategoryTranslationCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ProductCategoryTranslationFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ProductCategoryTranslationCountAggregateInputType | true
  }

export interface ProductCategoryTranslationDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ProductCategoryTranslation'], meta: { name: 'ProductCategoryTranslation' } }
  /**
   * Find zero or one ProductCategoryTranslation that matches the filter.
   * @param {ProductCategoryTranslationFindUniqueArgs} args - Arguments to find a ProductCategoryTranslation
   * @example
   * // Get one ProductCategoryTranslation
   * const productCategoryTranslation = await prisma.productCategoryTranslation.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ProductCategoryTranslationFindUniqueArgs>(args: Prisma.SelectSubset<T, ProductCategoryTranslationFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ProductCategoryTranslationClient<runtime.Types.Result.GetResult<Prisma.$ProductCategoryTranslationPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ProductCategoryTranslation that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ProductCategoryTranslationFindUniqueOrThrowArgs} args - Arguments to find a ProductCategoryTranslation
   * @example
   * // Get one ProductCategoryTranslation
   * const productCategoryTranslation = await prisma.productCategoryTranslation.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ProductCategoryTranslationFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ProductCategoryTranslationFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProductCategoryTranslationClient<runtime.Types.Result.GetResult<Prisma.$ProductCategoryTranslationPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ProductCategoryTranslation that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductCategoryTranslationFindFirstArgs} args - Arguments to find a ProductCategoryTranslation
   * @example
   * // Get one ProductCategoryTranslation
   * const productCategoryTranslation = await prisma.productCategoryTranslation.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ProductCategoryTranslationFindFirstArgs>(args?: Prisma.SelectSubset<T, ProductCategoryTranslationFindFirstArgs<ExtArgs>>): Prisma.Prisma__ProductCategoryTranslationClient<runtime.Types.Result.GetResult<Prisma.$ProductCategoryTranslationPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ProductCategoryTranslation that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductCategoryTranslationFindFirstOrThrowArgs} args - Arguments to find a ProductCategoryTranslation
   * @example
   * // Get one ProductCategoryTranslation
   * const productCategoryTranslation = await prisma.productCategoryTranslation.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ProductCategoryTranslationFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ProductCategoryTranslationFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProductCategoryTranslationClient<runtime.Types.Result.GetResult<Prisma.$ProductCategoryTranslationPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ProductCategoryTranslations that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductCategoryTranslationFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ProductCategoryTranslations
   * const productCategoryTranslations = await prisma.productCategoryTranslation.findMany()
   * 
   * // Get first 10 ProductCategoryTranslations
   * const productCategoryTranslations = await prisma.productCategoryTranslation.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const productCategoryTranslationWithIdOnly = await prisma.productCategoryTranslation.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ProductCategoryTranslationFindManyArgs>(args?: Prisma.SelectSubset<T, ProductCategoryTranslationFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProductCategoryTranslationPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ProductCategoryTranslation.
   * @param {ProductCategoryTranslationCreateArgs} args - Arguments to create a ProductCategoryTranslation.
   * @example
   * // Create one ProductCategoryTranslation
   * const ProductCategoryTranslation = await prisma.productCategoryTranslation.create({
   *   data: {
   *     // ... data to create a ProductCategoryTranslation
   *   }
   * })
   * 
   */
  create<T extends ProductCategoryTranslationCreateArgs>(args: Prisma.SelectSubset<T, ProductCategoryTranslationCreateArgs<ExtArgs>>): Prisma.Prisma__ProductCategoryTranslationClient<runtime.Types.Result.GetResult<Prisma.$ProductCategoryTranslationPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ProductCategoryTranslations.
   * @param {ProductCategoryTranslationCreateManyArgs} args - Arguments to create many ProductCategoryTranslations.
   * @example
   * // Create many ProductCategoryTranslations
   * const productCategoryTranslation = await prisma.productCategoryTranslation.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ProductCategoryTranslationCreateManyArgs>(args?: Prisma.SelectSubset<T, ProductCategoryTranslationCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ProductCategoryTranslations and returns the data saved in the database.
   * @param {ProductCategoryTranslationCreateManyAndReturnArgs} args - Arguments to create many ProductCategoryTranslations.
   * @example
   * // Create many ProductCategoryTranslations
   * const productCategoryTranslation = await prisma.productCategoryTranslation.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ProductCategoryTranslations and only return the `id`
   * const productCategoryTranslationWithIdOnly = await prisma.productCategoryTranslation.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ProductCategoryTranslationCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ProductCategoryTranslationCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProductCategoryTranslationPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ProductCategoryTranslation.
   * @param {ProductCategoryTranslationDeleteArgs} args - Arguments to delete one ProductCategoryTranslation.
   * @example
   * // Delete one ProductCategoryTranslation
   * const ProductCategoryTranslation = await prisma.productCategoryTranslation.delete({
   *   where: {
   *     // ... filter to delete one ProductCategoryTranslation
   *   }
   * })
   * 
   */
  delete<T extends ProductCategoryTranslationDeleteArgs>(args: Prisma.SelectSubset<T, ProductCategoryTranslationDeleteArgs<ExtArgs>>): Prisma.Prisma__ProductCategoryTranslationClient<runtime.Types.Result.GetResult<Prisma.$ProductCategoryTranslationPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ProductCategoryTranslation.
   * @param {ProductCategoryTranslationUpdateArgs} args - Arguments to update one ProductCategoryTranslation.
   * @example
   * // Update one ProductCategoryTranslation
   * const productCategoryTranslation = await prisma.productCategoryTranslation.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ProductCategoryTranslationUpdateArgs>(args: Prisma.SelectSubset<T, ProductCategoryTranslationUpdateArgs<ExtArgs>>): Prisma.Prisma__ProductCategoryTranslationClient<runtime.Types.Result.GetResult<Prisma.$ProductCategoryTranslationPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ProductCategoryTranslations.
   * @param {ProductCategoryTranslationDeleteManyArgs} args - Arguments to filter ProductCategoryTranslations to delete.
   * @example
   * // Delete a few ProductCategoryTranslations
   * const { count } = await prisma.productCategoryTranslation.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ProductCategoryTranslationDeleteManyArgs>(args?: Prisma.SelectSubset<T, ProductCategoryTranslationDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ProductCategoryTranslations.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductCategoryTranslationUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ProductCategoryTranslations
   * const productCategoryTranslation = await prisma.productCategoryTranslation.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ProductCategoryTranslationUpdateManyArgs>(args: Prisma.SelectSubset<T, ProductCategoryTranslationUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ProductCategoryTranslations and returns the data updated in the database.
   * @param {ProductCategoryTranslationUpdateManyAndReturnArgs} args - Arguments to update many ProductCategoryTranslations.
   * @example
   * // Update many ProductCategoryTranslations
   * const productCategoryTranslation = await prisma.productCategoryTranslation.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ProductCategoryTranslations and only return the `id`
   * const productCategoryTranslationWithIdOnly = await prisma.productCategoryTranslation.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ProductCategoryTranslationUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ProductCategoryTranslationUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProductCategoryTranslationPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ProductCategoryTranslation.
   * @param {ProductCategoryTranslationUpsertArgs} args - Arguments to update or create a ProductCategoryTranslation.
   * @example
   * // Update or create a ProductCategoryTranslation
   * const productCategoryTranslation = await prisma.productCategoryTranslation.upsert({
   *   create: {
   *     // ... data to create a ProductCategoryTranslation
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ProductCategoryTranslation we want to update
   *   }
   * })
   */
  upsert<T extends ProductCategoryTranslationUpsertArgs>(args: Prisma.SelectSubset<T, ProductCategoryTranslationUpsertArgs<ExtArgs>>): Prisma.Prisma__ProductCategoryTranslationClient<runtime.Types.Result.GetResult<Prisma.$ProductCategoryTranslationPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ProductCategoryTranslations.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductCategoryTranslationCountArgs} args - Arguments to filter ProductCategoryTranslations to count.
   * @example
   * // Count the number of ProductCategoryTranslations
   * const count = await prisma.productCategoryTranslation.count({
   *   where: {
   *     // ... the filter for the ProductCategoryTranslations we want to count
   *   }
   * })
  **/
  count<T extends ProductCategoryTranslationCountArgs>(
    args?: Prisma.Subset<T, ProductCategoryTranslationCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ProductCategoryTranslationCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ProductCategoryTranslation.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductCategoryTranslationAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ProductCategoryTranslationAggregateArgs>(args: Prisma.Subset<T, ProductCategoryTranslationAggregateArgs>): Prisma.PrismaPromise<GetProductCategoryTranslationAggregateType<T>>

  /**
   * Group by ProductCategoryTranslation.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductCategoryTranslationGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ProductCategoryTranslationGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ProductCategoryTranslationGroupByArgs['orderBy'] }
      : { orderBy?: ProductCategoryTranslationGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ProductCategoryTranslationGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetProductCategoryTranslationGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ProductCategoryTranslation model
 */
readonly fields: ProductCategoryTranslationFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ProductCategoryTranslation.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ProductCategoryTranslationClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  category<T extends Prisma.ProductCategoryDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProductCategoryDefaultArgs<ExtArgs>>): Prisma.Prisma__ProductCategoryClient<runtime.Types.Result.GetResult<Prisma.$ProductCategoryPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  language<T extends Prisma.LanguageDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.LanguageDefaultArgs<ExtArgs>>): Prisma.Prisma__LanguageClient<runtime.Types.Result.GetResult<Prisma.$LanguagePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ProductCategoryTranslation model
 */
export interface ProductCategoryTranslationFieldRefs {
  readonly id: Prisma.FieldRef<"ProductCategoryTranslation", 'String'>
  readonly category_id: Prisma.FieldRef<"ProductCategoryTranslation", 'String'>
  readonly language_id: Prisma.FieldRef<"ProductCategoryTranslation", 'String'>
  readonly name: Prisma.FieldRef<"ProductCategoryTranslation", 'String'>
  readonly description: Prisma.FieldRef<"ProductCategoryTranslation", 'String'>
}
    

// Custom InputTypes
/**
 * ProductCategoryTranslation findUnique
 */
export type ProductCategoryTranslationFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductCategoryTranslation
   */
  select?: Prisma.ProductCategoryTranslationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductCategoryTranslation
   */
  omit?: Prisma.ProductCategoryTranslationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductCategoryTranslationInclude<ExtArgs> | null
  /**
   * Filter, which ProductCategoryTranslation to fetch.
   */
  where: Prisma.ProductCategoryTranslationWhereUniqueInput
}

/**
 * ProductCategoryTranslation findUniqueOrThrow
 */
export type ProductCategoryTranslationFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductCategoryTranslation
   */
  select?: Prisma.ProductCategoryTranslationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductCategoryTranslation
   */
  omit?: Prisma.ProductCategoryTranslationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductCategoryTranslationInclude<ExtArgs> | null
  /**
   * Filter, which ProductCategoryTranslation to fetch.
   */
  where: Prisma.ProductCategoryTranslationWhereUniqueInput
}

/**
 * ProductCategoryTranslation findFirst
 */
export type ProductCategoryTranslationFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductCategoryTranslation
   */
  select?: Prisma.ProductCategoryTranslationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductCategoryTranslation
   */
  omit?: Prisma.ProductCategoryTranslationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductCategoryTranslationInclude<ExtArgs> | null
  /**
   * Filter, which ProductCategoryTranslation to fetch.
   */
  where?: Prisma.ProductCategoryTranslationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProductCategoryTranslations to fetch.
   */
  orderBy?: Prisma.ProductCategoryTranslationOrderByWithRelationInput | Prisma.ProductCategoryTranslationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ProductCategoryTranslations.
   */
  cursor?: Prisma.ProductCategoryTranslationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProductCategoryTranslations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProductCategoryTranslations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ProductCategoryTranslations.
   */
  distinct?: Prisma.ProductCategoryTranslationScalarFieldEnum | Prisma.ProductCategoryTranslationScalarFieldEnum[]
}

/**
 * ProductCategoryTranslation findFirstOrThrow
 */
export type ProductCategoryTranslationFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductCategoryTranslation
   */
  select?: Prisma.ProductCategoryTranslationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductCategoryTranslation
   */
  omit?: Prisma.ProductCategoryTranslationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductCategoryTranslationInclude<ExtArgs> | null
  /**
   * Filter, which ProductCategoryTranslation to fetch.
   */
  where?: Prisma.ProductCategoryTranslationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProductCategoryTranslations to fetch.
   */
  orderBy?: Prisma.ProductCategoryTranslationOrderByWithRelationInput | Prisma.ProductCategoryTranslationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ProductCategoryTranslations.
   */
  cursor?: Prisma.ProductCategoryTranslationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProductCategoryTranslations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProductCategoryTranslations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ProductCategoryTranslations.
   */
  distinct?: Prisma.ProductCategoryTranslationScalarFieldEnum | Prisma.ProductCategoryTranslationScalarFieldEnum[]
}

/**
 * ProductCategoryTranslation findMany
 */
export type ProductCategoryTranslationFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductCategoryTranslation
   */
  select?: Prisma.ProductCategoryTranslationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductCategoryTranslation
   */
  omit?: Prisma.ProductCategoryTranslationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductCategoryTranslationInclude<ExtArgs> | null
  /**
   * Filter, which ProductCategoryTranslations to fetch.
   */
  where?: Prisma.ProductCategoryTranslationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProductCategoryTranslations to fetch.
   */
  orderBy?: Prisma.ProductCategoryTranslationOrderByWithRelationInput | Prisma.ProductCategoryTranslationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ProductCategoryTranslations.
   */
  cursor?: Prisma.ProductCategoryTranslationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProductCategoryTranslations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProductCategoryTranslations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ProductCategoryTranslations.
   */
  distinct?: Prisma.ProductCategoryTranslationScalarFieldEnum | Prisma.ProductCategoryTranslationScalarFieldEnum[]
}

/**
 * ProductCategoryTranslation create
 */
export type ProductCategoryTranslationCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductCategoryTranslation
   */
  select?: Prisma.ProductCategoryTranslationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductCategoryTranslation
   */
  omit?: Prisma.ProductCategoryTranslationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductCategoryTranslationInclude<ExtArgs> | null
  /**
   * The data needed to create a ProductCategoryTranslation.
   */
  data: Prisma.XOR<Prisma.ProductCategoryTranslationCreateInput, Prisma.ProductCategoryTranslationUncheckedCreateInput>
}

/**
 * ProductCategoryTranslation createMany
 */
export type ProductCategoryTranslationCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ProductCategoryTranslations.
   */
  data: Prisma.ProductCategoryTranslationCreateManyInput | Prisma.ProductCategoryTranslationCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ProductCategoryTranslation createManyAndReturn
 */
export type ProductCategoryTranslationCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductCategoryTranslation
   */
  select?: Prisma.ProductCategoryTranslationSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ProductCategoryTranslation
   */
  omit?: Prisma.ProductCategoryTranslationOmit<ExtArgs> | null
  /**
   * The data used to create many ProductCategoryTranslations.
   */
  data: Prisma.ProductCategoryTranslationCreateManyInput | Prisma.ProductCategoryTranslationCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductCategoryTranslationIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ProductCategoryTranslation update
 */
export type ProductCategoryTranslationUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductCategoryTranslation
   */
  select?: Prisma.ProductCategoryTranslationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductCategoryTranslation
   */
  omit?: Prisma.ProductCategoryTranslationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductCategoryTranslationInclude<ExtArgs> | null
  /**
   * The data needed to update a ProductCategoryTranslation.
   */
  data: Prisma.XOR<Prisma.ProductCategoryTranslationUpdateInput, Prisma.ProductCategoryTranslationUncheckedUpdateInput>
  /**
   * Choose, which ProductCategoryTranslation to update.
   */
  where: Prisma.ProductCategoryTranslationWhereUniqueInput
}

/**
 * ProductCategoryTranslation updateMany
 */
export type ProductCategoryTranslationUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ProductCategoryTranslations.
   */
  data: Prisma.XOR<Prisma.ProductCategoryTranslationUpdateManyMutationInput, Prisma.ProductCategoryTranslationUncheckedUpdateManyInput>
  /**
   * Filter which ProductCategoryTranslations to update
   */
  where?: Prisma.ProductCategoryTranslationWhereInput
  /**
   * Limit how many ProductCategoryTranslations to update.
   */
  limit?: number
}

/**
 * ProductCategoryTranslation updateManyAndReturn
 */
export type ProductCategoryTranslationUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductCategoryTranslation
   */
  select?: Prisma.ProductCategoryTranslationSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ProductCategoryTranslation
   */
  omit?: Prisma.ProductCategoryTranslationOmit<ExtArgs> | null
  /**
   * The data used to update ProductCategoryTranslations.
   */
  data: Prisma.XOR<Prisma.ProductCategoryTranslationUpdateManyMutationInput, Prisma.ProductCategoryTranslationUncheckedUpdateManyInput>
  /**
   * Filter which ProductCategoryTranslations to update
   */
  where?: Prisma.ProductCategoryTranslationWhereInput
  /**
   * Limit how many ProductCategoryTranslations to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductCategoryTranslationIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ProductCategoryTranslation upsert
 */
export type ProductCategoryTranslationUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductCategoryTranslation
   */
  select?: Prisma.ProductCategoryTranslationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductCategoryTranslation
   */
  omit?: Prisma.ProductCategoryTranslationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductCategoryTranslationInclude<ExtArgs> | null
  /**
   * The filter to search for the ProductCategoryTranslation to update in case it exists.
   */
  where: Prisma.ProductCategoryTranslationWhereUniqueInput
  /**
   * In case the ProductCategoryTranslation found by the `where` argument doesn't exist, create a new ProductCategoryTranslation with this data.
   */
  create: Prisma.XOR<Prisma.ProductCategoryTranslationCreateInput, Prisma.ProductCategoryTranslationUncheckedCreateInput>
  /**
   * In case the ProductCategoryTranslation was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ProductCategoryTranslationUpdateInput, Prisma.ProductCategoryTranslationUncheckedUpdateInput>
}

/**
 * ProductCategoryTranslation delete
 */
export type ProductCategoryTranslationDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductCategoryTranslation
   */
  select?: Prisma.ProductCategoryTranslationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductCategoryTranslation
   */
  omit?: Prisma.ProductCategoryTranslationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductCategoryTranslationInclude<ExtArgs> | null
  /**
   * Filter which ProductCategoryTranslation to delete.
   */
  where: Prisma.ProductCategoryTranslationWhereUniqueInput
}

/**
 * ProductCategoryTranslation deleteMany
 */
export type ProductCategoryTranslationDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ProductCategoryTranslations to delete
   */
  where?: Prisma.ProductCategoryTranslationWhereInput
  /**
   * Limit how many ProductCategoryTranslations to delete.
   */
  limit?: number
}

/**
 * ProductCategoryTranslation without action
 */
export type ProductCategoryTranslationDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductCategoryTranslation
   */
  select?: Prisma.ProductCategoryTranslationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductCategoryTranslation
   */
  omit?: Prisma.ProductCategoryTranslationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductCategoryTranslationInclude<ExtArgs> | null
}
