/** @description Application route paths */
export const CALLBACK_URL_KEY = "callbackUrl";

export const APP_ROUTES = {
  HOME: "/",
  SIGN_IN: "/sign-in",
  SIGN_UP: "/sign-up",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",
  PROFILE: "/profile",
  TERMS: "/terms",
  PRIVACY: "/privacy",
  DOCS: "/docs",
  CATEGORIES: "/categories",
  CATEGORY_DETAIL: (slug: string) => `/categories/${slug}`,
  PRODUCT_DETAIL: (slug: string) => `/products/${slug}`,
  CART: "/cart",
  CHECKOUT: "/checkout",
  ORDERS: "/orders",
  ORDER_DETAIL: (id: string) => `/orders/${id}`,
  PRODUCTS: "/products",
  SEARCH: "/search",
  SETTINGS: "/settings",
  HELP: "/help",
  FAQ: "/help/faq",
  SHIPPING: "/help/shipping",
  CONTACT: "/help/contact",
  VOUCHERS: "/vouchers",
  ALL_BRANDS: "/brands",
  BRAND_DETAIL: (slug: string) => `/brands/${slug}`,
  NEW_ARRIVALS: "/new-arrivals",
  RECENTLY_VIEWED: "/recent-viewed",
  FLASH_SALE: "/flash-sale",
  FAVORITES: "/favorites",
} as const;

/** @description API endpoint paths */
export const API_ROUTES = {
  AUTH: {
    LOGIN: "/auth/login",
    REGISTER: "/auth/register",
    ME: "/auth/me",
    LOGOUT: "/auth/logout",
    REFRESH_TOKEN: "/auth/refresh-token",
    FORGOT_PASSWORD: "/auth/forgot-password",
    RESET_PASSWORD: "/auth/reset-password",
    CHANGE_PASSWORD: "/auth/change-password",
  },
  USERS: {
    PROFILE: "/users/profile",
    UPLOAD_AVATAR: (userId: string) => `/users/${userId}/avatar`,
  },
  PRODUCTS: {
    BASE: "/products",
    RECOMMENDED: "/products/recommended",
    BASED_ON_INTEREST: "/products/based-on-interest",
    RECENTLY_VIEWED: "/products/recently-viewed",
    FLASH_SALE: "/products/flash-sale",
    DETAIL_BY_SLUG: (slug: string) => `/products/${slug}`,
    REVIEWS: (id: string) => `/products/${id}/reviews`,
    SIMILAR: (id: string) => `/products/${id}/similar`,
  },
  REVIEWS: {
    BASE: "/reviews",
  },
  PRODUCT_CATEGORIES: {
    BASE: "/product-categories",
    TREE: "/product-categories/tree",
    GROUPS: "/product-categories/groups",
  },
  BRAND: {
    TOP: "/brands/top",
    BASE: "/brands",
    DETAIL: (slug: string) => `/brands/${slug}`,
    PRODUCTS: (slug: string) => `/brands/${slug}/products`,
  },
  HOMEPAGE: {
    SECTIONS: "/homepage/sections",
  },
  ORDERS: {
    BASE: "/orders",
    MINE: "/orders",
    ALL: "/orders/all",
    DETAIL: (id: string) => `/orders/${id}`,
    CANCEL: (id: string) => `/orders/${id}/cancel`,
    UPDATE_STATUS: (id: string) => `/orders/${id}/status`,
  },
  ORDER_RETURNS: {
    BASE: "/order-returns",
    CREATE: (orderId: string) => `/order-returns/${orderId}`,
    CANCEL: (returnId: string) => `/order-returns/${returnId}/cancel`,
    UPDATE_STATUS: (returnId: string) => `/order-returns/${returnId}/status`,
  },
  ADDRESSES: {
    BASE: "/addresses",
    MINE: "/addresses",
    DEFAULT: "/addresses/default",
  },
  CART: {
    BASE: "/cart",
    ITEMS: "/cart/items",
    ITEM: (id: string) => `/cart/items/${id}`,
  },
  NOTIFICATIONS: {
    BASE: "/notifications",
    UNREAD_COUNT: "/notifications/unread-count",
    TOKENS: "/notifications/tokens",
    MARK_AS_READ: (id: string) => `/notifications/${id}/read`,
    MARK_ALL_AS_READ: "/notifications/read-all",
  },
  UPLOAD: {
    IMAGE: "/upload/image",
    HELP_CONTACT_IMAGE: "/upload/help-contact-image",
  },
  HELP_CONTACT_SUBMISSIONS: {
    BASE: "/help-contact-submissions",
  },
  FLASH_SALES: {
    BASE: "/flash-sales",
    TIME_SLOTS: "/flash-sales/time-slots",
    BATCH: "/flash-sales/batch",
    ADD_PRODUCTS: (id: string) => `/flash-sales/${id}/products`,
  },
  CONFIG: "/config",
} as const;
