console.log("AVAILABLE COMMANDS IN MONOREPO:");
console.log("-----------------------------------");
console.log("npm run dev        - Start Backend, Frontend, and Shared watcher");
console.log("npm run dev:shared - Start Shared package watcher only");
console.log("-----------------------------------");
console.log("npm run dev:be     - Start Backend only");
console.log("npm run dev:be:shared - Start Backend with Shared watcher");
console.log("npm run build:be   - Build Backend to dist folder");
console.log("npm run test:be    - Run tests for Backend");
console.log("npm run lint:be    - Check code style for Backend");
console.log("npm run format:be  - Auto format code for Backend");
console.log("-----------------------------------");
console.log("npm run dev:fe     - Start Frontend only");
console.log("npm run dev:fe:shared - Start Frontend with Shared watcher");
console.log("npm run build:fe   - Build Frontend");
console.log("npm run lint:fe    - Check code style for Frontend");
console.log("-----------------------------------");
console.log("npm run build      - Build all projects");
console.log("npm run test       - Run tests for all projects");
console.log("npm run type-check - Type check Frontend");
