export const TOP_BRANDS_DATA = [
  {
    name: 'Apple',
    slug: 'apple',
    description_en: 'Premium technology and iconic design.',
    description_vi: 'Công nghệ đỉnh cao và thiết kế biểu tượng.',
    story_en: 'Discover the world of Apple. From iPhone 15 Pro to MacBook Pro with M3 chips.',
    story_vi: 'Khám phá thế giới Apple. Từ iPhone 15 Pro đến MacBook Pro chip M3.',
    founded_year: 1976,
    headquarters: 'Cupertino, California, USA',
    website: 'https://www.apple.com',
    logo: 'https://cdn.simpleicons.org/apple/black',
    banner: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?q=80&w=2026&auto=format&fit=crop',
    images: [],
    keywords: ['iphone', 'ipad', 'macbook', 'apple'],
  },
  {
    name: 'Samsung',
    slug: 'samsung',
    description_en: 'Leading innovator in mobile and home entertainment.',
    description_vi: 'Dẫn đầu đổi mới trong di động và giải trí gia đình.',
    story_en: 'Samsung brings you the future today with Galaxy AI.',
    story_vi: 'Samsung mang đến tương lai ngay hôm nay với Galaxy AI.',
    founded_year: 1938,
    headquarters: 'Suwon, South Korea',
    website: 'https://www.samsung.com',
    logo: 'https://cdn.simpleicons.org/samsung/034EA2',
    banner: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?q=80&w=2070&auto=format&fit=crop',
    images: [],
    keywords: ['samsung', 'galaxy', 's24', 'qled'],
  },
  {
    name: 'Xiaomi',
    slug: 'xiaomi',
    description_en: 'Innovation for everyone at honest prices.',
    description_vi: 'Đổi mới cho mọi người với giá cả hợp lý.',
    story_en: 'Xiaomi makes high-end technology accessible.',
    story_vi: 'Xiaomi mang công nghệ cao cấp đến gần hơn với mọi người.',
    founded_year: 2010,
    headquarters: 'Beijing, China',
    website: 'https://www.mi.com',
    logo: 'https://cdn.simpleicons.org/xiaomi/FF6700',
    banner: 'https://images.unsplash.com/photo-1622440155250-934c7da87610?q=80&w=1974&auto=format&fit=crop',
    images: [],
    keywords: ['xiaomi', 'redmi', 'mi 14'],
  },
  {
    name: 'Sony',
    slug: 'sony',
    description_en: 'Premium audio, visual, and gaming experiences.',
    description_vi: 'Trải nghiệm âm thanh, hình ảnh và gaming đẳng cấp.',
    story_en: 'Experience the pinnacle of entertainment with Sony PS5.',
    story_vi: 'Trải nghiệm đỉnh cao giải trí cùng Sony PS5.',
    founded_year: 1946,
    headquarters: 'Minato, Tokyo, Japan',
    website: 'https://www.sony.com',
    logo: 'https://cdn.simpleicons.org/sony/000000',
    banner: 'https://images.unsplash.com/photo-1593305841991-05c297ba4575?q=80&w=2057&auto=format&fit=crop',
    images: [],
    keywords: ['sony', 'playstation', 'ps5'],
  },
  {
    name: 'Asus',
    slug: 'asus',
    description_en: 'In Search of Incredible. Leader in gaming.',
    description_vi: 'Tìm kiếm những điều phi thường. Dẫn đầu đổi mới gaming.',
    story_en: 'Asus pushes the boundaries with ROG and Zenbook.',
    story_vi: 'Asus phá vỡ mọi giới hạn với ROG và Zenbook.',
    founded_year: 1989,
    headquarters: 'Taipei, Taiwan',
    website: 'https://www.asus.com',
    logo: 'https://cdn.simpleicons.org/asus/0066B3',
    banner: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=2070&auto=format&fit=crop',
    images: [],
    keywords: ['asus', 'rog', 'zenbook'],
  },
  {
    name: 'Nike',
    slug: 'nike',
    description_en: 'Just Do It. Innovation for every athlete.',
    description_vi: 'Mang cảm hứng đến mọi vận động viên.',
    story_en: 'Nike is the global leader in sport.',
    story_vi: 'Nike là tập đoàn dẫn đầu toàn cầu về thể thao.',
    founded_year: 1964,
    headquarters: 'Beaverton, Oregon, USA',
    website: 'https://www.nike.com',
    logo: 'https://cdn.simpleicons.org/nike/000000',
    banner: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=80&w=2070&auto=format&fit=crop',
    images: [],
    keywords: ['nike', 'air max', 'jordan'],
  },
  {
    name: 'Garmin',
    slug: 'garmin',
    description_en: 'High-performance GPS navigation and wearables.',
    description_vi: 'Thiết bị định vị GPS và đồ đeo hiệu năng cao.',
    story_en: 'Garmin builds products engineered for life on the outside.',
    story_vi: 'Garmin tạo ra các sản phẩm cho cuộc sống năng động.',
    founded_year: 1989,
    headquarters: 'Olathe, Kansas, USA',
    website: 'https://www.garmin.com',
    logo: 'https://cdn.simpleicons.org/garmin/000000',
    banner: 'https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?q=80&w=2088&auto=format&fit=crop',
    images: [],
    keywords: ['garmin', 'fenix', 'forerunner'],
  },
  {
    name: 'Honda',
    slug: 'honda',
    description_en: 'The Power of Dreams. Quality you can trust.',
    description_vi: 'Sức mạnh của những ước mơ. Chất lượng tin cậy.',
    story_en: 'Honda is the world’s largest manufacturer of motorcycles.',
    story_vi: 'Honda là nhà sản xuất xe máy lớn nhất thế giới.',
    founded_year: 1948,
    headquarters: 'Tokyo, Japan',
    website: 'https://global.honda',
    logo: 'https://cdn.simpleicons.org/honda/E4000F',
    banner: 'https://images.unsplash.com/photo-1558981403-c5f91bb9c0f1?q=80&w=2070&auto=format&fit=crop',
    images: [],
    keywords: ['honda', 'sh150', 'vision'],
  },
];
